### ISSUE TITLE
[FEATURE] Pandas Series.map() is too slow

### ISSUE THREAD

**Issue by zegerius** [microsoft/recommenders#1022]
### Description
When generating internal user ids from external ids in `SARSingleNode.score`, the performance is abysmal. 

https://github.com/microsoft/recommenders/blob/9b6c065a77c07a60947e894a6b516be5cef14ca1/reco_utils/recommender/sar/sar_singlenode.py#L292

Our user2index has 114.401 keys (type uuid.UUID), a lookup with map takes on average 225ms, as demonstrated below:

```python
In [10]: %timeit test[model.col_user].drop_duplicates().map(model.user2index).values
225 ms ± 4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

where

```python
test = pd.DataFrame([uuid.UUID("xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx")], columns=["source"])
```

This seems extremely slow for a simple dict lookup.

Looking up all users results in ~484ms @ 114k users:

```python
In [84]: users = list(model.user2index.keys())

In [85]: test=pd.DataFrame(users, columns=["source"])

In [86]: %timeit test[model.col_user].drop_duplicates().map(model.user2index).values
484 ms ± 7.62 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

### Expected behavior with the suggested feature
Expected behavior: sub ms performance.

Besides a necessary change in Pandas, we can improve this fairly easily:

```python
In [11]: %timeit list(
                        map(
                            lambda user: model.user2index.get(user, np.NaN),
                            test[model.col_user].unique()
                        )
                    )
127 µs ± 1.81 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```

This is a performance improvement of ~1771x (0.13ms vs 225ms). 

At the full set, the improvement is less stellar, but still significant:

```python
In [87]: %timeit list(map(lambda x: model.user2index.get(x, np.NaN), test[model.col_user].unique()))
294 ms ± 7.47 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

In our use case, this scenario rarely occurs.

### Other Comments
Series.map() is also used in other parts of the code and should probably be improved as well:

https://github.com/microsoft/recommenders/blob/9b6c065a77c07a60947e894a6b516be5cef14ca1/reco_utils/recommender/sar/sar_singlenode.py#L234-L235

https://github.com/microsoft/recommenders/blob/9b6c065a77c07a60947e894a6b516be5cef14ca1/reco_utils/recommender/sar/sar_singlenode.py#L370

https://github.com/microsoft/recommenders/blob/9b6c065a77c07a60947e894a6b516be5cef14ca1/reco_utils/recommender/sar/sar_singlenode.py#L382

https://github.com/microsoft/recommenders/blob/9b6c065a77c07a60947e894a6b516be5cef14ca1/reco_utils/recommender/sar/sar_singlenode.py#L462

https://github.com/microsoft/recommenders/blob/9b6c065a77c07a60947e894a6b516be5cef14ca1/reco_utils/recommender/sar/sar_singlenode.py#L465

Any thoughts on this improvement? I'll submit a PR if no comments on these initial findings.

**Comment by miguelgfierro** [comment]
hey @zegerius, this is really great, thanks for the heads up. Would you like to go ahead and do a PR with these changes?
