### ISSUE TITLE
[ASK] Colab crash when using bigger dataset

### ISSUE THREAD

**Issue by TheAnswer96** [microsoft/recommenders#1029]
### Description
When I use dataset with about 400k split in 6k items and 300k users, colab crash during NCFDataset is running. Instead when I use a little slice of dataset with about 700 items and 800 users and a total of 1300 rows in the csv file it works. 

Does anyone know how to fix this?
Do you think this is a google colab related issue?
Thank you very much for your help.
Have a nice day.

**Comment by yueguoguo** [comment]
Not sure if it is related to the underlying machine you are using. Try scaling up memory, number of CPU cores, etc.

**Comment by miguelgfierro** [comment]
if you have a memory problem, here we have a tool to check the memory on a notebook: https://github.com/microsoft/recommenders/blob/master/reco_utils/common/notebook_memory_management.py also here you have some code to check gpu memory: https://github.com/miguelgfierro/pybase/blob/master/system/memory.py

**Comment by gramhagen** [comment]
I'm going to close this for now, let us know if you discover memory issues within the algorithm that need to be addressed, my assumption at this point is the colab notebook does not have enough memory for the algorithm / dataset in use.
