### ISSUE TITLE
[BUG] The link to deep dive notebook is broken in 00_quick_start/sar_movielens.ipynb

### ISSUE THREAD

**Issue by simonzhaoms** [microsoft/recommenders#1032]
### Description

All the links to `deep dive notebook` in [00_quick_start/sar_movielens.ipynb](https://github.com/microsoft/recommenders/blob/staging/notebooks/00_quick_start/sar_movielens.ipynb) are broken.

### Expected behavior (i.e. solution)

It should be `../02_model/sar_deep_dive.ipynb`.

**Comment by yueguoguo** [comment]
Good catch - can you create a PR for this?

**Comment by simonzhaoms** [comment]
It should be the rendering problem of nbviewer, which is fixed now.
