### ISSUE TITLE
[BUG] The link to Recommenders/reco_utils/recommender/sar/sar_singlenode.py is broken in notebooks/02_model/sar_deep_dive.ipynb

### ISSUE THREAD

**Issue by simonzhaoms** [microsoft/recommenders#1033]
### Description

The link to `Recommenders/reco_utils/recommender/sar/sar_singlenode.py` is not available in [`notebooks/02_model/sar_deep_dive.ipynb`](https://github.com/microsoft/recommenders/blob/master/notebooks/02_model/sar_deep_dive.ipynb).

### Expected behavior (i.e. solution)

It should be `../../reco_utils/recommender/sar/sar_singlenode.py`.

**Comment by yueguoguo** [comment]
Good catch - maybe create a PR directly to fix the issue

**Comment by simonzhaoms** [comment]
It should be the rendering problem of nbviewer, which is fixed now.
