### ISSUE TITLE
[ASK] Azure Machine Learning Designer Modules - port of Matchbox Recommender

### ISSUE THREAD

**Issue by atimesastudios** [microsoft/recommenders#1037]
### Description
Are there plans to make the Matchbox Recommender from Azure Machine Learning Studio available in Azure Machine Learning Designer? What is the closest recommendation algorithm to Matchbox? Is there any documentation on how I can create my own Azure Machine Learning Designer module? I see that @miguel-ferreira created a branch in #1036 which prompts these questions.

**Comment by miguelgfierro** [comment]
What I have done in https://github.com/microsoft/recommenders/pull/1060 is to show an example of Recommenders integration with the new AzureML Designer.

One problem of the Matchbox recommender was that it wasn't very scalable. I might suggest to try  this one instead: https://github.com/microsoft/recommenders/blob/master/notebooks/02_model/fm_deep_dive.ipynb

**Comment by anargyri** [comment]
Matchbox is a type of matrix factorization algorithm, based on this paper: http://www2009.eprints.org/12/1/p111.pdf

**Comment by anargyri** [comment]
There is also an .NET implementation here https://dotnet.github.io/infer/userguide/Learners/Matchbox%20recommender.html
