### ISSUE TITLE
Does the team have any advice on online evaluation?[ASK] 

### ISSUE THREAD

**Issue by Italosayan** [microsoft/recommenders#1048]
### Description
Which metrics to use during an A/B Test of a recommendation system? Examples in e commerce would be awesome. I found this windows presentation that has awesome information. Do you have more examples like the bing one?

https://medium.com/@somit_gupta/evaluation-of-online-controlled-experiments-20d79e2f898d

https://dl.acm.org/doi/10.1145/2365952.2366014
https://dl.acm.org/doi/10.1145/2764468.2764488

Thanks!!

**Comment by yueguoguo** [comment]
Thanks @Italosayan for sharing this. Online evaluation is definitely one of our utmost interests, but unfortunately so far we have not done much in the repo to support it. Will consider it in the near future.
