### ISSUE TITLE
[BUG] Maven coordinate of microsoft:sarplus:0.2.6 is not found

### ISSUE THREAD

**Issue by yueguoguo** [microsoft/recommenders#1049]
### Description
The maven coordinate of microsoft:sarplus:0.2.6 cannot be found.

### In which platform does it happen?
Azure Databricks

### How do we replicate the issue?
Follow the instructions of cluster set up on Azure Databricks [here](https://github.com/microsoft/recommenders/tree/master/contrib/sarplus) failed because the maven cannot be found, which in turn, resulted in an installation failure.

**Comment by yueguoguo** [comment]
@eisber FYI

**Comment by eisber** [comment]
can you try eisber:sarplus:0.2.6 ?

**Comment by yueguoguo** [comment]
@eisber esiber:sarplus:0.2.6 works well - so probably we just need to update the instruction or publicize a replicate of the original maven.
