### ISSUE TITLE
Multilabel classification with auc/logloss metric in python_evaluation [ASK] 

### ISSUE THREAD

**Issue by kartikey-singh** [microsoft/recommenders#1053]
I want to ask the team that when using `auc` function it calls `roc_auc_score`, but in a movielens type dataset where ratings are multi-label (1-5) which is the usual case. 

We need to add `labels` argument to it for it to work otherwise it throws `ValueError: multi_class must be in ('ovo', 'ovr')`.

As the `roc_auc_score` function by default work for binary data.

What are the suggestions for it? Also, the same argument applies to `logloss` function.

If I am wrong please correct me.

**Comment by miguelgfierro** [comment]
AUC and logloss can be used in general in multilabel, but we mostly use it for measuring binary classification. AUC is a weighted average between precision and recall and logloss gives you a sense of how wrong you are, penalising heavily results that are far from the correct ones. 
If you want to do multilabel metrics, I would recommend to use the regression metrics we have in the repo https://github.com/microsoft/recommenders/blob/master/reco_utils/evaluation/python_evaluation.py#L126, like rmse, mae, exp_variance and r2

**Comment by kartikey-singh** [comment]
Thanks for the reply, but now both `logloss` and `roc_auc_score` support `multi_class` classification,
[https://scikit-learn.org/stable/modules/generated/sklearn.metrics.roc_auc_score.html](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.roc_auc_score.html) .
Maybe it can be added as an enhancement, otherwise no problem.
