### ISSUE TITLE
[BUG] Running recommend_top_k_items() on SarPlus causes all the files in the cache path to be deleted

### ISSUE THREAD

**Issue by mmahathi666** [microsoft/recommenders#1054]
### Description
When running recommend_top_k_items() the SARPlus algorithm causes all the files in the cache path to be cleared. This is not expected and if needed, it should clean up any existing *.sar files from the path. Using this unknowningly on a folder can caus accidental data loss.

### In which platform does it happen?

All platforms

### How do we replicate the issue?
Run model.recommend_k_items(cust_df, top_k=10, remove_seen=False, cache_path='/mnt/cache/')
### Expected behavior (i.e. solution)
This should cause the cache to be built and no files to be deleted in the cache other than the *.sar files

**Comment by yueguoguo** [comment]
@eisber can you help take a look at this? Maybe we want to schedule a meeting for discussing this.

**Comment by eisber** [comment]
I think this originates from this line: https://github.com/eisber/sarplus/blob/master/python/pysarplus/SARPlus.py#L264

am not sure how to deal with it as clearing it out manually can be a pain (e.g. hdfs), one could potentially expose a parameter (overwrite = true, for the cache?)
