### ISSUE TITLE
[ASK] Is there a Chinese version of this project? If not, Can we build translation project?

### ISSUE THREAD

**Issue by linhongzhao321** [microsoft/recommenders#1056]
### Description
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;I learned and practiced some parts of this project，I have to say this project is very good！！！Next！I want to share this project with more Chinese developers who not good English。Before that, I would like to confirm the question as stated in the title。

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Is there a Chinese version of this project? If not, Can we build translation project in GitHub facilitate for Chinese Developers participate in the project or learn。

Would you happen to have a suggestion？

### 描述
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;这个项目我认为非常好！尤其是对新手而言。因此，我希望将这个项目汉化，从而分享给更多英文不好的中国开发者。但是，我希望先确认后文所述问题。

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;这个项目是否存在中文项目？如果没有，我们是否可以自行创建该项目的汉化版本。便于更多的中国开发者学习或使他们参与进来。

或者，贵方有任何其他的建议吗？

**Comment by miguelgfierro** [comment]
Hi, at the moment we don't plan to translate the repo to other languages, unfortunately we don't have the bandwidth. If you want, you can create a fork and do the translation there.
