### ISSUE TITLE
where could I get the 'reco_utils' that imported in the code?

### ISSUE THREAD

**Issue by maverick0220** [microsoft/recommenders#1065]
### Description

I tried pip3 on both linux and macOS, but none of them found such a distribution.

**Comment by gramhagen** [comment]
We put some instructions here. Let me know if they're not clear and we can update.
https://github.com/microsoft/recommenders/blob/master/SETUP.md#install-the-utilities-via-pip

**Comment by maverick0220** [comment]
Thanks for your guide, truly helped. For beginners like me it's a little hard to understand in the first place.

**Comment by gramhagen** [comment]
Great. Glad it helped. I'll close this issue then
