### ISSUE TITLE
[ASK] stand alone use xDeepFM.py

### ISSUE THREAD

**Issue by Sandy4321** [microsoft/recommenders#1072]
great code 
https://github.com/microsoft/recommenders/blob/master/notebooks/00_quick_start/xdeepfm_criteo.ipynb
thanks

only several questions
1
how to download data manually ?
2
will work 
\reco_utils\recommender\deeprec\models\xDeepFM.py
stand alone?

**Comment by yueguoguo** [comment]
Hi @Sandy4321 regarding your question

> how to download data manually ?
The data is a processed version of the original criteo dataset, you can download it from our blob storage by using 
```
if not os.path.exists(yaml_file):
    download_deeprec_resources(r'https://recodatasets.blob.core.windows.net/deeprec/', data_path, 'xdeepfmresources.zip')
```

> will work `\reco_utils\recommender\deeprec\models\xDeepFM.py` stand alone?

Not sure if I understand correctly, you mean running the `py` script alone? Then it is not probably how it is supposed to be used. You can the modules in the script in your own codes.

**Comment by Sandy4321** [comment]
great thanks
1
Not sure if I understand correctly, you mean running the py script alone? Then it is not probably how it is supposed to be used. You can the modules in the script in your own codes
so how install your modules on winodws?
2 
only I try to download manually by link you sent me 
https://recodatasets.blob.core.windows.net/deeprec
but get error
<Error>
<script/>
<Code>ResourceNotFound</Code>
<Message>
The specified resource does not exist. RequestId:f3cb8e00-301e-00b0-1286-0378da000000 Time:2020-03-26T15:49:47.9129625Z
</Message>
</Error>
![image](https://user-images.githubusercontent.com/11426119/77666957-016dce00-6f58-11ea-9105-2f574fa326e8.png)

**Comment by Sandy4321** [comment]
ok
I used this link
https://recodatasets.blob.core.windows.net/deeprec/http:/xdeepfmresources.zip/
I got data, thanks
but it looks very strange, what preprocessing you used?
0 16:372270:1 11:1561051:1 24:199173:1 3:1750186:1 26:2073461:1 12:1864800:1 17:150363:1 18:1283644:1 28:164307:1 27:1262273:1 19:1349205:1 7:1928194:1 39:795398:1 9:161196:1 32:1480661:1 30:180793:1 10:267940:1 1:1533602:1 21:1829128:1 20:602253:1 22:1113685:1 8:587827:1 29:1978347:1 4:1007621:1 35:635625:1 14:1712964:1 36:505691:1 2:1767161:1 25:94115:1 37:1331841:1 5:1140056:1 15:1080229:1 38:1372774:1 23:1055765:1 34:265347:1 31:980768:1 33:1483574:1 13:108951:1 6:904241:1
0 16:206299:1 11:1321335:1 24:1294289:1 3:1143985:1 26:284465:1 12:1864800:1 17:5388:1 18:1283644:1 28:431967:1 27:1127274:1 19:1466976:1 7:1460783:1 39:159044:1 9:1002004:1 32:1782349:1 30:197371:1 10:994317:1 1:1833823:1 21:1829128:1 20:451516:1 22:1113685:1 8:15274:1 29:2033901:1 4:1492998:1 35:635625:1 14:1712964:1 36:1262749:1 2:980850:1 25:1129080:1 37:1331841:1 5:58691:1 15:1795899:1 38:1372774:1 23:1985353:1 34:89063:1 31:930902:1 33:1321102:1 13:1283437:1 6:1779735:1
0 16:19531:1 11:713045:1 24:275840:1 3:1334725:1 26:428881:1 12:1864800:1 17:1235068:1 18:1283644:1 28:778507:1 27:1127274:1 19:1466976:1 7:102193:1 39:1883090:1 9:205898:1 32:909577:1 30:1937997:1 10:267940:1 1:1533602:1 21:1829128:1 20:1018441:1 22:1113685:1 8:747056:1 29:1086830:1 4:1416925:1 35:635625:1 14:1375997:1 36:651191:1 2:312642:1 25:975049:1 37:1516558:1 5:1476119:1 15:1532931:1 38:1977730:1 23:1291871:1 34:587981:1 31:719937:1 33:827266:1 13:270474:1 6:1973672:1
0 16:372270:1 11:1564212:1 24:203743:1 3:1601537:1 26:983192:1 12:366104:1 17:681405:1 18:661814:1 28:223281:1 27:1262273:1 19:1349205:1 7:1331188:1 39:1883090:1 9:807801:1 32:909577:1 30:189455:1 10:569158:1 1:269577:1 21:1153389:1 20:1710513:1 22:1113685:1 8:2025076:1 29:1839680:1 4:1204251:1 35:450135:1 14:161623:1 36:1336068:1 2:1767161:1 25:94115:1 37:422163:1 5:793756:1 15:1503172:1 38:1977730:1 23:2022990:1 34:1085398:1 31:1983766:1 33:827266:1 13:1501158:1 6:317821:1
0 16:506656:1 11:713045:1 24:814823:1 3:539832:1 26:1225306:1 12:1864800:1 17:1415282:1 18:683546:1 28:2079182:1 27:916634:1 19:1446727:1 7:102193:1 39:489663:1 9:561877:1 32:1105545:1 30:197371:1 10:267940:1 1:1533602:1 21:1829128:1 20:647998:1 22:1113685:1 8:15274:1 29:55721:1 4:1204251:1 35:635625:1 14:1712964:1 36:1262749:1 2:1259342:1 25:1675484:1 37:331975:1 5:809568:1 15:1879401:1 38:1825251:1 23:474683:1 34:536153:1 31:1171573:1 33:1321102:1 13:693903:1 6:1973672:1
1 16:820806:1 11:1321335:1 24:814823:1 3:1143985:1 26:1225306:1 12:366104:1 17:1522782:1 18:1283644:1 28:301750:1 27:1262273:1 19:1829576:1 7:1301050:1 39:479253:1 9:907722:1 32:985923:1 30:197371:1 10:64005:1 1:1798450:1 21:1581115:1 20:647998:1 22:1113685:1 8:1415848:1 29:1400119:1 4:1584723:1 35:635625:1 14:1712964:1 36:1262749:1 2:434323:1 25:1198882:1 37:440530:1 5:137250:1 15:1879401:1 38:1372774:1 23:776514:1 34:1441469:1 31:519812:1 33:1483574:1 13:108951:1 6:1032437:1
1 16:1518012:1 11:1561051:1 24:1249867:1 3:1080822:1 26:744009:1 12:1864800:1 17:402282:1 18:1283644:1 28:1221122:1 27:1087371:1 19:491224:1 7:1928194:1 39:1883090:1 9:1798653:1 32:909577:1 30:197371:1 10:569158:1 1:269577:1 21:1829128:1 20:229274:1 22:1113685:1 8:1904207:1 29:1030916:1 4:1204251:1 35:635625:1 14:1712964:1 36:1262749:1 2:1297776:1 25:1981464:1 37:166404:1 5:683078:1 15:253837:1 38:1977730:1 23:1291871:1 34:1118321:1 31:250193:1 33:827266:1 13:693903:1 6:1232892:1
0 16:257573:1 11:713045:1 24:1602971:1 3:539832:1 26:862819:1 12:366104:1 17:422014:1 18:1283644:1 28:1996244:1 27:1262273:1 19:1466976:1 7:1054000:1 39:1883090:1 9:1735918:1 32:909577:1 30:197371:1 10:267940:1 1:1533602:1 21:1829128:1 20:1395711:1 22:1113685:1 8:15274:1 29:1497004:1 4:1510980:1 35:635625:1 14:1806297:1 36:651191:1 2:1883037:1 25:1721353:1 37:509320:1 5:342726:1 15:1716997:1 38:1977730:1 23:1956500:1 34:1510585:1 31:2041349:1 33:827266:1 13:1318464:1 6:936629:1
1

**Comment by Sandy4321** [comment]
https://recodatasets.blob.core.windows.net/deeprec/xdeepfmresources.zip
this link works

**Comment by yueguoguo** [comment]
I will close the issue unless there is anything else.
