### ISSUE TITLE
[BUG] The formula to generate decayed rating in data_transform module has a bug?

### ISSUE THREAD

**Issue by darshats** [microsoft/recommenders#1073]
### Description

The formula for decay of rating appears incorrect:
lambda x: x['Weight'] * math.exp(-math.log2((t_ref - pd.to_datetime(x['Timestamp'])).days / T))

It should be:
lambda x: x['Weight'] * math.exp(-((t_ref - pd.to_datetime(x['Timestamp'])).days / T)*math.log2)
### In which platform does it happen?

All platforms

**Comment by gramhagen** [comment]
Closed by #1074 thanks for raising the issue @darshats
