### ISSUE TITLE
Remote pip install of reco_utils fails

### ISSUE THREAD

**Issue by gramhagen** [microsoft/recommenders#1082]
When this repo is used as a dependency in a setup.py (as shown below)
```
    install_requires = [
        'reco_utils@git+https://github.com/microsoft/recommenders/@master#egg=pkg'
    ],
```

The package pulls the $NAME environment flag which is the hostname in most linux environments, this will result in a mismatch between the expected name reco_utils and the installed package name causing pip to fail.

We should remove this line if possible
https://github.com/microsoft/recommenders/blob/75139859cf2aaf2c121c4b3953e7d59f057ba991/setup.py#L19

@miguelgfierro I think this was added to support ADO. Do you know why it's necessary?

**Comment by miguelgfierro** [comment]
aahhh good catch, I can change it
