### ISSUE TITLE
[BUG] dkn model in quick-start tutorial

### ISSUE THREAD

**Issue by zzh-ecnu** [microsoft/recommenders#1084]
### Description
performing↓
model = DKN(hparams, input_creator)
print(model.run_eval(valid_file))

then bug happened：could not create a concat primitive descriptor, in file tensorflow/core/kernels/mkl_concat_op.cc:811

### Dependencies Info.
Platform：Ubuntu 18.04
Setting up：follow the reco_base.yaml

### 
help! thanks very much!

**Comment by zzh-ecnu** [comment]
This bug has been solved.

Follow the reco_base.yaml, you will install tensorflow version==1.12.0, this version is too high for dkn model to run. So I try tensorflow which version==1.8.0, and that make sense!

So if you meet the problem about mkl lib, you can try to adjust the version of tensorflow.

**Comment by gramhagen** [comment]
Thanks @zzh-ecnu! I'm going to keep this open so we can adjust dkn or the version in the conda yaml generator.

**Comment by danyang-liu** [comment]
we test tensorflow==1.15.2 on both GPU and CPU, it's ok.
https://github.com/microsoft/recommenders/pull/1129
