### ISSUE TITLE
[FEATURE] Adding TF-IDF recommender using COVID-19 dataset

### ISSUE THREAD

**Issue by niwilso** [microsoft/recommenders#1087]
### Description
I am planning on contributing a simple TF-IDF recommender using the [Azure Open Research dataset on COVID-19](https://azure.microsoft.com/en-us/services/open-datasets/catalog/covid-19-open-research/) in the form of a quick start notebook and a deep dive notebook (with the appropriate util scripts and unit tests).

### Expected behavior with the suggested feature
Content-based recommendation with TF-IDF is a great starting point for content-rich scenarios.

### Other Comments
I feel this simple implementation could serve as a useful starting point for those looking to get started with something simple. In addition, the use of this new dataset may be more interesting than the MovieLens dataset for some readers.

**Comment by yueguoguo** [comment]
This is really awesome. Looking forward to the addition of the algorithm.

**Comment by niwilso** [comment]
The PR (https://github.com/microsoft/recommenders/pull/1088) has been approved and merged into the staging branch.

Note that there is no deep dive notebook yet. I hope to contribute that in a future PR.
