### ISSUE TITLE
[BUG] Memory limit exceeded

### ISSUE THREAD

**Issue by zerolxf** [microsoft/recommenders#1103]
### Description
 the program memory is very large when I load data. The program needs to be optimized

dataset.py in [155 line](https://github.com/microsoft/recommenders/blob/master/reco_utils/recommender/ncf/dataset.py#L155) 

### In which platform does it happen?
centos, docker.

### How do we replicate the issue?
When you load a large data set, the program memory will be very large, and it is obvious that the code can be optimized. （dataset: 100K userID, 50K itemID）

### Expected behavior (i.e. solution)

the program memory will be very large.

### Other Comments
Negative sampling only during training

**Comment by miguelgfierro** [comment]
hi @zerolxf, thanks for your comment, we will add this to our TODO list. In the meantime, if you see a fix, feel free to send a PR with an optimization
