### ISSUE TITLE
[ASK] Could it be possible to remove the upper limitation for pandas version

### ISSUE THREAD

**Issue by simonzhaoms** [microsoft/recommenders#1106]
### Description

In [scripts/generate_conda_file.py](https://github.com/microsoft/recommenders/blob/master/scripts/generate_conda_file.py#L48), the version of pandas is limited `"pandas": "pandas>=0.23.4,<1.0.0"`.  Could it be possible to remove this limitation?

https://github.com/microsoft/recommenders/blob/master/scripts/generate_conda_file.py#L48, 

### Other Comments

BTW, any best practice for tracking the source of dependency's version requirements?

**Comment by miguelgfierro** [comment]
pandas > 1 has a number of issues: https://github.com/microsoft/recommenders/pull/1052, maybe when the library is more mature we can remove the limitation
