### ISSUE TITLE
[FEATURE] Add NextItNet into sequential algorithms

### ISSUE THREAD

**Issue by Haoxuan-Wu** [microsoft/recommenders#1122]
### Description
Add NextItNet sequential recommender algorithm into sequential algorithms.

NextItNet: Yuan, F., Karatzoglou, A., Arapakis, I., Jose, J. M., & He, X. (2019). A Simple Convolutional Generative Network for Next Item Recommendation. web search and data mining.

### Expected behavior with the suggested feature
A simple and effective algorithm

**Comment by miguelgfierro** [comment]
https://github.com/microsoft/recommenders/pull/1126
