### ISSUE TITLE
[ASK] NPA word embedding mapping relation missing

### ISSUE THREAD

**Issue by zzh-ecnu** [microsoft/recommenders#1134]
### Description

In NPA.zip, there is a file called embedding.npy. However, it doesn't record the mapping relation bewteen word and index of word vector. For example, when "hello" appeared in a sentence, how can I decide related index of word vector which is then used for searching in embedding.npy?
### Other Comments
Please, thanks very much!

**Comment by gramhagen** [comment]
@yjw1029 can you provide some information on the words that map to the embedding matrix in npa.zip?

**Comment by zzh-ecnu** [comment]
Sure~

This is an example before word embedding: 
                             CandidateNews0:18707,23848,13490,10948,21385,11606,1251,16591,827,28081

However, this format has been transformed from word to index(say the first index 18707), the problem is i don't know the mapping relation which word is related to 18707.

**Comment by yjw1029** [comment]
The dataset is a synthetic dataset, which may have some privacy issue if we public the word mapping.

**Comment by gramhagen** [comment]
I see. Ok. I will close this issue then.
