### ISSUE TITLE
[BUG] LSTUR and NRMS in News Rec Module

### ISSUE THREAD

**Issue by yjw1029** [microsoft/recommenders#1136]
### Description
* Attention layer in LSTUR doesn't mask padding which will effect model performance
* Can't save NRMS model

### How do we replicate the issue?

* Create a conda environment for gpu 
* run example/00_quick_start/nrms_synthetic.ipynb
* run cell "model.model.save_model(path)"
* run example/00_quick_start/lstur_synthetic.ipynb

### Expected behavior (i.e. solution)
* change get_config method of SelfAttention layer in reco_utils/recommender/newsrec/layers.py.
* add masking attention weight in AttLayer2 layer.

**Comment by amelieyu1989** [comment]
same problem that could not save model in : reco_utils/recommender/newsrec/models/base_model.py
is it resolved please?
