### ISSUE TITLE
[BUG] cmake needs to be installed 

### ISSUE THREAD

**Issue by wutaomsft** [microsoft/recommenders#1143]
### Description

If cmake is not installed, conda env create -f reco_base.yaml will fail.

**Comment by gramhagen** [comment]
CMake is required by XLearn as noted here: https://github.com/microsoft/recommenders/blob/master/SETUP.md#dependencies-setup
This will make it a bit more difficult for windows installation, but should still be possible.

While you can install cmake through conda it doesn't seem to include or always pick up the c / c++ compilers needed, so installing cmake at the os level is probably the simplest.

I'm checking with @yueguoguo in #1121 if using `apt-get install -y build-essential cmake` is sufficient or if we need to pull from source to build cmake. Depending on that we can update the instructions to make it a bit easier for linux.
