### ISSUE TITLE
[ASK]  how to create 3 files embedding.npy, uid2index.pkl and word_dict.pkl in notebook

### ISSUE THREAD

**Issue by phmhonganh** [microsoft/recommenders#1182]
### Other Comments
I wanna ask how to create 3 files embedding.npy, uid2index.pkl and word_dict.pkl in notebook https://github.com/microsoft/recommenders/blob/master/examples/00_quick_start/nrms_MIND.ipynb

**Comment by miguelgfierro** [comment]
this might help https://github.com/microsoft/recommenders/blob/master/examples/02_model_content_based_filtering/dkn_deep_dive.ipynb

**Comment by miguelgfierro** [comment]
closing this, feel free to reopen in case it is needed

**Comment by bestpredicts** [comment]
so

> this might help https://github.com/microsoft/recommenders/blob/master/examples/02_model_content_based_filtering/dkn_deep_dive.ipynb

the code does not generate  files embedding.npy, uid2index.pkl and word_dict.pkl , can u provide the code  how to generate these files?
