### ISSUE TITLE
[BUG] SAR Deep Dive link is not working

### ISSUE THREAD

**Issue by lucazav** [microsoft/recommenders#1198]
The SAR Deep Dive notebook link into [this page](https://github.com/microsoft/recommenders/blob/master/examples/00_quick_start/sar_movielens_with_azureml.ipynb) is not working. It seems the right link is the following one:

https://github.com/microsoft/recommenders/blob/master/examples/02_model_collaborative_filtering/sar_deep_dive.ipynb

**Comment by wutaomsft** [comment]
Thanks for reporting.  Fixed in https://github.com/microsoft/recommenders/pull/1213
