### ISSUE TITLE
SAR: make sure cold users filter in SAR pySpark implementation works properly

### ISSUE THREAD

**Issue by maxkazmsft** [Microsoft/Recommenders#121]
For a large number of users (>500,000), SAR pySpark recommend_k_items method thinks that there are cold users in the test set but there are actually only warm users there. This is not reproducible on non-customer data though, related to #88

**Comment by miguelgfierro** [comment]
closing this for now, please feel free to reopen if needed

@gramhagen if you think you will need this, feel free to reopen
