### ISSUE TITLE
[ASK] 

### ISSUE THREAD

**Issue by euphoria911** [microsoft/recommenders#1210]
### NPA metrics

Hello! I am testing NAML, NRMS and NPA algorithms for MIND-dataset. I noticed that the metric HIT@1,5,10 has a non-zero value for the first two algorithms, but for NPA it is zero. Can someone explain why this is so? thnx

**Comment by miguelgfierro** [comment]
FYI @Leavingseason

**Comment by wutaomsft** [comment]
@yjw1029 can you help? thanks!

**Comment by euphoria911** [comment]
OK, I figured it out. For some reason true labels are formed in the float type. So inside the body of the hit-function np.where (y_true == 1) is not executed. 
AND I would like to draw your attention to the if-function is implemented inside the functions for calculating hit and ndcg. It will not work correctly if the user wants to get the ndcg@5 metric, for example.
