### ISSUE TITLE
[BUG] AttributeError: 'HParams' object has no attribute 'use_entity'

### ISSUE THREAD

**Issue by shainaraza** [microsoft/recommenders#1217]
I am using DKN_mind and repeatedly getting this error
![image](https://user-images.githubusercontent.com/32249936/96468854-91c47680-11fa-11eb-8188-d121c9b41999.png)

any suggestions?

**Comment by miguelgfierro** [comment]
the latest code should work correctly https://github.com/microsoft/recommenders/blob/master/reco_utils/recommender/deeprec/deeprec_utils.py#L161
