### ISSUE TITLE
[ASK] Where to download mind test set with label?

### ISSUE THREAD

**Issue by Faysir** [microsoft/recommenders#1219]
### Description
    Since the MIND 2020 competition successfully closed, where can I download the test set with label?
    I want to make some research on news recommendation, and I start up with the framework of Microsoft News Recommendation(https://github.com/microsoft/recommenders), but when I need to evaluate my algorithm, I found the test dataset download from https://msnews.github.io/ don't have labels.
    Now I have submitted the result of the test set to Mind competition page, and I got the valid and test result successfully. But it's too slow, the whole process (includes predict, submit, evaluate) cost about more than 1 hour. Can I download the test set which has label inside and make local evaluate?

**Comment by Mind-Hand** [comment]
the same to me. i just let the large-dev as my test set

**Comment by Faysir** [comment]
> the same to me. i just let the large-dev as my test set 

yeah, me too, use large-dev for valid first, and upload test result upon mind official website for final evaluation
