### ISSUE TITLE
[FEATURE] Efficiency enhancement in surprise_utils.py

### ISSUE THREAD

**Issue by zhaisw** [microsoft/recommenders#1222]
### Description
In `recommenders/reco_utils/recommender/surprise/surprise_utils.py  compute_ranking_predictions` function, the code will try to get unique items or users in every for-loop step, which will decrease the efficiency.

### Expected behavior with the suggested feature
Better to use memory to improve code efficiency,
```python
users = data[usercol].unique()
items = data[itemcol].unique()
for user in users:
        for item in items:
...
```

**Comment by miguelgfierro** [comment]
this is really nice, do you want to do a PR?

**Comment by zhaisw** [comment]
> this is really nice, do you want to do a PR?

Yes! For sure, I would like to do that. Thanks.

**Comment by miguelgfierro** [comment]
thanks for the contribution @zhaisw!
https://github.com/microsoft/recommenders/pull/1224
