### ISSUE TITLE
Data format in SLi_Rec notebook [ASK] 

### ISSUE THREAD

**Issue by LeDuySon** [microsoft/recommenders#1223]
### Description

I want to train sli_rec with my own dataset. I try to format my dataset as the notebook show, but when  run_eval with my valid or test set i have this error ValueError: Only one class present in y_true. ROC AUC score is not defined in that case.
My dataset format:

![Screenshot from 2020-10-28 16-32-07](https://user-images.githubusercontent.com/33374938/97418232-289bdc00-193b-11eb-9b55-785182ed9ed4.png)

Can someone help me !

**Comment by tongxinz** [comment]
I've got a similar issue... Did you resolve the problem?

**Comment by doudouaili** [comment]
Hi, Have you solved it?

**Comment by LeDuySon** [comment]
Yes, i had to catch error for the line its calculate roc score, because its
not work when u have only 1 class so just catch error and set roc score to
zero

Vào 13:59, Th 3, 31 thg 8, 2021 阿狸先生 ***@***.***> đã viết:
