### ISSUE TITLE
[BUG] smoke test creates folders in rootdir that should have been temporary

### ISSUE THREAD

**Issue by wutaomsft** [microsoft/recommenders#1237]
### Description

When running test_extract_mind(size,tmp) in tests/smoke/test_mind.py, it creates MINDxxx_train.zip folder that are removed after tests.  (xxx is either demo or small).

I would expect folder would be created in /tmp and would be deleted after the test.

### In which platform does it happen?

All Linux platforms.
### How do we replicate the issue?

(reco_base) azureuser@dsvmd16:~/src/recommenders$ pytest tests/smoke -m "smoke and not spark and not gpu" --durations 0 -k "extract_mind"
======================================== test session starts ========================================
platform linux -- Python 3.6.11, pytest-6.1.2, py-1.9.0, pluggy-0.13.1
rootdir: /home/azureuser/src/recommenders, configfile: pytest.ini
plugins: xdist-2.1.0, forked-1.3.0
collected 45 items / 43 deselected / 2 selected                                                     

tests/smoke/test_mind.py ..                                                                   [100%]

========================================= warnings summary ==========================================
../../../../anaconda/envs/reco_base/lib/python3.6/site-packages/ansiwrap/core.py:6
  /anaconda/envs/reco_base/lib/python3.6/site-packages/ansiwrap/core.py:6: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp

../../../../anaconda/envs/reco_base/lib/python3.6/importlib/_bootstrap.py:219
  /anaconda/envs/reco_base/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216, got 192
    return f(*args, **kwds)

../../../../anaconda/envs/reco_base/lib/python3.6/importlib/_bootstrap.py:219
  /anaconda/envs/reco_base/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
    return f(*args, **kwds)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================================= slowest durations =========================================
7.39s call     tests/smoke/test_mind.py::test_extract_mind[small]
1.29s call     tests/smoke/test_mind.py::test_extract_mind[demo]

(4 durations < 0.005s hidden.  Use -vv to show these durations.)
=========================== 2 passed, 43 deselected, 3 warnings in 10.95s ===========================
(reco_base) azureuser@dsvmd16:~/src/recommenders$ ls -lt
total 2108
drwxrwxr-x  4 azureuser azureuser    4096 Nov  8 15:55 MINDsmall_train.zip
drwxrwxr-x  4 azureuser azureuser    4096 Nov  8 15:55 MINDdemo_train.zip
-rw-rw-r--  1 azureuser azureuser   30304 Nov  8 15:25 output.ipynb
-rw-rw-r--  1 azureuser azureuser    1274 Nov  8 14:49 reco_base.yaml
-rw-rw-r--  1 azureuser azureuser     284 Nov  8 14:42 pytest.ini
-rw-rw-r--  1 azureuser azureuser    4517 Nov  8 13:18 AUTHORS.md
-rw-rw-r--  1 azureuser azureuser   19637 Nov  8 13:18 README.md
-rw-rw-r--  1 azureuser azureuser   18380 Nov  8 13:18 SETUP.md
drwxrwxr-x  3 azureuser azureuser    4096 Nov  1 22:47 demo
drwxrwxr-x  7 azureuser azureuser    4096 Nov  1 19:10 tests
drwxrwxr-x  4 azureuser azureuser    4096 Oct 31 21:56 lightgbm_criteo.mml
drwxrwxr-x  4 azureuser azureuser    4096 Oct 31 20:06 tools
-rw-rw-r--  1 azureuser azureuser 1979173 Oct 31 20:02 ml-100k.data
drwxrwxr-x  9 azureuser azureuser    4096 Oct 31 20:01 reco_utils
-rw-rw-r--  1 azureuser azureuser    1352 Oct 31 19:52 reco_pyspark.yaml
drwxrwxr-x  8 azureuser azureuser    4096 Oct 31 19:49 scenarios
-rw-rw-r--  1 azureuser azureuser    1556 Oct 31 19:49 setup.py
drwxrwxr-x 12 azureuser azureuser    4096 Oct 31 19:49 examples
drwxrwxr-x  3 azureuser azureuser    4096 Oct 31 19:49 docs
-rw-rw-r--  1 azureuser azureuser    4583 Oct 31 19:49 CONTRIBUTING.md
-rw-rw-r--  1 azureuser azureuser    7732 Oct 31 19:49 GLOSSARY.md
-rw-rw-r--  1 azureuser azureuser    1162 Oct 31 19:49 LICENSE
-rw-rw-r--  1 azureuser azureuser    4316 Oct 31 19:49 NEWS.md
-rw-rw-r--  1 azureuser azureuser    2383 Oct 31 19:49 SECURITY.md
drwxrwxr-x  3 azureuser azureuser    4096 Oct 31 19:49 contrib

**Comment by miguelgfierro** [comment]
we are now using fixture `tmp` in the tests https://github.com/microsoft/recommenders/blob/main/tests/smoke/reco_utils/dataset/test_mind.py#L69 which is temporary: https://github.com/microsoft/recommenders/blob/main/tests/conftest.py#L52
