### ISSUE TITLE
[FEATURE] use pytest-xdist

### ISSUE THREAD

**Issue by miguelgfierro** [microsoft/recommenders#1250]
### Description

Not sure if we are using it already, but using pytest-xdist saves the notebooks unit tests by over 50% time on a 12-core machine: will give 8m while using xdist will give 3m 

on nc-12 (12 cores).  There are 1 or 2 notebooks dominating the tests, so you would get better results with larger sets of sets.

Sometimes there are dependencies between tests.  At that point you may want to use --dist=loadscope or --dist=loadfile option.

**Comment by miguelgfierro** [comment]
-  [x] pytest tests/unit -m "not notebooks and not spark and not gpu" --durations 0
-  [x] pytest tests/unit -m "notebooks and not spark and not gpu" --durations 0
-  [x] pytest tests/unit -m "not notebooks and not spark and gpu" --durations 0
-  [x] pytest tests/unit -m "notebooks and not spark and gpu" --durations 0
-  [x] pytest tests/unit -m "not notebooks and spark and not gpu" --durations 0
-  [x] pytest tests/unit -m "notebooks and spark and not gpu" --durations 0

Smoke:
-  [x] pytest tests/smoke -m "smoke and not spark and not gpu" --durations 0
-  [x] pytest tests/smoke -m "smoke and not spark and gpu" --durations 0
-  [x] pytest tests/smoke -m "smoke and spark and not gpu" --durations 0

Integration:
-  [x] pytest tests/integration -m "integration and not spark and not gpu" --durations 0
-  [x] pytest tests/integration -m "integration and not spark and gpu" --durations 0
-  [x] pytest tests/integration -m "integration and spark and not gpu" --durations 0

**Comment by miguelgfierro** [comment]
```
pytest tests/unit -m "not notebooks and not spark and not gpu" --durations 0 -s -n auto --dist=loadscope
```
new vs old: 9s vs 13s

**Comment by miguelgfierro** [comment]
```
pytest tests/smoke -m "smoke and not spark and not gpu" --durations 0 -s -n auto --dist=loadscope
```
new vs old: 12:51 vs

**Comment by miguelgfierro** [comment]
```
pytest tests/integration -m "integration and not spark and not gpu" --durations 0 --disable-warnings -s -n auto --dist=loadscope
```

**Comment by laserprec** [comment]
Thanks Miguel! This is definitely something we can employ on our new CI pipelines. I think this would make most sense on tests we run on the self-hosted VM with 12cores. The platform-hosted machines only have 2cores and I don't see we have significant gains.

**Comment by miguelgfierro** [comment]
Closing since there hasn't been interaction for a while
