### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Jazzssmine** [microsoft/recommenders#1290]
### Description
Unable to download yaml file

### In which platform does it happen?
I'm using jupyter notebook and try to download yaml file

if not os.path.exists(yaml_file):
    download_deeprec_resources(r'https://recodatasets.blob.core.windows.net/newsrec/', \
                               os.path.join(data_path, 'utils'), mind_utils)
There's a warning: 'File is not a zip file'.

**Comment by gramhagen** [comment]
File locations have changed, you can see updates in the staging branch examples: 

https://github.com/microsoft/recommenders/blob/staging/examples/00_quick_start/naml_MIND.ipynb

```
if not os.path.exists(yaml_file):
    download_deeprec_resources(r'https://recodatasets.z20.web.core.windows.net/newsrec/', \
                               os.path.join(data_path, 'utils'), mind_utils)
```

does this work for you?

**Comment by Jazzssmine** [comment]
It works now, thx!
