### ISSUE TITLE
[BUG] naml_MIND.ipynb in examples cannot run

### ISSUE THREAD

**Issue by liuchongming74** [microsoft/recommenders#1291]
### Description
I can not run NAML jupyter notebook in `recommenders/examples/00_quick_start/naml_MIND.ipynb`, when I came to this line: `print(model.run_eval(valid_news_file, valid_behaviors_file))`, 

and I got this, 
```
~/anaconda3/envs/xxx/lib/python3.7/site-packages/tensorflow_core/python/client/session.py in __call__(self, *args, **kwargs)
   1470         ret = tf_session.TF_SessionRunCallable(self._session._session,
   1471                                                self._handle, args,
-> 1472                                                run_metadata_ptr)
   1473         if run_metadata:
   1474           proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

https://github.com/microsoft/recommenders/issues/1291#issue-797394442
InvalidArgumentError: indices[3,0] = 17 is not in [0, 17)
	 [[{{node vert_encoder/embedding_1/embedding_lookup}}]]
```

It seems like provided embedding table and sample dimension is not matched.

I download `demo` data from https://recodatasets.blob.core.windows.net/newsrec/MINDdemo_train.zip, https://recodatasets.blob.core.windows.net/newsrec/MINDdemo_dev.zip, https://recodatasets.blob.core.windows.net/newsrec/MINDdemo_utils.zip.

### In which platform does it happen?
I am using TensorFlow-gpu 1.15.3, Ubuntu 18.04.

### How do we replicate the issue?
Just run `recommenders/examples/00_quick_start/naml_MIND.ipynb`.

### Expected behavior (i.e. solution)
Printing accuracy is expected.

**Comment by Xudongenen** [comment]
Me too

**Comment by svrijenhoek** [comment]
similar behavior when running npa_mind.ipynb

**Comment by Xudongenen** [comment]
> ### Description
> I can not run NAML jupyter notebook in `recommenders/examples/00_quick_start/naml_MIND.ipynb`, when I came to this line: `print(model.run_eval(valid_news_file, valid_behaviors_file))`,
> 
> and I got this,
> 
> ```
> ~/anaconda3/envs/xxx/lib/python3.7/site-packages/tensorflow_core/python/client/session.py in __call__(self, *args, **kwargs)
>    1470         ret = tf_session.TF_SessionRunCallable(self._session._session,
>    1471                                                self._handle, args,
> -> 1472                                                run_metadata_ptr)
>    1473         if run_metadata:
>    1474           proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)
> 
> https://github.com/microsoft/recommenders/issues/1291#issue-797394442
> InvalidArgumentError: indices[3,0] = 17 is not in [0, 17)
> 	 [[{{node vert_encoder/embedding_1/embedding_lookup}}]]
> ```
> 
> It seems like provided embedding table and sample dimension is not matched.
> 
> I download `demo` data from https://recodatasets.blob.core.windows.net/newsrec/MINDdemo_train.zip, https://recodatasets.blob.core.windows.net/newsrec/MINDdemo_dev.zip, https://recodatasets.blob.core.windows.net/newsrec/MINDdemo_utils.zip.
> 
> ### In which platform does it happen?
> I am using TensorFlow-gpu 1.15.3, Ubuntu 18.04.
> 
> ### How do we replicate the issue?
> Just run `recommenders/examples/00_quick_start/naml_MIND.ipynb`.
> 
> ### Expected behavior (i.e. solution)
> Printing accuracy is expected.
> 
> ### Other Comments

change vert_num in "naml.yaml" to 19

**Comment by lshowway** [comment]
@Xudongenen When I ran nrms_mind with large dataset, I can not get the results reported in the paper. I got 0.60, the reported is 0.67+

**Comment by miguelgfierro** [comment]
Closing since there hasn't been interaction for a while

**Comment by loiphan2000** [comment]
> > ### Description
> > I can not run NAML jupyter notebook in `recommenders/examples/00_quick_start/naml_MIND.ipynb`, when I came to this line: `print(model.run_eval(valid_news_file, valid_behaviors_file))`,
> > and I got this,
> > ```
> > ~/anaconda3/envs/xxx/lib/python3.7/site-packages/tensorflow_core/python/client/session.py in __call__(self, *args, **kwargs)
> >    1470         ret = tf_session.TF_SessionRunCallable(self._session._session,
> >    1471                                                self._handle, args,
> > -> 1472                                                run_metadata_ptr)
> >    1473         if run_metadata:
> >    1474           proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)
> > 
> > https://github.com/microsoft/recommenders/issues/1291#issue-797394442
> > InvalidArgumentError: indices[3,0] = 17 is not in [0, 17)
> > 	 [[{{node vert_encoder/embedding_1/embedding_lookup}}]]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It seems like provided embedding table and sample dimension is not matched.
> > I download `demo` data from https://recodatasets.blob.core.windows.net/newsrec/MINDdemo_train.zip, https://recodatasets.blob.core.windows.net/newsrec/MINDdemo_dev.zip, https://recodatasets.blob.core.windows.net/newsrec/MINDdemo_utils.zip.
> > ### In which platform does it happen?
> > I am using TensorFlow-gpu 1.15.3, Ubuntu 18.04.
> > ### How do we replicate the issue?
> > Just run `recommenders/examples/00_quick_start/naml_MIND.ipynb`.
> > ### Expected behavior (i.e. solution)
> > Printing accuracy is expected.
> > ### Other Comments
> 
> change vert_num in "naml.yaml" to 19

can you tell me how  to change vert_num in "naml.py"?thanks
