### ISSUE TITLE
[ASK] Why we need to put a tanh layer after kims_cnn module in dkn_item2item? 

### ISSUE THREAD

**Issue by FanFanFanYang** [microsoft/recommenders#1324]
### Description
I think the output of kims_cnn is an dense embedding, right? Why need an extra layer?
https://github.com/microsoft/recommenders/blob/cbc863f320624fc87d6d008a244fe55fcf954856/reco_utils/recommender/deeprec/models/dkn_item2item.py#L62

**Comment by miguelgfierro** [comment]
Closing since there hasn't been interaction for a while
