### ISSUE TITLE
[FEATURE] make tqdm optional

### ISSUE THREAD

**Issue by gramhagen** [microsoft/recommenders#1333]
### Description
currently tqdm is required to download datasets, given this is just for a visual progress indicator it would be preferable if there was no dependency on tqdm, or at least a graceful fallback to continuing to download data without that library

### Expected behavior with the suggested feature

this should run without tqdm installed
```
from reco_utils.dataset.movielens import load_pandas_df
df = load_pandas_df()
```

**Comment by miguelgfierro** [comment]
@gramhagen, I'll doing some cleaning on the repo. Is this still a problem?

**Comment by gramhagen** [comment]
we can close this, now that we're using a package with installed dependencies i think this is ok
