### ISSUE TITLE
Cannot replicate LSTUR results for MIND large test

### ISSUE THREAD

**Issue by albertobezzon** [microsoft/recommenders#1342]
Hello, I cannot replicate the results of LSTUR model with MIND test set. I used the scripts provided to generate `embedding.npy`, `word_dict.pkl` and `uid2index.pkl` for test set because they are not provided with MINDlarge_utils.zip. 
I use the last lines of code in lstur_MIND.pynb to make predictions in test set, but the results of metrics in validations and test are very differents.

For example, I obtained 
`group_auc: 0.65, mean_mrr: 0.31, ndcg@5: 0.34, ndcg@10: 0.40` in validation and `auc: 0.5075, mrr: 0.2259, ndcg@5: 0.2309, nDCG@10: 0.2868` in test set, with the model trained for 10 epochs.

**Comment by Hieu-LeMinh** [comment]
Do you have a solution yet ??

**Comment by Hieu-LeMinh** [comment]
> Hello, I cannot replicate the results of LSTUR model with MIND test set. I used the scripts provided to generate `embedding.npy`, `word_dict.pkl` and `uid2index.pkl` for test set because they are not provided with MINDlarge_utils.zip.
> I use the last lines of code in lstur_MIND.pynb to make predictions in test set, but the results of metrics in validations and test are very differents.
> 
> For example, I obtained
> `group_auc: 0.65, mean_mrr: 0.31, ndcg@5: 0.34, ndcg@10: 0.40` in validation and `auc: 0.5075, mrr: 0.2259, ndcg@5: 0.2309, nDCG@10: 0.2868` in test set, with the model trained for 10 epochs.
Do you have a solution yet ??

**Comment by albertobezzon** [comment]
> Do you have a solution yet ??

I originally calculated the embeddings for the test set only and used them for prediction. I solved it, recalculating all the embeddings for train, validation and test set.
