### ISSUE TITLE
Getting com.microsoft.aad.msal4j.AcquireTokenSilentSupplier failed error on getting access token from clientSecret 

### ISSUE THREAD

**Issue by SuryaAnand302** [microsoft/recommenders#1345]
Hi Team,

I am trying to get access token from clientSecret. Please find below code snippet.

`IClientCredential cred = ClientCredentialFactory.createFromSecret(clientSecret);
ConfidentialClientApplication app;
try {
// Build the MSAL application object for a client credential flow
app = ConfidentialClientApplication.builder(applicationId, cred ).authority(authority).build();
} catch (MalformedURLException e) {
System.out.println("Error creating confidential client: " + e.getMessage());
return null;
}

    IAuthenticationResult result;
    try{
        SilentParameters silentParameters = SilentParameters.builder(scopeSet).build();
        result= app.acquireTokenSilently(silentParameters).join();
    } catch (Exception ex ){
        if (ex.getCause() instanceof MsalException) {
     
            ClientCredentialParameters parameters =
                    ClientCredentialParameters
                            .builder(scopeSet)
                            .build();
     
            // Try to acquire a token. If successful, you should see
            // the token information printed out to console
            result = app.acquireToken(parameters).join();
        } else {
            // Handle other exceptions accordingly
            System.out.println("Unable to authenticate = " + ex.getMessage());
            return null;
        }
    }`
But while running I am getting below error, can you please suggest me when changes I have to make.
I am using msal4j-1.9.1.jar.

[ForkJoinPool.commonPool-worker-1] ERROR com.microsoft.aad.msal4j.ConfidentialClientApplication - [Correlation ID: 7c7ce67e-*********]
Execution of class com.microsoft.aad.msal4j.AcquireTokenSilentSupplier failed.
com.microsoft.aad.msal4j.MsalClientException: java.net.SocketTimeoutException: connect timed out

**Comment by gramhagen** [comment]
Hi @SuryaAnand302, can you provide more detail on which part of the repo this code relates to? 
My first impression is that it would be better to raise this issue here: https://github.com/AzureAD/microsoft-authentication-library-for-java
But I want to make sure if you're using an example from our repo that is broken we can address it here too.

**Comment by SuryaAnand302** [comment]
Hi @gramhagen, I have posted the first time so might posted on wrong window, so I'll take care it from next time.
Yes, the code is not from your repository, its from the docs.microsoft.com.

**Comment by gramhagen** [comment]
np, I will close this issue here then.
