### ISSUE TITLE
[FEATURE] Consider adding BiVAE model 

### ISSUE THREAD

**Issue by tqtg** [microsoft/recommenders#1352]
### Description

Hi,
I would like to contribute a notebook explaining [Bilateral Variational Autoencoder (BiVAE)](https://dl.acm.org/doi/pdf/10.1145/3437963.3441759) model presented in WSDM'21. The implementation of BiVAE is under [Cornac](https://github.com/PreferredAI/cornac) library which covers the BPR tutorial added earlier.
Let me know if this contribution is favorable. Thanks!

**Comment by gramhagen** [comment]
Yes, of course. That would be awesome!

We're currently making a lot of small changes to better support installation through PyPI, but if you want to start work on an example notebook we can fold in any changes that may impact testing or dependencies.

**Comment by gramhagen** [comment]
merged to staging, will be pushed to main with the next release. Thanks so much for the contribution @tqtg!

**Comment by satsaras** [comment]
how to use bivae cap with user and item features? The notebook doesnt explain that
