### ISSUE TITLE
[BUG] Fix Docs / Doc Pipeline

### ISSUE THREAD

**Issue by gramhagen** [microsoft/recommenders#1354]
### Description
Update docs and make sure pipeline is correctly building / updating docs

### How do we replicate the issue?
with merge to staging/main docs should update

**Comment by gramhagen** [comment]
I just came across this site, may be worth looking at wrt our doc effort here: https://thegooddocsproject.dev/

**Comment by miguelgfierro** [comment]
Closing this issue, the documentation is working now
