### ISSUE TITLE
[FEATURE] Move AzureML Designer Modules

### ISSUE THREAD

**Issue by gramhagen** [microsoft/recommenders#1355]
### Description
Determine where to put azureml design module in reco_utils package to reduce dependencies

### Expected behavior with the suggested feature
potentially moving code to contrib?

**Comment by miguelgfierro** [comment]
hi @likebupt, we are moving to create a pipy package for recommenders, there is a PR going on here https://github.com/microsoft/recommenders/pull/1346

Do you think it would be ok to move all the content of the designer to `contrib` folder?

**Comment by likebupt** [comment]
> hi @likebupt, we are moving to create a pipy package for recommenders, there is a PR going on here #1346
> 
> Do you think it would be ok to move all the content of the designer to `contrib` folder?

It's okay to move the folder, but we may need to change the script of modules as well.

**Comment by anargyri** [comment]
@miguelgfierro this issue can be closed, it seems.
