### ISSUE TITLE
[FEATURE] Add VowpalWabbit from PyPI 

### ISSUE THREAD

**Issue by gramhagen** [microsoft/recommenders#1356]
### Description
Modify example notebooks to use vowpalwabbit package in python directly instead of subprocess calls

**Comment by AdityaSoni19031997** [comment]
Hey!
Should I help in closing this issue?

Be Safe,
Best,
Aditya.

**Comment by gramhagen** [comment]
it would be nice to have an example using the python package instead of requiring vw to be installed and used from the command line. that said, @YanZhangADS looked into this recently and came to the conclusion that working with large scale datasets is probably more performant to use the command line. so it might be nice to show an example of how one would use the command line if the dataset is too large, otherwise using the python package with the sklearn wrapper should be a better user experience than the current notebook here: https://github.com/microsoft/recommenders/blob/main/examples/02_model_content_based_filtering/vowpal_wabbit_deep_dive.ipynb

**Comment by miguelgfierro** [comment]
@YanZhangADS analyzed whether to use pip version or directly the c++. She found that it is more optimal to use the C++ version. 

Closing this for now. Feel free to reopen if you consider.

**Comment by AdityaSoni19031997** [comment]
Yep, it's better to use it from the terminal directly in my experience as well.
