### ISSUE TITLE
[FEATURE] Installation via `pip install recommenders` or `conda install recommenders`

### ISSUE THREAD

**Issue by zkneupper** [microsoft/recommenders#1361]
### Description
Would your team consider making the recommenders package installable from the PyPi and/or Anaconda package repository?

Rather than cloning the git repository and installing from that, users could

`pip install recommenders`

or

`conda install recommenders`

### Other Comments
I would love to help in any way I can.

**Comment by gramhagen** [comment]
Thanks @zkneupper for offering to help! This is something we are actively working on. You should be able to pip install from the repo now.  Can you check the instructions [here](https://github.com/microsoft/recommenders/blob/staging/reco_utils/README.md) to see if they are clear and work for you? Any feedback that would be very helpful!

Our next step is to publish this PyPI so checking out the repo is not necessary, but there are couple things we'd like to wrap up first.
-  #1354 
-  #1355

**Comment by dciborow** [comment]
@zkneupper , we are up on pypi!
https://pypi.org/project/recommender-utils/#description

pip install recommender-utils

**Comment by zkneupper** [comment]
> @zkneupper , we are up on pypi!
> https://pypi.org/project/recommender-utils/#description
> 
> pip install recommender-utils

Congratulations! Thanks for the team's work on this to make it pip-installable. 👍

**Comment by gramhagen** [comment]
please note the package name will likely change over the next few weeks, we'll keep you posted.
