### ISSUE TITLE
[BUG] integration tests must not be executed if smoke test fail

### ISSUE THREAD

**Issue by miguelgfierro** [microsoft/recommenders#1364]
### Description

With the last change, integration test are executed even if smoke tests fail, see example: https://dev.azure.com/best-practices/recommenders/_build/results?buildId=46125&view=logs&j=5264e576-3c6f-51f6-f055-fab409685f20&t=b3018297-00ec-509d-8d8a-45865fb67b06

### Other Comments
FYI @gramhagen

**Comment by miguelgfierro** [comment]
try this on spark tests, only 15min: https://dev.azure.com/best-practices/recommenders/_build?definitionId=164&_a=summary

**Comment by miguelgfierro** [comment]
with timeout of 3min (it should fail because the pipeline takes longer than 3min) the pipeline doesn't work properly -> https://dev.azure.com/best-practices/recommenders/_build/results?buildId=46276&view=logs&j=5264e576-3c6f-51f6-f055-fab409685f20&t=afa25a3a-cb48-5dc9-c093-b77a0626746f

I'm enforcing a test to fail: `assert True == False`. The pipeline doesn't fail, it appears always as working -> https://dev.azure.com/best-practices/recommenders/_build/results?buildId=46275&view=logs&j=5264e576-3c6f-51f6-f055-fab409685f20&t=b3018297-00ec-509d-8d8a-45865fb67b06

@gramhagen have you noticed this behavior? I think right now all the pipelines will pass in ADO even if some tests fail

**Comment by gramhagen** [comment]
i'm hoping it's an easy fix. I will force a test failure and see if pushing publishing to happen inside the loop will address this.
