### ISSUE TITLE
[ASK] New Python recommender systems library - LibRecommender 

### ISSUE THREAD

**Issue by julioasotodv** [microsoft/recommenders#1366]
Hi!

just FYI, a new Python library that includes some interesting reco algorithms was recently added to Github: https://github.com/massquantity/LibRecommender

Maybe it would be interesting to include some usecases for some of the included algos that are not covered yet by this repo.

thank you!

**Comment by miguelgfierro** [comment]
this library has many of the algos that we already have, we can review it in the future in case we see there are newest additions
