### ISSUE TITLE
[ASK] the negtive sample is not very well in NCF 

### ISSUE THREAD

**Issue by ucasiggcas** [microsoft/recommenders#1379]
### Description
hi,dear 
Have tried the [NCF](https://github.com/microsoft/recommenders/blob/main/examples/00_quick_start/ncf_movielens.ipynb) with the ml-20m dataset, but killed by memory,then I find the codes down, **when I only sample 100 negtive items**, the process is also very slow, so how to deal with it ?
```
self.interact_status[self.col_item + "_negative"] = self.interact_status[
            self.col_item + "_interacted"
        ].apply(lambda x: self.item_pool - x)
```

could I training the big data in an hour ?

**Comment by miguelgfierro** [comment]
We are investigating the same issue https://github.com/microsoft/recommenders/issues/1561 and soon we will do a PR. Closing this issue
