### ISSUE TITLE
[Typo?] Code clone tab points to old master and not to new main

### ISSUE THREAD

**Issue by prvenk** [microsoft/recommenders#1382]
### Description

I cloned the repository as below but it seems to point to an old version of master. 

![image](https://user-images.githubusercontent.com/65745778/115778157-14c1b780-a36b-11eb-9ab4-52f49f3d8083.png)

Found this in the setup document and cloning this way got me to main.

![image](https://user-images.githubusercontent.com/65745778/115778792-088a2a00-a36c-11eb-8438-94d58004ff5a.png)

Seems like a simple fix to update the clone link.

**Comment by miguelgfierro** [comment]
not sure I understand, if you do:
```
git clone https://github.com/microsoft/recommenders
git status
```
what branch do you see?

**Comment by prvenk** [comment]
Hmm now it points to main. Earlier I saw master and didn't see main. Will close this.
