### ISSUE TITLE
[BUG] tests/resources/deeprec/slirec very large (over 3GB)

### ISSUE THREAD

**Issue by wutaomsft** [microsoft/recommenders#1383]
### Description

tests/resources/deeprec/slirec is very large (over 3GB)  @miguelgfierro

**Comment by miguelgfierro** [comment]
@wutaomsft a question about this, can you clarify what is the expected output for this bug?

Just for context, SliRec is an algo made by Jianxun and team, the dataset that is downloaded into test/resources/etc, but not loaded into the repo

**Comment by wutaomsft** [comment]
You are right @miguelgfierro - this is not in the repo but only generated during test.  Closing.
