### ISSUE TITLE
MemoryError: Unable to allocate 75.6 GiB for an array with shape (63577, 319205) and data type float32

### ISSUE THREAD

**Issue by rookiexiao123** [microsoft/recommenders#1387]
如果我的数据很大，如果才能让它运行下去呢？我没有办法增加内存或者删减数据集。
If my data is big, what if I can make it work? I have no way to increase memory or delete datasets.

**Comment by miguelgfierro** [comment]
this is a common issue, make sure that your GPU memory is large enough. Another solution is to reduce the batch size
