### ISSUE TITLE
conda env create Access Denied

### ISSUE THREAD

**Issue by joshidp** [microsoft/recommenders#1391]
Hi All,

Thanks for your work.

I'm getting exception while executing the conda env create -f reco_base.yaml
command  from https://github.com/microsoft/recommenders/blob/main/SETUP.md

It's giving me below exception, I tried running the command with admin privelage  but same issue is coming and I tried it on multiple machines also. I am on latest conda and python 3.8

Successfully built xlearn gast memory-profiler fusepy termcolor wrapt antlr4-python3-runtime future pyreadline
Installing collected packages: idna, oauthlib, requests-oauthlib, PyJWT, isodate, decorator, msrest, azure-core, adal, websocket-client, pyasn1, msrestazure, jeepney, backports.weakref, azure-mgmt-core, azure-common, SecretStorage, ruamel.yaml, pathspec, ndg-httpsclient, jsonpickle, jmespath, docker, contextlib2, backports.tempfile, azure-mgmt-storage, azure-mgmt-resource, azure-mgmt-keyvault, azure-mgmt-containerregistry, azure-mgmt-authorization, azure-graphrbac, applicationinsights, nbconvert, distro, azureml-train-restclients-hyperdrive, azureml-telemetry, azureml-core, dotnetcore2, dataclasses, azureml-train-core, azureml-pipeline-core, azureml-dataprep-native, numpy, fusepy, cached-property, botocore, black, azureml-pipeline-steps, azureml-dataprep, zope.interface, zope.event, wheel, Werkzeug, tabulate, s3transfer, pyreadline, pynacl, protobuf, portalocker, patsy, markdown, itsdangerous, h5py, grpcio, greenlet, bcrypt, azureml-train, azureml-pipeline, azure-nspkg, argcomplete, absl-py, wrapt, tokenizers, termcolor, tensorflow-estimator, tensorboard, statsmodels, sentencepiece, sacremoses, pymongo, pyarrow, paramiko, opt-einsum, networkx, knack, keras-preprocessing, keras-applications, humanfriendly, google-pasta, gevent, gast, future, flask, filelock, boto3, azureml-widgets, azureml-tensorboard, azureml-sdk, azureml-contrib-notebook, azure-storage-common, azure-cli-telemetry, azure-cli-nspkg, astor, antlr4-python3-runtime, xlearn, transformers, tensorflow, scrapbook, pymanopt, pydocumentdb, memory-profiler, locustio, hyperopt, category-encoders, azure-storage-blob, azure-mgmt-cosmosdb, azure-cli-core
  Attempting uninstall: idna
    Found existing installation: idna 2.10
    Uninstalling idna-2.10:
      Successfully uninstalled idna-2.10
  Attempting uninstall: decorator
    Found existing installation: decorator 5.0.6
    Uninstalling decorator-5.0.6:
      Successfully uninstalled decorator-5.0.6
  Attempting uninstall: pathspec
    Found existing installation: pathspec 0.7.0
    Uninstalling pathspec-0.7.0:
      Successfully uninstalled pathspec-0.7.0
  Attempting uninstall: nbconvert
    Found existing installation: nbconvert 6.0.7
    Uninstalling nbconvert-6.0.7:
      Successfully uninstalled nbconvert-6.0.7
  Attempting uninstall: numpy
    Found existing installation: numpy 1.19.2
    Uninstalling numpy-1.19.2:
      Successfully uninstalled numpy-1.19.2
  Attempting uninstall: black
    Found existing installation: black 19.10b0
    Uninstalling black-19.10b0:
      Successfully uninstalled black-19.10b0

**Pip subprocess error:
ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\Users\\dejosh\\AppData\\Local\\Temp\\pip-uninstall-xb_9p36c\\black.exe'
Consider using the `--user` option or check the permissions.**

**Comment by gramhagen** [comment]
seems like an issue with admin access to Temp folder
similar topics here:
- https://github.com/pypa/pip/issues/6068
- https://github.com/conda/conda/issues/2893

might be worth trying to disable antivirus temporarily?

**Comment by joshidp** [comment]
I have full admin access and tried on multiple machines, I am working on azure data science vm. There are other packages which are getting installed without any issue only for this package access issue is coming.

**Comment by gramhagen** [comment]
i will try to repro, you are using Windows 2019 server instance of a Azure DSVM?

**Comment by joshidp** [comment]
Yes, freshly created DSVM and performed the steps written in below link

https://github.com/microsoft/recommenders/blob/main/SETUP.md

**Comment by gramhagen** [comment]
i see the same error, however the conda environment is created and appears to have all the necessary packages/versions.
i would suggest ignoring the error for now, I don't see an easy way to get past it currently. a lot of this will be changing as we switch to pypi based installation, so hopefully some of these issues will go away.
let us know if you encounter issues using the conda environment.

**Comment by gramhagen** [comment]
hmm, i take that back, some of the pip packages are missing

**Comment by gramhagen** [comment]
ok, a few problems on windows, tensorflow 1.15.4 is no longer available from pypi, so i think the easiest thing to do for now is to manually install pip packages

create a new requirments.txt with the following taken from reco_base.yaml (excluding tensorflow)
```
azureml-sdk[notebooks,tensorboard]==1.0.69
azure-storage-blob<=2.1.0
azure-cli-core==2.0.75
azure-mgmt-cosmosdb==0.8.0
black>=18.6b4
category_encoders>=1.3.0
dataclasses>=0.6
hyperopt==0.1.2
idna==2.7
locustio==0.11.0
memory-profiler>=0.54.0
nbconvert>=5.5.0
pydocumentdb>=2.3.3
pymanopt==0.2.5
xlearn==0.40a1
transformers==2.5.0
scrapbook>=0.5.0
```

then execute the following
```
# these don't need to be repeated if you already have a conda environment (it's ok if it failed with the error you mentioned)
python tools/generate_conda_file.py
conda env create -f reco_base.yaml

# now activate and manually install requirements
conda activate reco_base
pip install -r requirements.txt
```

python

**Comment by joshidp** [comment]
Yeah, I am doing impacted packages installation manually.
