### ISSUE TITLE
create a conda environment error[BUG] 

### ISSUE THREAD

**Issue by donttal** [microsoft/recommenders#1411]
### Description
(base) ➜  Recommenders git:(main) conda env create -f reco_base.yaml
Collecting package metadata (repodata.json): failed

    Traceback (most recent call last):
        raise Response304ContentUnchanged()
    conda.core.subdir_data.Response304ContentUnchanged

    During handling of the above exception, another exception occurred:

An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?

[y/N]: y
Upload successful.

Thank you for helping to improve conda.
Opt-in to always sending reports (and not see this message again)
by running

    $ conda config --set report_errors true

**Comment by gramhagen** [comment]
This looks like a problem with conda specifically, please see related issue here for possible remedies or further support: https://github.com/conda/conda/issues/8051

**Comment by donttal** [comment]
> This looks like a problem with conda specifically, please see related issue here for possible remedies or further support: [conda/conda#8051](https://github.com/conda/conda/issues/8051)

thanks
