### ISSUE TITLE
[ASK] NCFDataset need memory > 100G to serve 1.6 million record df

### ISSUE THREAD

**Issue by hahmad2008** [microsoft/recommenders#1432]
### Description

I have a rating dataframe with 1618496 rows.  but when I started to use the NCF method from the recommenders library, the kernel restarted when it reached **`data = NCFDataset(train=train, test=test, seed=SEED)`** and I notice the memory on the monitor hit 100G, and then it can't afford more to complete this line.

So please how to overcome this issue? and how people use it with big dataframe how to deal with it? is there any option use to handle big data?

### Other Comments

* Process from monitor window:
* 
![image](https://user-images.githubusercontent.com/68266028/121140212-4078fe00-c842-11eb-9cd0-9757fe8705c9.png)

**Comment by miguelgfierro** [comment]
Working on a fix right now and summarizing everything in the issue https://github.com/microsoft/recommenders/issues/1561. We'll do a PR soon. I'll close this one
