### ISSUE TITLE
[FEATURE] Move the tests to hosted machines

### ISSUE THREAD

**Issue by miguelgfierro** [microsoft/recommenders#1460]
### Description

Right now, we have the tests on a DSVM that is running 24/7. These tests run sequentially. 

We want to change this and run the test in hosted VMs and in parallel. We should have a matrix that tests python 3.6 and 3.7

**Comment by miguelgfierro** [comment]
@laserprec added you as owner

**Comment by laserprec** [comment]
Non-gpu tests are moved to Github-hosted machines with PR #1494
