### ISSUE TITLE
[BUG] Cleanup documentation

### ISSUE THREAD

**Issue by wutaomsft** [microsoft/recommenders#1468]
### Description
Instructions on setting up environment are now fragmented.  The information is spreaded in 
1. README.md
2. SETUP.md
3. reco_utils/READM.md

It is quite confusing even for someone experienced with this work.  Suggest to clean up these instructions and consolidate.

### In which platform does it happen?
All.

### Expected behavior (i.e. solution)

Suggested Principles:
1. We should separate instructions for using the repo, vs developing for the repo.
2. For using the repo (especially for the first-time user), the instructions should be short and aim to enable user to get set up  in the shortest time. (this is the "fast lane").  Only include content/instructions that are mandatory.  We should target reading + following instructions in fast lane take no longer than 1 minute.
3. For developing for the repo, the instructions may have to be longer, more detailed and contains some debugging information (this is the "slow lane"). these instructions should be separate from the "fast lane".
4. If there are more complex (or rarer) usage instructions, consider putting it in slow lane.

### Other Comments
Additionally, pip install followed by launching jupyter notebook does not seem to work (as notebooks are not installed by pip).

**Comment by miguelgfierro** [comment]
@laserprec @simonzhaoms since you are already reviewing the SETUP documentation, please see some notes from Tao yo might want to consider
