### ISSUE TITLE
[FEATURE] Evaluation API / module consistency

### ISSUE THREAD

**Issue by gramhagen** [microsoft/recommenders#1472]
### Description
Spark based evaluation metrics for rating, ranking, and diversity are separated into different classes, but all consolidated into one package now: reco_utils.evaluation.spark_evaluation. Additionally the python based evaluation is in a single file, but the interface is not class based. It would be ideal to consolidate the api for both python and spark side into either purely functional or class-based approaches. Additionally, the proper separation of concerns can be applied to move specific functionality into separate packages: e.g. spark_rating_evaluation.py would only contain the SparkRatingEvaluation class. The goal would be to shorten and simplify each  individual class/module so that maintenance and enhancements would be easier.

#1470

**Comment by miguelgfierro** [comment]
fixed now https://github.com/microsoft/recommenders/tree/main/recommenders/evaluation
