### ISSUE TITLE
[BUG] Unable to install on Python 3.7.11

### ISSUE THREAD

**Issue by dciborow** [microsoft/recommenders#1473]
### Description
I am unable to install recommenders 0.6.0 on Python 3.7.11. Proposing an update to loosen pin.

**Comment by dciborow** [comment]
#1474

**Comment by miguelgfierro** [comment]
@dciborow can you share the error?

I know that @anargyri did some tests with 3.7

**Comment by anargyri** [comment]
3.7 works with conda, not with venv (the issue of Surprise and numpy conflict) but the version was < 3.7.11 (I think it was 3.7.5 or close to that).

**Comment by miguelgfierro** [comment]
fixed on https://pypi.org/project/recommenders/. Now when doing pip install recommenders==0.6.0 it should work with python<3.8
