### ISSUE TITLE
[BUG] No module named 'reco_utils'

### ISSUE THREAD

**Issue by xu-song** [microsoft/recommenders#1486]
### Description

Error `No module named 'reco_utils'` in docker test

https://github.com/microsoft/recommenders/tree/main/tools/docker

```
$ docker run -it recommenders:cpu pytest tests/unit -m "not spark and not gpu and not notebooks"
ImportError while loading conftest '/root/recommenders/tests/conftest.py'.
tests/conftest.py:22: in <module>
    from reco_utils.common.constants import (
E   ModuleNotFoundError: No module named 'reco_utils'
```

### In which platform does it happen?

Linux  cpu docker

**Comment by gramhagen** [comment]
the dockerfile needs to be updated to use recommenders package from pypi

**Comment by xu-song** [comment]
looking forward to your update.

**Comment by miguelgfierro** [comment]
fixed in the latest release: https://github.com/microsoft/recommenders/blob/main/tools/docker/Dockerfile
