### ISSUE TITLE
[ASK] Can this library be made compatible with Microsoft Azure DataBricks?

### ISSUE THREAD

**Issue by oliver-causey** [microsoft/recommenders#1496]
### Description
I am trying to run this library on azure DataBricks. This library requires Python 3.6 or Python 3.7. However, Python 3 on DataBricks is Python 3.8.8, with no option to downgrade. I have been unable to find a workaround for this. Does anyone have any suggestions?

### In which platform does it happen?
Azure DataBricks

### How do we replicate the issue?
Run the following in a DataBricks notebook:

!pip install ms-recommenders

### Expected behavior (i.e. solution)
The library should successfully install

### Other Comments

I am aware that it is a Python version compatibility issue. It seems weird that the Microsoft platform I am using is completely incompatible with the Microsoft library I am trying to use.

**Comment by gramhagen** [comment]
All Azure Databricks runtimes < 8.0 use a python version < 3.8, more info can be found here: https://docs.microsoft.com/en-us/azure/databricks/release-notes/runtime/releases. When creating a cluster you can choose a lower runtime version for compatibility with this package.

please use [recommenders](https://pypi.org/project/recommenders/) as ms-recommenders is deprecated. we are working to support python 3.8 but as it stands there are some dependency issues that need to be resolved with pytorch & tensorflow.

**Comment by oliver-causey** [comment]
Thank you very much! I am a newbie to DataBricks.
