### ISSUE TITLE
[BUG] AttributeError: module 'tensorflow.keras.initializers' has no attribute 'truncated_normal'\n in multinomial_vae.py

### ISSUE THREAD

**Issue by k9luo** [microsoft/recommenders#1513]
### Description

Based on the Global Settings and Imports in the [example notebook](https://github.com/microsoft/recommenders/blob/main/examples/02_model_collaborative_filtering/multi_vae_deep_dive.ipynb) for multinomial_vae, it requires `tensorflow==2.2.0-rc1` and `keras==2.3.1`. After I installed these two libraries and ran the code, I got `AttributeError: module 'tensorflow.keras.initializers' has no attribute 'truncated_normal'\n` when running multinomial_vae.py. According to [Tensorflow 2.2 documentation](https://www.tensorflow.org/versions/r2.2/api_docs/python/tf/keras/initializers), there isn't a class called `truncated_normal ` but there is one named `TruncatedNormal`.

### How do we replicate the issue?

Running the notebook would probably encounter this error.

### Expected behavior (i.e. solution)

Change `truncated_normal ` to `TruncatedNormal` in [here](https://github.com/microsoft/recommenders/blob/staging/recommenders/models/vae/multinomial_vae.py#L291) and [here](https://github.com/microsoft/recommenders/blob/staging/recommenders/models/vae/multinomial_vae.py#L308) should resolve this problem.

**Comment by miguelgfierro** [comment]
this PR should fix your problem https://github.com/microsoft/recommenders/pull/1565
