### ISSUE TITLE
No module named 'recommenders'[ASK] 

### ISSUE THREAD

**Issue by dagartga** [microsoft/recommenders#1519]
### Description
I am running a Google Colab notebook for the 00_quick_start/als_movielens.ipynb I have done !pip install recommenders and when I do !pip show recommenders it shows that it has been installed. But when I run the cell with from recommenders.utils.timer import Timer I get an error message. It is attached. I am not sure what I am doing wrong. I am using Windows 10 and Python 3.7.11
![recommenders_error](https://user-images.githubusercontent.com/65997824/132077290-57c068d3-41b2-404b-baf3-88a9c3d97836.png)

**Comment by abdsamadf** [comment]
@dagartga Did you find any solution? I am having the same problem.

**Comment by gramhagen** [comment]
the imports in the current examples in the repository are based on changes that are not released in the latest 0.6.0 package on PyPI. We are working to release a fix for this, in the meantime if you want to use these tools with the package from PyPI you will need to use examples from that tagged branch: https://github.com/microsoft/recommenders/tree/0.6.0/examples

alternatively, install from source (either clone the main branch and run `pip install .` or install from github: `pip install git+https://github.com/microsoft/recommenders@98d661edc6a9965c7f42b76dc5317af3ae74d5e0#egg=recommenders`) to use the latest examples in main.

**Comment by rwforest** [comment]
@gramhagen Can you help me understand why only the commit version specified in your comment works and others don't?
For example, I did

```pip install -e git+https://github.com/microsoft/recommenders/#egg=recommenders```

```from recommenders.utils.timer import Timer```

It'd complain about module not found

**Comment by naina12** [comment]
> the imports in the current examples in the repository are based on changes that are not released in the latest 0.6.0 package on PyPI. We are working to release a fix for this, in the meantime if you want to use these tools with the package from PyPI you will need to use examples from that tagged branch: https://github.com/microsoft/recommenders/tree/0.6.0/examples
> 
> alternatively, install from source (either clone the main branch and run `pip install .` or install from github: `pip install git+https://github.com/microsoft/recommenders@98d661edc6a9965c7f42b76dc5317af3ae74d5e0#egg=recommenders`) to use the latest examples in main.

I installed the recommenders as explained and while running lightGCN example i got error "AttributeError: module 'tensorflow' has no attribute 'contrib'" in google colab. plz help

**Comment by abdsamadf** [comment]
You can install the recommenders library by using this command `pip install git+https://github.com/microsoft/recommenders.git`. It works for me.

**Comment by naina12** [comment]
Thank you sir, it worked.

**Comment by gramhagen** [comment]
@rwforest can you retry without using the editable flag? -e 
If that doesn't work you might need to try a fresh virtual environment

**Comment by rwforest** [comment]
> @rwforest can you retry without using the editable flag? -e
> If that doesn't work you might need to try a fresh virtual environment

@gramhagen that worked thank you

**Comment by miloooooz** [comment]
@gramhagen Hi, I got recommender0.6.0 installed and when I enter pip freeze it does show in the list. But my jupyter notbook still gives `ModuleNotFoundError: No module named 'recommenders'` error, I wonder why does it happen.
I have checked `pip -V`, it gives `pip 20.1.1 from /anaconda/envs/azureml_py36/lib/python3.6/site-packages/pip (python 3.6)` and `sys.path` gives 
```
['/anaconda/envs/azureml_py36/lib/python36.zip',
 '/anaconda/envs/azureml_py36/lib/python3.6',
 '/anaconda/envs/azureml_py36/lib/python3.6/lib-dynload',
 '',
 '/home/azureuser/.local/lib/python3.6/site-packages',
 '/anaconda/envs/azureml_py36/lib/python3.6/site-packages',
 '/anaconda/envs/azureml_py36/lib/python3.6/site-packages/IPython/extensions',
 '/home/azureuser/.ipython',
 '/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azureml/_project/vendor',
 '/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azureml/automl/core/_vendor']
```
So I assume the env where my jupyter notebook runs should already be consistent with the site where I install my packages, but it still shows `ModuleNotFoundError`, any advice would be super appreciated, thanks.

**Comment by anargyri** [comment]
These changes have now been released on PyPI as v. 0.7.0, so the issue should be fixed now.
