### ISSUE TITLE
[ASK] Questions about Building and Running with Docker

### ISSUE THREAD

**Issue by ljy0ustc** [microsoft/recommenders#1523]
### Description

After I built and ran with docker according to this instruction,
![image](https://user-images.githubusercontent.com/87422961/132969183-17b63623-3354-463d-ab83-cc16a4ba48e2.png)
I open the Jupyter Notebook at  http://localhost:8888 to run an example "dkn_deep_dive" but receive the following error:
![image](https://user-images.githubusercontent.com/87422961/132969159-cec166f0-1817-4072-afbf-3aa7980b0739.png).

**Comment by ljy0ustc** [comment]
Should I install the "recommenders" module on my own using "pip" after running with docker?

**Comment by lhojun** [comment]
In my case, it was helpful to do a manual pip install independent of docker.
Probably same problem as #1519.
(It is assumed that pip install fails during docker image build process)
try this:
``pip install git+https://github.com/microsoft/recommenders.git``
