### ISSUE TITLE
[BUG] can't install recommenders from pip

### ISSUE THREAD

**Issue by miloooooz** [microsoft/recommenders#1537]
```
/Users/milozhou$ pip install recommenders
ERROR: Could not find a version that satisfies the requirement recommenders (from versions: none)
ERROR: No matching distribution found for recommenders
```

I tried to install recommender from pip and run it in jupyter from Azure Machine Learning, but it doesn't work, did I do it wrong? Thanks in advance.

**Comment by gramhagen** [comment]
What version of python are you using? Right now I believe we only support <= 3.7

**Comment by miloooooz** [comment]
@gramhagen Thanks, I turned to 3.6 and it's solved.
