### ISSUE TITLE
[BUG] Build failed on Pyspark 3.2.0 

### ISSUE THREAD

**Issue by laserprec** [microsoft/recommenders#1553]
### Description
Our smoke and unit tests failed on the latest pyspark v3.2.0 in `staging` branch.

### In which platform does it happen?
In our CI pipelines and in linux virtual machines. For details of the errors, please visit the following links:
- [nightly](https://github.com/microsoft/recommenders/runs/3928935302?check_suite_focus=true)
- [pr-gate](https://github.com/microsoft/recommenders/runs/3940426052?check_suite_focus=true)
- [dsvm_notebook_linux_pyspark](https://dev.azure.com/best-practices/recommenders/_build/results?buildId=52781&view=results) (ADO pipeline)

### How do we replicate the issue?
- `git clone https://github.com/microsoft/recommenders.git`
- `git checkout staging`
- `pip install -e .[spark,example,dev]`
- `pytest tests/unit/examples/test_notebooks_pyspark.py`

### Expected behavior (i.e. solution)
Our current dependency bounds for pyspark is `>=2.4.5, <4.0.0`. However, pyspark[ released 3.2.0 yesterday](https://pypi.org/project/pyspark/#history) (10/18/2021) that broke our build

We should set the bounds for pyspark to `>=2.4.5, <3.2.0` as a hotfix.

**Comment by miguelgfierro** [comment]
@anargyri this issue is fixed with the latest code from @simonzhaoms?

**Comment by anargyri** [comment]
> @anargyri this issue is fixed with the latest code from @simonzhaoms?

Does SAR+ have the mmlspark coordinates anywhere? the notebook takes them from here https://github.com/microsoft/recommenders/blob/ba24adc77d46df9f7dd94ee0e197b4519af1d3e2/recommenders/utils/spark_utils.py#L12

**Comment by miguelgfierro** [comment]
Maven: https://search.maven.org/artifact/com.microsoft.sarplus/sarplus_2.12/0.5.0/jar
Installation instructions: https://github.com/microsoft/recommenders/tree/staging/contrib/sarplus

**Comment by simonzhaoms** [comment]
@miguelgfierro @anargyri SAR+ doesn't requires mmlspark
As I know from the upgrade of SAR+, Spark 3.2 has several breaking changes from Spark 3.1.  And mmlspark hasn't not support Spark 3.2 yet.

**Comment by miguelgfierro** [comment]
@laserprec @simonzhaoms is this issue solved?

**Comment by simonzhaoms** [comment]
I think using `com.microsoft.azure:synapseml_2.12:0.9.4` and replacing `from mmlspark.xxx` with `from synapse.ml.xxx` may solve the problem.  See [SynapseML (mmlspark)](https://github.com/microsoft/SynapseML).

**Comment by miguelgfierro** [comment]
@simonzhaoms if you have time, can you try to do the changes? Andreas is out until next week, and we have an issue with the github pipeline, so we are delaying the release 1.0

**Comment by simonzhaoms** [comment]
@miguelgfierro I'll try

**Comment by simonzhaoms** [comment]
See the PR https://github.com/microsoft/recommenders/pull/1608

The 2 affected notebooks ([als_movielens.ipynb](https://github.com/microsoft/recommenders/blob/staging/examples/00_quick_start/als_movielens.ipynb) and [mmlspark_lightgbm_criteo.ipynb](https://github.com/microsoft/recommenders/blob/staging/examples/02_model_content_based_filtering/mmlspark_lightgbm_criteo.ipynb)) has been tested locally.  I am waiting for the tests to finish.
