### ISSUE TITLE
[Help Wanted] LightFM Example Notebook

### ISSUE THREAD

**Issue by drodri321** [microsoft/recommenders#1557]
### Description
LightFM.  When at prediction point the model.predict brings a problematic error which I cannot resolve.  Have spent hours doing trial-and-error but cannot understand what the issue is.

### In which platform does it happen?
Jupyter Notebook
Python 3.7

### How do we replicate the issue?
Run example notebook for LightFM.  No need to change any code, just run.

### Expected behavior (i.e. solution)
Should give a dataframe of predictions

**Comment by miguelgfierro** [comment]
good that your issue was solved, if `np.int32` didn't work it seems a problem of LightFM. 
I'll close this issue
