### ISSUE TITLE
[BUG] Errors in benchmark notebook

### ISSUE THREAD

**Issue by xlsrln** [microsoft/recommenders#1560]
### Description
When running the benchmark notebook for movielens, several errors occur.

First, the ALS model crashes on 

`recommend_k_als(model, test, train, top_k, remove_seen)
    100             (dfs_pred[DEFAULT_USER_COL] == train[DEFAULT_USER_COL])
    101             & (dfs_pred[DEFAULT_ITEM_COL] == train[DEFAULT_ITEM_COL]),
--> 102             how="outer",
    103         )` in `/content/benchmark_utils.py `

The error is `Column itemID#481 are ambiguous. It's probably because you joined several Datasets together, and some of these Datasets are the same.`

Secondly, the NCF step fails with error

`RuntimeError: tf.placeholder() is not compatible with eager execution.`

The error happens at `self.user_input = tf.compat.v1.placeholder(tf.int32, shape=[None, 1])` in `recommenders/models/ncf/ncf_singlenode.py in _create_model(self)`

### In which platform does it happen?
Google colab notebook

### How do we replicate the issue?
By running https://github.com/microsoft/recommenders/blob/main/examples/06_benchmarks/movielens.ipynb

### Expected behavior (i.e. solution)
It should run without errors

**Comment by miguelgfierro** [comment]
This looks a problem with the TF version, which version are you using?

**Comment by xlsrln** [comment]
The NCF errors indeed look like they are fixed by using tensorflow 1.

**Comment by xlsrln** [comment]
But the spark error isn't
