### ISSUE TITLE
[BUG] ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject

### ISSUE THREAD

**Issue by mokeeqian** [microsoft/recommenders#1562]
### The benchmark notebook got a Numpy error while running, like this:

```
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
```
I searched from the stackoverflow, it seems that I got the conflicted version of Numpy. I just go with the SETUP guide.

**Comment by laserprec** [comment]
A duplicate issue of #1563. I would suggest directing the conversations to #1563. Closing this issue.
