### ISSUE TITLE
[BUG] Inline Latex not rendering correctly in Notebooks

### ISSUE THREAD

**Issue by miguelgfierro** [microsoft/recommenders#1567]
### Description

The formulas in the notebooks that use inline latex code (with only one $) are not rendering. 

In nbviewer it works https://nbviewer.org/github/microsoft/recommenders/blob/staging/examples/02_model_collaborative_filtering/cornac_bivae_deep_dive.ipynb so it might be a problem with GitHub?

### How do we replicate the issue?

See https://github.com/microsoft/recommenders/blob/staging/examples/02_model_collaborative_filtering/cornac_bivae_deep_dive.ipynb or https://github.com/microsoft/recommenders/blob/staging/examples/02_model_collaborative_filtering/sar_deep_dive.ipynb

**Comment by miguelgfierro** [comment]
I found an ugly workaround, if the code was `$mxm$`, we can replace it by this
`<img src="https://render.githubusercontent.com/render/math?math=mxm">`, but obviously it would be great to have a better solution.

**Comment by miguelgfierro** [comment]
help is on its way from GitHub team. We will see this fixed soon

**Comment by MgenGlder** [comment]
This should be working now.

**Comment by miguelgfierro** [comment]
@MgenGlder it works! awesome, thanks for being so quick
