### ISSUE TITLE
[BUG] Misleading Example provided in LibffmConverter

### ISSUE THREAD

**Issue by tim5go** [microsoft/recommenders#1577]
The example provided in **LibffmConverter** is wrong
https://github.com/microsoft/recommenders/blob/27709229cdc4aa7d39ab715789f093a2d21d2661/recommenders/datasets/pandas_df_utils.py#L134-L141

The expected output for last column should be:
```python
field4 
4:6:1 
4:7:1 
4:8:1 
4:9:1
4:10:1  
```

**Comment by miguelgfierro** [comment]
thanks @tim5go for reporting this, PR sent
