### ISSUE TITLE
[ASK] What's the system requirements on Azure ML to run LightGCN?

### ISSUE THREAD

**Issue by rwforest** [microsoft/recommenders#1601]
### Description
I see it takes 47 seconds to run 50 epochs of 100k movielens in the below notebook. I am curious what's the system requirements if I want to reproduce similar results in Azure ML or Azure Databricks.

https://github.com/microsoft/recommenders/blob/main/examples/02_model_collaborative_filtering/lightgcn_deep_dive.ipynb

**Comment by miguelgfierro** [comment]
If you use a GPU environment, here you have the dependencies needed: https://github.com/microsoft/recommenders/blob/main/setup.py#L65

**Comment by rwforest** [comment]
> If you use a GPU environment, here you have the dependencies needed: https://github.com/microsoft/recommenders/blob/main/setup.py#L65

@miguelgfierro I am referring to the cluster config that can run 50 epochs in 47 seconds

**Comment by miguelgfierro** [comment]
I would recommend to try different clusters configs and measure the time, this notebook is run on a DSVM, not on AzureML or Databricks
