### ISSUE TITLE
Query about 06_benchmarks.ipynb

### ISSUE THREAD

**Issue by Ashish-Soni08** [microsoft/recommenders#1631]
### Description

In the cell 7 -> prepare training data;  for each key, what is expected?

**Comment by miguelgfierro** [comment]
The inputs are defined in https://github.com/microsoft/recommenders/blob/main/examples/06_benchmarks/benchmark_utils.py. For example:
```
def prepare_training_als(train, test):
def prepare_training_svd(train, test):
```
Then in the notebook, the code is set like the following:
```
# Data prep for training set
train = prepare_training_data.get(algo, lambda x,y:(x,y))(df_train, df_test)
```
