### ISSUE TITLE
[ASK] Whether to drop support for Python 3.6

### ISSUE THREAD

**Issue by simonzhaoms** [microsoft/recommenders#1638]
### Description

As said at [Release Python 3.6](https://www.python.org/downloads/release/python-360/), Python 3.6 has now reached end-of-life.  I wonder if we should drop the support for Python 3.6 in the near future?

### Other Comments

See also:
* [Status of Python branches](https://devguide.python.org/#status-of-python-branches)
* [Time to Say Goodbye: Python 3.6 Is End-of-Life](https://thenewstack.io/time-to-say-goodbye-python-3-6-is-end-of-life/)

**Comment by simonzhaoms** [comment]
As of March 8, 2022:
<img width="410" alt="Screen Shot 2022-03-08 at 8 49 44 AM" src="https://user-images.githubusercontent.com/43029286/157143747-5e867580-a38e-426c-af15-bee8965e5ce9.png">
Let's see what it will be in 1 month, 2 months, 6 months.

**Comment by simonzhaoms** [comment]
April 8, 2022:
![Screenshot from 2022-04-08 14-39-25](https://user-images.githubusercontent.com/43029286/162378970-8aa57fb6-d120-4512-9e4a-6e5c4dd8869b.png)

**Comment by simonzhaoms** [comment]
![Screenshot from 2022-05-11 15-14-50](https://user-images.githubusercontent.com/43029286/167791132-9f4f6c1a-9c9f-40cd-bffb-a3a28ac8a265.png)

**Comment by AdityaSoni19031997** [comment]
As of https://endoflife.date/python, Python 3.6 had already reached EOL 9 months before.

**Comment by miguelgfierro** [comment]
Right now we are not testing on 3.6, I think still most of the code works, but not 100% sure

**Comment by miguelgfierro** [comment]
![image](https://user-images.githubusercontent.com/3491412/196987283-3b14a0a1-6906-4ea3-8fc9-865abb3af97a.png)

As of Oct 2022

**Comment by miguelgfierro** [comment]
We discussed this point. 

The approach we considered is, right now we are not getting problems with 3.6, and it is used by 40%, so we can keep it for now. If we start getting dependency issues, then we can reconsider removing 3.6. 

@simonzhaoms do you like this approach, or do you think we should change it?

**Comment by simonzhaoms** [comment]
@miguelgfierro  Yeah, let's keep it for now.
