### ISSUE TITLE
[ASK] The docstring explanation for `LibffmConverter`

### ISSUE THREAD

**Issue by Tony-Feng** [microsoft/recommenders#1670]
### Description

Hello Dev Team,

In the docstring of `LibffmConverter`:
https://github.com/microsoft/recommenders/blob/fe215e9babf8f7caba025a83059445362cff0006/recommenders/datasets/pandas_df_utils.py#L112

I'm wondering if this line would be the following one instead:
```
i.e. `<field_index>:<field_feature_index>:1` or `<field_index>:<field_feature_index>:<field_feature_value>`
```

Since according to:
https://github.com/microsoft/recommenders/blob/fe215e9babf8f7caba025a83059445362cff0006/recommenders/datasets/pandas_df_utils.py#L225
The returned value is in form of `<field_index>:<field_feature_index>:<field_feature_value>` instead of  `<field_index>:<field_index>:<field_feature_value>`.

A PR https://github.com/microsoft/recommenders/pull/1669 has been made to fix this typo if applicable.

Thank you very much.

**Comment by Tony-Feng** [comment]
Hello @miguelgfierro, thanks for reviewing the PR. I'm also wondering if there would be a specific reason for selecting 1 in `<field_index>:<field_feature_index>:1` for strings? Thanks again!

**Comment by miguelgfierro** [comment]
That's just an example, you can add the value you want
