### ISSUE TITLE
[BUG] Badge icon does not show in SARplus

### ISSUE THREAD

**Issue by anargyri** [microsoft/recommenders#1679]
### Description

- https://github.com/microsoft/recommenders/tree/main/contrib/sarplus
The icon that shows the test status does not show properly.
- https://github.com/microsoft/recommenders/tree/main/contrib/sarplus#azure-synapse
JAR location is missing.

**Comment by simonzhaoms** [comment]
I think that GitHub service was somehow broken temporarily, but the test status badge is working now.
* [pysarplus downloads](https://pypi.org/project/pysarplus/#files)
* [sarplus downloads](https://search.maven.org/artifact/com.microsoft.sarplus/sarplus_2.12)
