### ISSUE TITLE
[BUG] Review LigthFM notebook and do test

### ISSUE THREAD

**Issue by miguelgfierro** [microsoft/recommenders#1700]
### Description

We don't have tests for LgithFM and there is an issue reported: https://github.com/microsoft/recommenders/pull/1651#issuecomment-1081480645

**Comment by SafetyMary** [comment]
In which platform does it happen?
Jupiter lab

How do we replicate the issue?
running the lightFM quick start notebook
https://github.com/microsoft/recommenders/blob/main/examples/02_model_hybrid/lightfm_deep_dive.ipynb

got the error on

with Timer() as test_time:
all_predictions = prepare_all_predictions(data, uid_map, iid_map,
interactions=train_interactions,
model=model1,
num_threads=NO_THREADS)

TypeError: Invalid type passed to user_ids parameter. This must be either int or np.int32 array. Type received: <class 'numpy.int64'>

System version: 3.8.13 (default, Mar 28 2022, 06:59:08) [MSC v.1916 64 bit (AMD64)]
LightFM version: 1.16

**Comment by miguelgfierro** [comment]
@SafetyMary I checked and it is working in dev. Please do this in the root folder:
```
git checkout staging
git pull origin staging
pip install -e .[dev,examples]
```
