### ISSUE TITLE
[ASK] Python version support needed

### ISSUE THREAD

**Issue by shrgupta1** [microsoft/recommenders#1724]
### Description

Hello,

I'm implementing NAML in my project and am getting the error, 'ERROR: Could not find a version that satisfies the requirement recommenders (from versions: none)ERROR: No matching distribution found for recommenders' when I tested it with Python 3.10.

What versions of Python does NAML support?

Thanks in advance!

**Comment by miguelgfierro** [comment]
the version support is `">=3.6, <3.10"`, if you need to use python 3.10 you can install from source
