### ISSUE TITLE
[BUG] Container usage from external registry 'docker.io' found cause a warning in the tests

### ISSUE THREAD

**Issue by miguelgfierro** [microsoft/recommenders#1725]
### Description

We started to get a warning that can be seen [here](https://dev.azure.com/best-practices/recommenders/_build/results?buildId=60846&view=logs&j=475df697-7465-54db-fcd2-cb9bdea8ab03&t=b7db66b6-fa35-5c82-573e-eabcb50ded02)

```
tools/docker/Dockerfile - Container usage from external registry 'docker.io' found.
##[warning]Container security analysis found 1 violations. This repo has one or more docker files having references to images from external registries. Please review https://aka.ms/containers-security-guidance to remove the reference of container images from external registries. Please reach out via teams (https://aka.ms/cssc-teams) or email (cssc@microsoft.com) for any questions or clarifications.

```
This is weird because I don't see any reference to docker.io in the code

**Comment by anargyri** [comment]
This must be because the docker file references the base images by Ubuntu and Nvidia.

**Comment by anargyri** [comment]
E.g. this https://github.com/microsoft/recommenders/blob/d4181cf1d1df6e71f7e6b202b0875bb3bd54150c/tools/docker/Dockerfile#L7

**Comment by gramhagen** [comment]
Yeah any dockerfile under Microsoft org needs to pull from first party registry not dockers registry. This impacts the Ubuntu and Nvidia images. There are a list of accepted mirrors in the linked guidance doc.

**Comment by miguelgfierro** [comment]
Here they are: https://eng.ms/docs/more/containers-secure-supply-chain/approved-images
