### ISSUE TITLE
[ASK] Training NCF with GPU is much slower than with CPU

### ISSUE THREAD

**Issue by Jannchie** [microsoft/recommenders#1734]
### Description

I'm trying [ncf_movielens](https://github.com/microsoft/recommenders/blob/main/examples/00_quick_start/ncf_movielens.ipynb) example, I found that using GPU is slower then CPU.

I added the following code to the beginning to disable the GPU:

``` python
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "-1"
```

With RTX3090, it took 357 seconds for training. GPU utilization is around 80%.
With i9-12900K, it took 121 seconds for training. Oddly, CPU usage is not high either.

### Other Comments

I would like to know, is this normal? Or, am I not configuring the GPU training correctly?

**Comment by miguelgfierro** [comment]
The reason is because your GPU is not configured properly, check that you have the right dependencies installed including CUDA and CuDNN
