### ISSUE TITLE
[FEATURE] Simplify some arguments of the evaluation

### ISSUE THREAD

**Issue by Jannchie** [microsoft/recommenders#1737]
### Description

I found that for metrics like `map_at_k`, `ndcg_at_k`, `precision_at_k`, `recall_at_k`, the `col_rating` argument seem unnecessary if the `relevancy_method` is `"top_k"`. However, the current implementation will report an error if this argument is not passed in:

```
ValueError: Missing columns in true rating DataFrame
```

### Expected behavior with the suggested feature

I think it's a bit confusing to pass in unnecessary arguments. 

A simple but dirty fix would be to change the default arguments `DEFAULT_RATING_COL` to `DEFAULT_USER_COL`.

**Comment by miguelgfierro** [comment]
@ChuyangKe can you review this?

**Comment by yueguoguo** [comment]
Perhaps another way is to use `*args` and then check the existence of rating column in `args` when `relevancy_method` is not "top_k".

**Comment by AdityaSoni19031997** [comment]
i can work on this issue, Can someone point-me to the correct file? I think the changes has to be cascaded and checked as well as multiple modules might be using these metrics? 
Thanks

**Comment by miguelgfierro** [comment]
@AdityaSoni190319 can you implement the solution proposed by Le (yueguoguo)?

metrics are here https://github.com/microsoft/recommenders/blob/main/recommenders/evaluation/python_evaluation.py

**Comment by AdityaSoni19031997** [comment]
I will work on this one. Will get back to you. It would be great to contribute to this repo for the 2nd time!

Thanks.

**Comment by AdityaSoni19031997** [comment]
@miguelgfierro I have tried to patch this fix and had run the tests for the given methods as well. LMK your feedback or any other changes needed.
