### ISSUE TITLE
[FEATURE] Is there a tutorial on how to select recommender algorithm?

### ISSUE THREAD

**Issue by wanglu2014** [microsoft/recommenders#1741]
This page is well-organized https://github.com/microsoft/recommenders, however, what tips you suggest on choose one of algorithm under what condition?

**Comment by yueguoguo** [comment]
I think it depends on many factors like
* data availability - interaction data, feature-typed data, graph data.
* problem setting - recall, ranking, etc.
* computing engine - big data platform (spark), GPU (deep learning), etc.

**Comment by wanglu2014** [comment]
> I think it depends on many factors like
> 
>     * data availability - interaction data, feature-typed data, graph data.
> 
>     * problem setting - recall, ranking, etc.
> 
>     * computing engine - big data platform (spark), GPU (deep learning), etc.

Thank you for your reply. What is your experience to choose algorithm?

**Comment by miguelgfierro** [comment]
Here we have some guidance in the description: https://github.com/microsoft/recommenders#algorithms
