### ISSUE TITLE
[FEATURE] Add time performance benchmark for functions in unit tests

### ISSUE THREAD

**Issue by simonzhaoms** [microsoft/recommenders#1750]
### Description

The idea is from [the pull request for improving the performance of `get_top_k_items()`](https://github.com/microsoft/recommenders/pull/1748#issuecomment-1156972351).  By adding time performance benchmark, we can know whether changes from a PR would affect the performance or not other than the expected correct results.

### Expected behavior with the suggested feature

I find [pytest-benchmark](https://pypi.org/project/pytest-benchmark/) can be used.  But not sure whether there are other ways.

**Comment by miguelgfierro** [comment]
Another way is to meassure the time with the Timer class https://github.com/microsoft/recommenders/blob/main/recommenders/utils/timer.py
