### ISSUE TITLE
CUDA version

### ISSUE THREAD

**Issue by SahitiCheguru** [microsoft/recommenders#1761]
### Description

Although I installed the right version of CUDA, the benchmark movielens noteebook shows: No CUDA in this machine. Maybe there is a problem with the function. 
Please refer:  pybase/system_info.py at main · miguelgfierro/pybase (github.com)
### Expected behavior (i.e. solution)
 CUDA version: CUDA Version 10.2.89

### Other Comments
This issue fixes #1758

**Comment by miguelgfierro** [comment]
fixed in https://github.com/microsoft/recommenders/pull/1758
