### ISSUE TITLE
[BUG] LightGCN: Training time discrepancy in Benchmark MovieLens notebook

### ISSUE THREAD

**Issue by SahitiCheguru** [microsoft/recommenders#1766]
### Description

LightGCN algorithm is reported to have a larger Training time than expected in the microsoft/recommenders/blob/main/examples/06_benchmarks/movielens.ipynb notebook

### Expected behavior (i.e. solution)
 Current Training time: 6129.2162s
Expected Training time: Training time: 417.1986s 

### Other Comments
This issue resolves #1758

**Comment by miguelgfierro** [comment]
Tracking a similar issue https://github.com/microsoft/recommenders/issues/1825
