### ISSUE TITLE
[BUG] Broken Link 

### ISSUE THREAD

**Issue by levalencia** [microsoft/recommenders#1786]
### Description
Readme section:

We have introduced a new way of testing our repository using [AzureML](https://azure.microsoft.com/en-us/services/machine-learning/). With AzureML we are able to distribute our tests to different machines and run them in parallel. This allows us to test our repository on a wider range of machines and provides us with a much faster test cycle. Our total computation time went from around 9h to 35min, and we were able to reduce the costs by half. See more details [here](https://github.com/microsoft/recommenders/blob/main/test/README.md).We have introduced a new way of testing our repository using [AzureML](https://azure.microsoft.com/en-us/services/machine-learning/). With AzureML we are able to distribute our tests to different machines and run them in parallel. This allows us to test our repository on a wider range of machines and provides us with a much faster test cycle. Our total computation time went from around 9h to 35min, and we were able to reduce the costs by half. See more details [here](https://github.com/microsoft/recommenders/blob/main/test/README.md).

See more details link is Broken.

**Comment by levalencia** [comment]
Actually the first link is also broken: [Recommenders 1.1.1](https://github.com/microsoft/recommenders/releases/tag/1.1.1)![Recommenders 1.1.1](https://github.com/microsoft/recommenders/releases/tag/1.1.1)!

**Comment by miguelgfierro** [comment]
This has been fixed already
