### ISSUE TITLE
[ASK] Recommendation algorithms leveraging user attributes as input

### ISSUE THREAD

**Issue by SlokomManel** [microsoft/recommenders#1813]
Hi Recommenders,
Thank you for the interesting repository. I came across `recommenders` repository very recently. I am still exploring different algorithms. I have a particular interest to recommendation algorithms leveraging or taking user attributes i.e., gender, age, occupation as input. 
### Description

In my experiments, I am exploring the impact of user attributes as side information to a recommender system algorithms. So I am looking for a number of algorithms that are available in `recommenders`. Could you please point me / direct me to all algorithms that do take user attributes as input. 

Bests,
_Manel._ 

### Comments
Please note that I have already tried Factorization machine.

**Comment by miguelgfierro** [comment]
in this table you can find a description of all algos: https://github.com/microsoft/recommenders#algorithms

For the kind of data you have, maybe you can take a look at the hybrid and content-based filtering algos
