### ISSUE TITLE
[BUG] Unable to install the repository using the generate_conda_file.py script

### ISSUE THREAD

**Issue by AthinaKyriakou** [microsoft/recommenders#1847]
### Description

Unable to install thePySpark environment of the repository when following the instructions in the [conda.md](https://github.com/microsoft/recommenders/blob/main/conda.md). In particular, when running `conda env create -f reco_pyspark.yaml` the following message appears: 

> Collecting package metadata (repodata.json): done
Solving environment: failed
ResolvePackageNotFound: 
- cornac==1.14.2
- scikit-surprise==1.1.3 

### In which platform does it happen?

MacOS

### How do we replicate the issue?

- git clone the repository
Assuming the repo is cloned as Recommenders: 
- `cd Recommenders`
- python tools/generate_conda_file.py --pyspark
- conda env create -f reco_pyspark.yaml

### Expected behavior (i.e. solution)

Successful creation of the conda environment with the needed dependencies.

### Other Comments
<img width="703" alt="Screenshot 2022-11-12 at 23 01 03" src="https://user-images.githubusercontent.com/34518449/201496436-32f6d35f-89d1-4eea-97fd-0597f1f6ad43.png">

**Comment by miguelgfierro** [comment]
the conda readme is not up to date. Please follow these steps:
```
conda create -n microsoft-rec python=3.8
pip install .[spark,examples]
```
if you want to install the latest release, you can do `pip install recommenders[spark,examples]`

**Comment by simonzhaoms** [comment]
Hi @AthinaKyriakou, I can install the PySpark environment on my Mac.
Not sure what's wrong with your system.  But please make sure that you have the right version of Python and Java, and all dependencies are installed.   See https://github.com/microsoft/recommenders/blob/main/SETUP.md#dependencies-setup

**Comment by AthinaKyriakou** [comment]
@miguelgfierro thanks for your reply! It would be nice to add in the repo README.md installation steps per operating system for the case of the local machine. 

In a new conda environment, these steps worked for me in macOS:
- `pip3 install cmake`
- `conda install -c conda-forge lightfm`
- `conda install -c conda-forge lightgbm`
- `pip3 install recommenders`

**Comment by AthinaKyriakou** [comment]
> 

@simonzhaoms thanks for your response! Unfortunately it did not work with the right version of Python and Java and all the needed dependencies.
