### ISSUE TITLE
Try to optimize SAR single node computations

### ISSUE THREAD

**Issue by miguelgfierro** [Microsoft/Recommenders#187]
Try to transform pandas to numpy and see if it works in single node.

Try to see if we can optimize in spark

**Comment by miguelgfierro** [comment]
I will take a look at this

**Comment by anargyri** [comment]
I found this, which would be good to compare against scipy sparse matrix multiplication:
https://stackoverflow.com/questions/46456396/what-is-the-fastest-way-to-multiply-with-extremely-sparse-matrix
They implement a simple multiplication without creating matrices, using numba.

**Comment by miguelgfierro** [comment]
fixed on https://github.com/Microsoft/Recommenders/pull/485
