### ISSUE TITLE
[BUG] tests/unit/recommenders/datasets/test_dataset.py fails on Windows

### ISSUE THREAD

**Issue by wutaomsft** [microsoft/recommenders#1881]
### Description
When running tests in the above file in Windows, test_maybe_download() and test_maybe_download_maybe() fail due to Linux-specific asserts

### In which platform does it happen?
Windows on Local

### How do we replicate the issue?
On Windows, run
pytest .\tests\unit\recommenders\datasets\test_dataset.py::test_maybe_download_maybe

### Other Comments
Fix incoming

**Comment by miguelgfierro** [comment]
Fixed with the PR merged
