### ISSUE TITLE
[BUG] AzureML test don't get the signal of a failed test on GitHub

### ISSUE THREAD

**Issue by miguelgfierro** [microsoft/recommenders#1884]
### Description

When a test fails on AzureML, it is not reflected on GitHub, so the badge is green. 
See: https://github.com/microsoft/recommenders/actions/runs/4224733255/jobs/7336077991

**Comment by miguelgfierro** [comment]
@pradnyeshjoshi any idea of what might be happening?

**Comment by pradnyeshjoshi** [comment]
> @pradnyeshjoshi any idea of what might be happening?

The pytest exit status code was not being correctly used in the GitHub action. #1885 should fix this.
