### ISSUE TITLE
[BUG] Question about setup instructions 

### ISSUE THREAD

**Issue by wutaomsft** [microsoft/recommenders#1902]
### Description
In README.md, it mentioned that build-essential, libpython etc are needed.  It looks these instructions are out of date.

@simonzhaoms @miguelgfierro @anargyri.  No need to change it now; I am working through the content and will provide an update. Only need your confirmation that this content is not needed.

### In which platform does it happen?
All

### How do we replicate the issue?
Ensure software required for compilation and Python libraries
       is installed.

       + On Linux this can be supported by adding:

         ```bash
         sudo apt-get install -y build-essential libpython<version>
         ``` 

         where `<version>` should be the Python version (e.g. `3.6`).

       On Windows you will need [Microsoft C++ Build Tools](https://visualstudio.microsoft.com/visual-cpp-build-tools/).

### Expected behavior (i.e. solution)
These packages are not required.  Suggesting to remove this step.

**Comment by simonzhaoms** [comment]
Yeah, I think so.

**Comment by miguelgfierro** [comment]
Agree as well

**Comment by wutaomsft** [comment]
Updated
