### ISSUE TITLE
[ASK]  My kernel dies when I fit my LightFm model from Microsoft Recommenders

### ISSUE THREAD

**Issue by konstantinos-theod** [microsoft/recommenders#1942]
### Description
I downloaded the code to run it in my Jupyter Notebook.

When I try to run the LightFm model the kernel dies (On the exact same code from the link)

This happens specifically at batch [10] when I try to fit the model

model1.fit(interactions=train_interactions, epochs=NO_EPOCHS);

I tried making a totally new virtual environment, a test kernel installing modules from scratch that didn't work either

I can't see an error message to be more specific because the Kernel just crashes

I tried it on 2 different pc's both with Windows 11 it didn't work.

I installed that latest pip , packages etc

I saw some YT videos like installing freetype and other fixes but these were general for kernels dying and didn't help

I tried editing it and making it less power consuming both on my model and the microsoft one writing using less threads and verbose(I also tried without threads and all the combinations etc) but nothing worked. model1.fit(interactions=train_interactions, epochs=NO_EPOCHS, num_threads=2, verbose=False)

**Someone tested the code on a mac computer and was able to run it though.**

Could you try downloading and running the code and see if you can fix it?Most probably it is not going to run on windows pc's.

My specs are: Intel core i5 -4460, Nvidia GTX 1060 and 32 GB's of RAM

**Comment by whatactuallyis** [comment]
You might end up installing Lightfm version 1.17. The same happened to me. Then, I tried specifically installing the 1.16 version of it which is the version in the author's notebook. It solved the kernel issue.

But I agree that version 1.17 doesn't work for the [example](https://github.com/microsoft/recommenders/blob/787ae309ec78a9b2b1f58931931cb117affc4ea9/examples/02_model_hybrid/lightfm_deep_dive.ipynb) notebook.

**Comment by konstantinos-theod** [comment]
Thank you so much it worked! Saved me a lot of time
