### ISSUE TITLE
[ASK] I can't getting start

### ISSUE THREAD

**Issue by b856741** [microsoft/recommenders#1946]
When I tried to get start and type` pip install recommenders[examples]` ,it shows: 
Building wheels for collected packages: lightfm, scikit-surprise, Flask-BasicAuth, future
  Building wheel for lightfm (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [42 lines of output]
      Compiling without OpenMP support.
      C:\ProgramData\Anaconda3\envs\recommenders\lib\site-packages\setuptools\dist.py:755: SetuptoolsDeprecationWarning: Invalid dash-separated options
      !!

              ********************************************************************************
              Usage of dash-separated 'description-file' will not be supported in future
              versions. Please use the underscore name 'description_file' instead.

              By 2023-Sep-26, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.

              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************

      !!
        opt = self.warn_dash_deprecation(opt, section)
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-39
      creating build\lib.win-amd64-cpython-39\lightfm
      copying lightfm\cross_validation.py -> build\lib.win-amd64-cpython-39\lightfm
      copying lightfm\data.py -> build\lib.win-amd64-cpython-39\lightfm
      copying lightfm\evaluation.py -> build\lib.win-amd64-cpython-39\lightfm
      copying lightfm\lightfm.py -> build\lib.win-amd64-cpython-39\lightfm
      copying lightfm\_lightfm_fast.py -> build\lib.win-amd64-cpython-39\lightfm
      copying lightfm\__init__.py -> build\lib.win-amd64-cpython-39\lightfm
      creating build\lib.win-amd64-cpython-39\lightfm\datasets
      copying lightfm\datasets\movielens.py -> build\lib.win-amd64-cpython-39\lightfm\datasets
      copying lightfm\datasets\stackexchange.py -> build\lib.win-amd64-cpython-39\lightfm\datasets
      copying lightfm\datasets\_common.py -> build\lib.win-amd64-cpython-39\lightfm\datasets
      copying lightfm\datasets\__init__.py -> build\lib.win-amd64-cpython-39\lightfm\datasets
      copying lightfm\_lightfm_fast_no_openmp.c -> build\lib.win-amd64-cpython-39\lightfm
      copying lightfm\_lightfm_fast_openmp.c -> build\lib.win-amd64-cpython-39\lightfm
      running build_ext
      building 'lightfm._lightfm_fast_no_openmp' extension
      creating build\temp.win-amd64-cpython-39
      creating build\temp.win-amd64-cpython-39\Release
      creating build\temp.win-amd64-cpython-39\Release\lightfm
      cl.exe /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\ProgramData\Anaconda3\envs\recommenders\include -IC:\ProgramData\Anaconda3\envs\recommenders\Include /Tclightfm/_lightfm_fast_no_openmp.c /Fobuild\temp.win-amd64-cpython-39\Release\lightfm/_lightfm_fast_no_openmp.obj -ffast-math -march=native
      error: command 'cl.exe' failed: None
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for lightfm
  Running setup.py clean for lightfm
  error: subprocess-exited-with-error

  × python setup.py clean did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Compiling without OpenMP support.
      C:\ProgramData\Anaconda3\envs\recommenders\lib\site-packages\setuptools\dist.py:755: SetuptoolsDeprecationWarning: Invalid dash-separated options
      !!

              ********************************************************************************
              Usage of dash-separated 'description-file' will not be supported in future
              versions. Please use the underscore name 'description_file' instead.

              By 2023-Sep-26, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.

              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************

      !!
        opt = self.warn_dash_deprecation(opt, section)
      running clean
      error: [WinError 2] 系統找不到指定的檔案。
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed cleaning build dir for lightfm
  Building wheel for scikit-surprise (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [105 lines of output]
      C:\Users\user\AppData\Local\Temp\pip-install-21zxdjc0\scikit-surprise_62954189362e4de6b574a39d547e2beb\setup.py:65: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
      !!

              ********************************************************************************
              Requirements should be satisfied by a PEP 517 installer.
              If you are using pip, you can try `pip install --use-pep517`.
              ********************************************************************************

      !!
        dist.Distribution().fetch_build_eggs(["numpy>=1.17.3"])
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-39
      creating build\lib.win-amd64-cpython-39\surprise
      copying surprise\accuracy.py -> build\lib.win-amd64-cpython-39\surprise
      copying surprise\builtin_datasets.py -> build\lib.win-amd64-cpython-39\surprise
      copying surprise\dataset.py -> build\lib.win-amd64-cpython-39\surprise
      copying surprise\dump.py -> build\lib.win-amd64-cpython-39\surprise
      copying surprise\reader.py -> build\lib.win-amd64-cpython-39\surprise
      copying surprise\trainset.py -> build\lib.win-amd64-cpython-39\surprise
      copying surprise\utils.py -> build\lib.win-amd64-cpython-39\surprise
      copying surprise\__init__.py -> build\lib.win-amd64-cpython-39\surprise
      copying surprise\__main__.py -> build\lib.win-amd64-cpython-39\surprise
      creating build\lib.win-amd64-cpython-39\surprise\model_selection
      copying surprise\model_selection\search.py -> build\lib.win-amd64-cpython-39\surprise\model_selection
      copying surprise\model_selection\split.py -> build\lib.win-amd64-cpython-39\surprise\model_selection
      copying surprise\model_selection\validation.py -> build\lib.win-amd64-cpython-39\surprise\model_selection
      copying surprise\model_selection\__init__.py -> build\lib.win-amd64-cpython-39\surprise\model_selection
      creating build\lib.win-amd64-cpython-39\surprise\prediction_algorithms
      copying surprise\prediction_algorithms\algo_base.py -> build\lib.win-amd64-cpython-39\surprise\prediction_algorithms
      copying surprise\prediction_algorithms\baseline_only.py -> build\lib.win-amd64-cpython-39\surprise\prediction_algorithms
      copying surprise\prediction_algorithms\knns.py -> build\lib.win-amd64-cpython-39\surprise\prediction_algorithms
      copying surprise\prediction_algorithms\predictions.py -> build\lib.win-amd64-cpython-39\surprise\prediction_algorithms
      copying surprise\prediction_algorithms\random_pred.py -> build\lib.win-amd64-cpython-39\surprise\prediction_algorithms
      copying surprise\prediction_algorithms\__init__.py -> build\lib.win-amd64-cpython-39\surprise\prediction_algorithms
      running egg_info
      writing scikit_surprise.egg-info\PKG-INFO
      writing dependency_links to scikit_surprise.egg-info\dependency_links.txt
      writing entry points to scikit_surprise.egg-info\entry_points.txt
      writing requirements to scikit_surprise.egg-info\requires.txt
      writing top-level names to scikit_surprise.egg-info\top_level.txt
      reading manifest file 'scikit_surprise.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      adding license file 'LICENSE.md'
      writing manifest file 'scikit_surprise.egg-info\SOURCES.txt'
      C:\ProgramData\Anaconda3\envs\recommenders\lib\site-packages\setuptools\command\build_py.py:201: _Warning: Package 'surprise.prediction_algorithms' is absent from the `packages` configuration.
      !!

              ********************************************************************************
              ############################
              # Package would be ignored #
              ############################
              Python recognizes 'surprise.prediction_algorithms' as an importable package[^1],
              but it is absent from setuptools' `packages` configuration.

              This leads to an ambiguous overall configuration. If you want to distribute this
              package, please make sure that 'surprise.prediction_algorithms' is explicitly added
              to the `packages` configuration field.

              Alternatively, you can also rely on setuptools' discovery methods
              (for example by using `find_namespace_packages(...)`/`find_namespace:`
              instead of `find_packages(...)`/`find:`).

              You can read more about "package discovery" on setuptools documentation page:

              - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html

              If you don't want 'surprise.prediction_algorithms' to be distributed and are
              already explicitly excluding 'surprise.prediction_algorithms' via
              `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
              you can try to use `exclude_package_data`, or `include-package-data=False` in
              combination with a more fine grained `package-data` configuration.

              You can read more about "package data files" on setuptools documentation page:

              - https://setuptools.pypa.io/en/latest/userguide/datafiles.html

              [^1]: For Python, any directory (with suitable naming) can be imported,
                    even if it does not contain any `.py` files.
                    On the other hand, currently there is no concept of package data
                    directory, all directories are treated like packages.
              ********************************************************************************

      !!
        check.warn(importable)
      copying surprise\similarities.c -> build\lib.win-amd64-cpython-39\surprise
      copying surprise\similarities.pyx -> build\lib.win-amd64-cpython-39\surprise
      copying surprise\prediction_algorithms\co_clustering.c -> build\lib.win-amd64-cpython-39\surprise\prediction_algorithms
      copying surprise\prediction_algorithms\matrix_factorization.c -> build\lib.win-amd64-cpython-39\surprise\prediction_algorithms
      copying surprise\prediction_algorithms\optimize_baselines.c -> build\lib.win-amd64-cpython-39\surprise\prediction_algorithms
      copying surprise\prediction_algorithms\slope_one.c -> build\lib.win-amd64-cpython-39\surprise\prediction_algorithms
      copying surprise\prediction_algorithms\co_clustering.pyx -> build\lib.win-amd64-cpython-39\surprise\prediction_algorithms
      copying surprise\prediction_algorithms\matrix_factorization.pyx -> build\lib.win-amd64-cpython-39\surprise\prediction_algorithms
      copying surprise\prediction_algorithms\optimize_baselines.pyx -> build\lib.win-amd64-cpython-39\surprise\prediction_algorithms
      copying surprise\prediction_algorithms\slope_one.pyx -> build\lib.win-amd64-cpython-39\surprise\prediction_algorithms
      running build_ext
      building 'surprise.similarities' extension
      creating build\temp.win-amd64-cpython-39
      creating build\temp.win-amd64-cpython-39\Release
      creating build\temp.win-amd64-cpython-39\Release\surprise
      cl.exe /c /nologo /O2 /W3 /GL /DNDEBUG /MD -Ic:\users\user\appdata\local\temp\pip-install-21zxdjc0\scikit-surprise_62954189362e4de6b574a39d547e2beb\.eggs\numpy-1.25.0-py3.9-win-amd64.egg\numpy\core\include -IC:\ProgramData\Anaconda3\envs\recommenders\include -IC:\ProgramData\Anaconda3\envs\recommenders\Include /Tcsurprise/similarities.c /Fobuild\temp.win-amd64-cpython-39\Release\surprise/similarities.obj
      error: command 'cl.exe' failed: None
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for scikit-surprise
  Running setup.py clean for scikit-surprise
  Building wheel for Flask-BasicAuth (setup.py) ... done
  Created wheel for Flask-BasicAuth: filename=Flask_BasicAuth-0.2.0-py3-none-any.whl size=4261 sha256=26d58eed63f5d93cebf12ba5cae3cd70b66550a7f8cf1c48910e45d8a1d979d4
  Stored in directory: c:\users\user\appdata\local\pip\cache\wheels\d4\5a\db\e442580c22be34f69e537448832d7e1ee5a9c5adb63ace30bf
  Building wheel for future (setup.py) ... done
  Created wheel for future: filename=future-0.18.3-py3-none-any.whl size=492055 sha256=b790230f9e1ada98b146c71846ea47735114d1ba36a3e0cce703776203e098cd
  Stored in directory: c:\users\user\appdata\local\pip\cache\wheels\bf\5d\6a\2e53874f7ec4e2bede522385439531fafec8fafe005b5c3d1b
Successfully built Flask-BasicAuth future
Failed to build lightfm scikit-surprise
ERROR: Could not build wheels for lightfm, scikit-surprise, which is required to install pyproject.toml-based projects
What should I do ?

**Comment by miguelgfierro** [comment]
It seems that it is failing with surprise and lightfm. Here some ideas to solve the issue:
- Try to install some of the latest versions of surprise and lightfm, and then install recommenders
- Move out of Windows and try linux, you can use WSL. All the tests we have are in Linux, we do not support Windows at the moment

**Comment by Wonderdch** [comment]
> It seems that it is failing with surprise and lightfm. Here some ideas to solve the issue:
> 
> * Try to install some of the latest versions of surprise and lightfm, and then install recommenders
> * Move out of Windows and try linux, you can use WSL. All the tests we have are in Linux, we do not support Windows at the moment

I get this work by first install surprise and lightfm with conda-forge, and then install recommenders. 😣

```
conda install -c conda-forge scikit-surprise
conda install -c conda-forge lightfm

pip install recommenders[examples]
```
