### ISSUE TITLE
own train-test data split 

### ISSUE THREAD

**Issue by riyaj8888** [microsoft/recommenders#1964]
i am following this notebook https://github.com/microsoft/recommenders/blob/main/examples/02_model_collaborative_filtering/ncf_deep_dive.ipynb
but i dont have any timestamp related column in my dataset . i have created train-test split externally and want to feed it to NCFDataset class but i m getting "Empty file error".

any way to solve this

**Comment by miguelgfierro** [comment]
it seems that you are either not linking the right file or your file doesn't have data. 

The best way to debug your code is to start from the current notebook, make sure it works and then replace the original dataset with your one trying to change as less as possible. For example, what I would do is to change everything except the timestamp, or use a constant timestamp. Then keep iterating until you have something working.
