### ISSUE TITLE
SAR single node adds columns to the train and test dataframes

### ISSUE THREAD

**Issue by loomlike** [Microsoft/Recommenders#204]
SAR single node implementation adds
 'exponential' and 'rating_exponential' columns to the train data in fit(), and
'hashedUsers' column to the test data in recommend_k_items() or
hashedUsers' and 'hashedItems' columns in predict().

This would not be an expected behavior, especially when one uses/compares multiple models together by 're'-using the same set of train and test data to those models.

SAR pySpark implementation generates a copy of input dataframe and adds necessary columns to that when fit(), which we should do the same thing for the single node implementation.

**Comment by miguelgfierro** [comment]
@gramhagen do you know if this behavior is still happening?

**Comment by gramhagen** [comment]
no this has been fixed in staging by #387
