### ISSUE TITLE
SAR to set remove_seen flag later

### ISSUE THREAD

**Issue by loomlike** [microsoft/recommenders#208]
Would be nice if I can set remove_seen flag later too (or pass as an arg for predict / recommend).
remove_seen affects only at prediction / recommendation phase, which does filter out items when generating the results.

I wanted to test both including vs. excluding seen-items results, and had to re-train the model just for that because the current implementation we cannot change it after the model initialization.

**Comment by miguelgfierro** [comment]
@loomlike is this still needed?

FYI @gramhagen

**Comment by gramhagen** [comment]
I recommend keeping it in init, the latest update to sar single node removes seen items during fit (since the final score is already calculated there). and we stay consistent with als for better or worse.

**Comment by anargyri** [comment]
> I recommend keeping it in init, the latest update to sar single node removes seen items during fit (since the final score is already calculated there). and we stay consistent with als for better or worse.

I wouldn't be worried so much about being consistent with ALS. It seems to go against the single responsibility principle if you specify this flag during training. I would think more about what are possible scenarios in practice. For example, maybe I want to test the same model both using recommendations that include seen items and recommendations that don't (I don't know a priori which of the two my customers will prefer).

**Comment by loomlike** [comment]
+1 to @anargyri's point. Does remove_seen flag affect heavily on the training time?

Alternatively, a user can use predict() by feeding all user-item pairs as the test df, where the user can remove seen_items when preparing the df.

**Comment by gramhagen** [comment]
I believe a more flexible implementation than what is done currently would only compute the user-item affinity and item-item similarity matrices as part of the fit method. The recommend method could be responsible for taking a subset of the user-item affinity for the test users and doing the matrix multiplication with item-item similarity and ranking for recommendation. At that point you could specify whether to remove seen items which could have been recorded during training or derived from the user-affinity matrix. Or as @loomlike suggests, provide the specific user-item pairs for calculation which would just be the dot product of one user vector and one item similarity column. It should also be easier to distribute the predict / recommendation calculation with this approach.

**Comment by gramhagen** [comment]
this has been addressed by #617
