### ISSUE TITLE
Extract text based features for items with text based meta data

### ISSUE THREAD

**Issue by dciborow** [Microsoft/Recommenders#274]
### *What* is affected by this bug?
*For example:*
1. *Run of a notebook.*
2. *Unit tests.*
3. ...

### *Where* on the platform does it happen?
*For example:*
1. *Azure Data Science Virtual Machine.*
2. *Azure Databricks.*
3. *Other platforms.*

### *How* do we replicate the issue?
(*Please be specific as possible. Use dashes (-) or numbers (1.) to create a list of steps.*)
*For example:*
1. *Create a conda environment for pyspark*
2. *Run unit test `test_sar_pyspark.py` with `pytest -m 'spark'`*
3. ...

### Expected behavior (i.e. solution)
*For example:*
1. The tests for SAR PySpark should pass successfully.

### Other Comments

**Comment by miguelgfierro** [comment]
DKN can do this, closing for now. Feel free to reopen
