### ISSUE TITLE
Create a live benchmark

### ISSUE THREAD

**Issue by miguelgfierro** [Microsoft/Recommenders#282]
### *What* is affected by this bug?
Every night, when we execute the integration tests, we should also generate a benchmark table with the latest results. 

In order to show this table in the readme, we can generate a svg image and link it in the readme, this way we will be able to have a live benchmark that is computed every day. 

The use of svg for showing changing images is used by VSTS, travis and others with the status badges. The idea of creating a live benchmark cames from there.

### *Where* on the platform does it happen?
1. *Azure Data Science Virtual Machine.*

### Expected behavior (i.e. solution)
To have a SVG image linked to the repo instead of a static benchmark

**Comment by yueguoguo** [comment]
Will revisit this after hyperopt is done

**Comment by miguelgfierro** [comment]
FYI @bethz @heatherbshapiro @danielsc I think it would be very interesting to do a live benchmark with AzureML. The work we are doing with the test could be extended to generate a SVG with a benchmark  table of each algorithm. Then, the benchmark will always be computed with the latest code. 

I haven't seen this anywhere
