### ISSUE TITLE
SAR+ Requires Crossjoin

### ISSUE THREAD

**Issue by dciborow** [Microsoft/Recommenders#296]
It seem's SAR+ requires cross join be performed. This operation scales very poorly in spark, which is why you have to turn it on specifically. Can this be optimized out? 
(It's been awhile, but is this a spot where you don't really need the whole product matrix, but really just an upper triangular section? if so I think that operation would perform much better...)

**Comment by miguelgfierro** [comment]
closing for now, @eisber feel free to reopen if needed
