### ISSUE TITLE
SAR on GPU

### ISSUE THREAD

**Issue by anargyri** [microsoft/recommenders#298]
Add a new algorithm that computes SAR on a GPU. Maybe use Gilbert's code from blads_sar repo?

**Comment by miguelgfierro** [comment]
hey @anargyri @eisber @yueguoguo, is anyone working on this at the moment? if not I would like to take the task when I come back in January

**Comment by miguelgfierro** [comment]
From Max:

You could try using GPU for block-matrix multiplication to scale SAR, i.e. if you have two large matrices A and B which cannot fit into memory, you can split them up into blocks, perform multiplication on GPU by batching through the blocks and then combining the results to disc again. I can point you to pyTorch and TensorFlow SAR implementations but from what I recall they were slower than CPU for anything over 1M records.
​

Perhaps something like this https://github.com/bamos/block but I haven't tried any of these libraries recently.

**Comment by miguelgfierro** [comment]
https://pandas.pydata.org/pandas-docs/stable/enhancingperf.html

**Comment by miguelgfierro** [comment]
closing because stale issue, feel free to reopen if needed
