### ISSUE TITLE
Create TOC in ALS/SVD notebooks

### ISSUE THREAD

**Issue by yueguoguo** [microsoft/recommenders#312]
### *What* is affected by this bug?
There may be different settings for recommendation problems in certain algorithms. E.g., ALS can be used for predicting explicit ratings or recommend items with implicit feedbacks. These two different scenarios should be made clear in the notebooks. 

### *Where* on the platform does it happen?
Platform independent. 

### *How* do we replicate the issue?
Run the ALS / SVD notebooks. 

### Expected behavior (i.e. solution)
Add a table of content (TOC) to elaborate. 

### Other Comments

**Comment by miguelgfierro** [comment]
@yueguoguo is this still needed?
