### ISSUE TITLE
Create Surprise quickstart notebook

### ISSUE THREAD

**Issue by yueguoguo** [microsoft/recommenders#336]
### *What* is affected by this bug?
A quickstart notebook can eliminate the irrelevant codes that may make run of the notebook unexpectedly long in the benchmark.

**Comment by miguelgfierro** [comment]
do we still want to do this? @yueguoguo an open question, should all algos have quick start and deep dive?

**Comment by miguelgfierro** [comment]
closing because stale issue, feel free to reopen if needed
