### ISSUE TITLE
Benchmark methodology

### ISSUE THREAD

**Issue by WessZumino** [Microsoft/Recommenders#337]
I am currently benchmarking the RBM and compare it with the benchmarks reported in the master branch table. I know that @yueguoguo has been working on a new benchmark table, but I will refer to the one in the master branch in what follows. 

I think it would be important to specify how the numbers in the benchmark table have been obtained, maybe in a notebook if not directly in the Readme file. I understand that the hyper parameters are not optimal, in the sense that they have not been obtained through an extensive search. Nevertheless, my first question as a user would be: how to interpret and compare those numbers? 

Are the reported metrics referring to maximum efficiency (given a set of parameters)? 
Let me be more explicit with an example: consider the movielens 1m dataset. All the 3 SAR algos achieve the same metrics but in different times. Are those values the best achievable metrics? Let's say that instead of running SAR CPU for 5 s I run it for 10, will the accuracy be the same or will it increase? 

Usually, when I need to compare different Neural network topologies, this will be my main criteria. 
This issue becomes more important the moment I want to compare SAR and ALS, or any other algo. 
I would like to know which one is more precise. From the table it looks like SAR is better, but it is not clear a priori if running ALS longer will lead to a better result. 

Also, I find strange that the evaluation metrics seems to get worst with increasing system size. This is a bit counterintuitive and I am currently looking into this.

It would be nice to know your thoughts :)

**Comment by miguelgfierro** [comment]
this was already discussed, we are working at the moment on adding in the benchmark the new algos: #464. Closing for now, feel free to open in case it is needed
