### ISSUE TITLE
Add list of contributors

### ISSUE THREAD

**Issue by gramhagen** [Microsoft/Recommenders#360]
Add document(s) to list contributors and add instructions for contributors to add their name / contact info to CONTRIBUTING.md

Additionally should we implement a Codeowners file? 
- https://help.github.com/articles/about-codeowners/

**Comment by maxkazmsft** [comment]
Is this a duplicate of https://github.com/Microsoft/Recommenders/pull/362?

**Comment by gramhagen** [comment]
yes, I think we both added this after a conversation early on, we can close this
