### ISSUE TITLE
Implement scalable SAR algos: PySpark and SAR+

### ISSUE THREAD

**Issue by yueguoguo** [microsoft/recommenders#364]
SAR+ and PySpark SAR are in the `experimental` branch. I found them very needed in many real-world use cases when data sizes are large. 

Do we want to make them great again 😃 ? @maxkazmsft @eisber

**Comment by miguelgfierro** [comment]
FYI @nikhilrj Markus and Scott are looking at this

**Comment by gramhagen** [comment]
Now that there's a spark implementation in MML Spark I think we can close this. Future work to improve speed / scalability can be made there. Let me know if anyone thinks there are other implementations we should be focusing on here.

**Comment by nikhilrj** [comment]
@gramhagen sounds good. Let's keep this issue open and re-purpose it: we should aim to have a notebook showcasing MMLSpark SAR in our repo and not necessarily have implementations in our repo.

**Comment by miguelgfierro** [comment]
added in #955
