### ISSUE TITLE
User-friendly guidance on data preparation

### ISSUE THREAD

**Issue by yueguoguo** [Microsoft/Recommenders#375]
It takes time in real-world problems that user feel frustrated about preparing data for recommender algorithms. It would be good to have notebooks to detail that.

**Comment by WessZumino** [comment]
Totally agree! In the RBM deepdive I have used some space to explain the logic behind the data splitting and preparation for movielens. However, this is quite a simple scenario as the data are already given in the correct format. It would be good to find a real case scenario in which more work is needed for data preparation

**Comment by atimesastudios** [comment]
May we please also have guidance for FFM dataset preparation to feed xDeepFM, especially with integrating customer and item features into the input dataset along with implicit/explicit feedback.

**Comment by yueguoguo** [comment]
@atimesastudios yea we do have some preparation functions for this
* The `negative_feedback_sampler` (see [here](https://github.com/microsoft/recommenders/blob/f53d2639b0f41348a95aeaaa6da5514039e14c2a/reco_utils/dataset/pandas_df_utils.py#L262)) is the one that samples negative feedback when data is about implicit feedback.
* The `LibffmConverter` (see [here](https://github.com/microsoft/recommenders/blob/f53d2639b0f41348a95aeaaa6da5514039e14c2a/reco_utils/dataset/pandas_df_utils.py#L86)) is the one that performs libffm format conversion from feature data set.
