### ISSUE TITLE
Baseline naive recommender (kind of zero-rule classifier)

### ISSUE THREAD

**Issue by loomlike** [Microsoft/Recommenders#380]
Even evaluation metrics help to understand how well a model performs, it is still good to have a baseline to compare with, e.g. to see if the model is doing better than a random or a naive rule.

Estimating the baseline performance would be different for each problems as well as its business goal, but we can provide an example of the movie recommendation scenario at least.

I'm creating a notebook describing about this topic, where I use 'avg rating for each user' as the baseline of rating prediction and 'top-k popular' for recommendation.

Any ideas /suggestions are welcome!

**Comment by yueguoguo** [comment]
This is very very useful. FYI Surprise has some implementations on this - see [here](https://surprise.readthedocs.io/en/stable/basic_algorithms.html).

**Comment by yueguoguo** [comment]
#382
