### ISSUE TITLE
showcase Real Time Bidding scenario with data compression

### ISSUE THREAD

**Issue by maxkazmsft** [microsoft/recommenders#386]
This work item is for notebook creation for a real time bidding scenario of binary classification (click/no click), where a user interacts with a certain website a number of times. We could use a SAR algorithm to showcase ranking of websites or links for the user.

The **KEY IDEA** is to illustrate data compression, by compressing duplicate rows and ignoring the Timestamp column (this would showcase how SAR can be used without the Affinity calculation).

More specifically, say user UA viewed item IA 10 times and clicked on the item 4 times. We would have 10 rows in the dataset: 6 rows with dependent variable set to 0 and 4 rows with dependent variable set to 1. We can "compress" this data by recording just one row 
UA, IA, 4/10 
and use 4/10 as the weight in SAR.

Moreover, say there are items IA, IB and IC  each observed nA, nB and nC times across all users. We can further balance the dataset by considering inverse weights like N/nA, N/nB, etc, where N=nA+nB+nC. Or we can balance individual user-item interactions - in this example additional weight factor for user UA interacting with IA would be N/10

TODO: find a public dataset for this

**Comment by sharatsc** [comment]
Can we use Criteo dataset
http://ailab.criteo.com/ctr-at-scale-using-open-technologies/ ?

**Comment by maxkazmsft** [comment]
I don't think so... SAR needs a user ID and an item ID. We'd have to tie back Criteo feature values to user and item IDs and I don't think we have that mapping, nor do we know which set of features are from the users and which are from the items...
