### ISSUE TITLE
Add an experimentation example with AML

### ISSUE THREAD

**Issue by miguelgfierro** [Microsoft/Recommenders#424]
This article https://azure.microsoft.com/en-gb/blog/experimentation-using-azure-machine-learning/ from @danielsc can be used as a base

**Comment by loomlike** [comment]
I'm working on AML + hyperdrive for wide-deep, excluding auto-ml (don't think we --recommender-- can use automl). Basically I have two notebooks around 75% ready, one for wide-deep and the other one for aml+hyperdrive for wide-deep tuning

**Comment by miguelgfierro** [comment]
closing this since it has been solved on #448 and on #546
