### ISSUE TITLE
Add Vowpal Wabbit based recommender example

### ISSUE THREAD

**Issue by nikhilrj** [Microsoft/Recommenders#426]
### *What* is affected by this issue?
Investigate adding a VW based example for news recommendations or movies recommendations w/ item features

### In *which* platform does it happen?
DSVM / Databricks

### Expected behavior (i.e. solution)
I have an end to end example of training / deploying / operationalizing a recommender system using VW.

**Comment by gramhagen** [comment]
dropping commits into gramhagen/vw_example branch

for now I'm showing a few different approaches using VW (linear regression, multinomial logistic regression, and two matrix factorization approaches)

need to add some more text to the notebook under 02_model/vowpal_wabbit_deep_dive.ipynb, but interim suggestions are welcome

**Comment by nikhilrj** [comment]
Fixed with #452 - awesome work Scott!
