### ISSUE TITLE
Specify the local and DSVM os requirements.

### ISSUE THREAD

**Issue by ehrlinger** [Microsoft/Recommenders#437]
Should there be a prequisite that explicitly states the assumed OS for operations?

In both the readme, and the setup documents, you are assuming a Linux based OS... as far as I can tell, but never explicitly state that.

This was discovered in part because the command to run script to generate the conda file

'./scripts/generate_conda_file.sh'

will not run on a windows machine.

**Comment by yueguoguo** [comment]
Resolved in #439
