### ISSUE TITLE
Bug on hypertune_spark_deep_dive notebook dataload

### ISSUE THREAD

**Issue by loomlike** [Microsoft/Recommenders#441]
Movielens dataloader uses default column names in the repo. To use custom names, should pass either header or schema.

### *What* is affected by this bug?
* *Run of a notebook.*

### In *which* platform does it happen?
* Spark

### *How* do we replicate the issue?
* Run the notebook

### Expected behavior (i.e. solution)
Easily fix by changing the data loading line as:
`load_spark_df(spark, size='100k', header=(COL_USER, COL_ITEM, COL_RATING))`

**Comment by loomlike** [comment]
Also need to check if we have a test function for this notebook or we intentionally not added the test for this? @yueguoguo @miguelgfierro

**Comment by yueguoguo** [comment]
Fixed in #442
