### ISSUE TITLE
ModuleNotFoundError: No module named 'azure.datalake'

### ISSUE THREAD

**Issue by danielsc** [Microsoft/Recommenders#443]
### *What* is affected by this bug?
Installation of conda_bare.yaml environment succeeds, but papermill doesn't work with the environment as it is created.

### In *which* platform does it happen?
ProductName:	Mac OS X
ProductVersion: 10.14.2
BuildVersion: 18C54

### *How* do we replicate the issue?
```
$ ./scripts/generate_conda_file.sh
$ conda env create -n bare -f conda_bare.yaml --quiet 
$ conda activate bare
$ python
Python 3.6.7 | packaged by conda-forge | (default, Nov 20 2018, 18:37:09) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import papermill
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/danielsc/.azureml/envs/simple/lib/python3.6/site-packages/papermill/__init__.py", line 8, in <module>
    from .api import display, record, read_notebook, read_notebooks
  File "/Users/danielsc/.azureml/envs/simple/lib/python3.6/site-packages/papermill/api.py", line 17, in <module>
    from .iorw import load_notebook_node, list_notebook_files
  File "/Users/danielsc/.azureml/envs/simple/lib/python3.6/site-packages/papermill/iorw.py", line 20, in <module>
    from .adl import ADL
  File "/Users/danielsc/.azureml/envs/simple/lib/python3.6/site-packages/papermill/adl.py", line 2, in <module>
    from azure.datalake.store import core, lib
ModuleNotFoundError: No module named 'azure.datalake'
>>> 
```
### Expected behavior (i.e. solution)
This appears to be caused by pinning scikit-learn==0.19.1. If I replace that with scikit-learn>=0.19.1, then papermill imports fine.

**Comment by yueguoguo** [comment]
@danielsc it looks like when importing the module, it is from the conda env of `/Users/danielsc/.azureml/envs/simple/` instead of `bare`. Not sure if there is any issue in installing or activating the conda env.

**Comment by danielsc** [comment]
It seems, there are currently some issues with the some azure packages on MacOS when running Python 3.6 -- I see the same issues with Azure Machine Learning. Python 3.7 works without issues. Will keep this Issue posted.

**Comment by danielsc** [comment]
Apparently, I have been hitting this conda issue: https://github.com/conda/conda/issues/7173
The resolution is to `rm -rf ~/.local/lib/python3.6`
