### ISSUE TITLE
Add the metric AUC 

### ISSUE THREAD

**Issue by miguelgfierro** [Microsoft/Recommenders#445]
This can be used by any algo that implemented regression metrics

**Comment by yueguoguo** [comment]
To clarify, AUC is meant for binary classification, right? Probably this would be useful to the content-based algorithms for predicting hit/not-hit?

**Comment by miguelgfierro** [comment]
yes, that's exactly the reason. It was used in xDeepFM

**Comment by miguelgfierro** [comment]
Metrics to implement:
- limited AUC
- average AUC
- direct AUC from sklearn
