### ISSUE TITLE
Create a new devops agent that is public so external people can see the results of the tests

### ISSUE THREAD

**Issue by miguelgfierro** [microsoft/recommenders#449]
### *What* is affected by this bug?
Right now, external developers can't see why the tests are failing when they do a PR. 

### In *which* platform does it happen?
*For example:*
* *Azure Data Science Virtual Machine.*

### Expected behavior (i.e. solution)
we have to create a new agent, start the pipeline there and make the agent public

**Comment by miguelgfierro** [comment]
related to https://github.com/Microsoft/Recommenders/issues/450

**Comment by bethz** [comment]
Hey Folks, I'm ramping on DevOps. So far, I created a test DevOps pipeline to kick the tires and created a dummy pipeline off Recommenders.  I exported some of the existing tests, started setup and met with Jordan Edwards to discuss some of his plans .  I am doing a little more investigation to understand how to best integrate with AzureML.   Yea, and some more ramping on AzureML too....

**Comment by bethz** [comment]
Update: I'm working with Aimhin and others on DevOps on a generalizable DevOps solution that we can clone and use for subsequent projects. I've also met with the Forecasting team about plans for DevOps.  The great news is that the DevOps team is developing new pipeline tasks that are advantageous for AML.  This includes tasks like use Python 3.6, Identify notebooks to test, copy scripts to artifacts, Azureml-infra-CI, AML Model Deploy, AML Model Register and more. All great additions and tasks we want to consume.  But, it's a couple of more weeks, until those are ready.  Here's what I'm working on while that's going on:
- I'm working with the DevOps team on providing inputs on their task development, I'll also be a good tester for their rough, initial releases
- Subscription - I'm sorting out how to handle the subscription as when we make devops public we want to make good choices re: subscription iimplication
- As this will be public, I'm also investigating issues around how we should think about that.

**Comment by miguelgfierro** [comment]
this is fixed
