### ISSUE TITLE
Nightly build failed

### ISSUE THREAD

**Issue by yueguoguo** [Microsoft/Recommenders#454]
### *What* is affected by this bug?
Nightly build on staging branch

### In *which* platform does it happen?
The DevOps machine.

### *How* do we replicate the issue?
![image](https://user-images.githubusercontent.com/1726448/51816816-5043b780-2303-11e9-9f8e-9a2629c24843.png)

### Expected behavior (i.e. solution)
Successful pass.

### Other Comments
Checking the failure details, it looks like some issue with fast ai notebook.

**Comment by yueguoguo** [comment]
It looks like ncf testing and fast ai testing related. @danielsc probably you also want to take a look.

**Comment by miguelgfierro** [comment]
I'm working on it on this https://github.com/Microsoft/Recommenders/tree/bug/test_smoke
