### ISSUE TITLE
Add more OS implementations of FMs

### ISSUE THREAD

**Issue by anargyri** [microsoft/recommenders#456]
There are a couple of external libraries for Factorization Machines that we could consider importing to the repo.

- Scala version https://github.com/wzhe06/CTRmodel
Not only FMs. Also it requires an implicit data format.
- Python version https://github.com/ibayer/fastFM
Supports several optimization algos.

**Comment by miguelgfierro** [comment]
added a new one here https://github.com/microsoft/recommenders/pull/909
