### ISSUE TITLE
Add movielens 1M benchmark results of the new algos

### ISSUE THREAD

**Issue by miguelgfierro** [Microsoft/Recommenders#464]
### *What* is affected by this bug?
We have results for SAR, ALS and SVD in a table in the readme, we should add the rest of the algos.

**Comment by gramhagen** [comment]
This should be for 1M dataset? That's at least what the text in the README says, if that's not right I can correct that.

**Comment by miguelgfierro** [comment]
oh good catch, I'll rename the title

**Comment by miguelgfierro** [comment]
I'm working on changing the benchmark notebook. As of now it is just running the notebooks with papermill and parsing the results. However, the data splits are not the same across all notebooks. I will remake it to have more consistency

**Comment by miguelgfierro** [comment]
Progress, code finished and metrics checked:
- [ ] SVD
- [ ] ALS
- [ ] SAR
- [ ] fastai
- [ ] ncf
- [ ] rbm

**Comment by miguelgfierro** [comment]
FastAI is giving some weird metrics:
```
Ranking metrics: 
{
    "MAP": 213457.64543650797,
    "Precision@k": 25008.0,
    "Recall@k": 10.0,
    "nDCG@k": 25008.00000005573
}
```

**Comment by miguelgfierro** [comment]
fixed with https://github.com/Microsoft/Recommenders/pull/715
