### ISSUE TITLE
NFC deep dive notebook tests with papermill takes much longer than the notebook execution

### ISSUE THREAD

**Issue by miguelgfierro** [Microsoft/Recommenders#466]
### *What* is affected by this bug?
With 1 epoch and batch size of 1024, the notebook can be executed in around 3 min. However, if we execute the same notebook and parameters through papermill, the time is much higher >30min.

### In *which* platform does it happen?
* *Azure Data Science Virtual Machine.*

### Expected behavior (i.e. solution)
Papermill should take just slightly more that the actual notebook, not minutes

**Comment by yueguoguo** [comment]
This is interesting 🤓

**Comment by miguelgfierro** [comment]
fixed on https://github.com/Microsoft/Recommenders/pull/463
