### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by miguelgfierro** [Microsoft/Recommenders#474]
We have to update the README for the new algos that are in the repo. We also have to update the benchmark results.

@gramhagen could you do VW?

I will do FastAI and NCF

The list of the new algos that we have is:
- [x]  VW
- [x]  NCF
- [x]  FastAI
- [x]  xDeepFM
- [x]  DKN
- [x]  RBM

**Comment by miguelgfierro** [comment]
@nikhilrj I was looking at the main readme and we don't list in the front page all the algos that we have. I think this is something that the user will like to see quickly. 

What are your thoughts on this? what would be a good way to show the algos more clearly?

**Comment by anargyri** [comment]
I already did that in a new PR.

**Comment by gramhagen** [comment]
The 02_models/README is update with VW, are you looking for results that can be read in from the comparison notebook and put into the main /README?

**Comment by nikhilrj** [comment]
> @nikhilrj I was looking at the main readme and we don't list in the front page all the algos that we have. I think this is something that the user will like to see quickly.
> 
> What are your thoughts on this? what would be a good way to show the algos more clearly?

Agreed. Maybe let's add an Algorithms section which includes a table that gives a 1 sentence description of each algorithm and which env it supports? Alternatively this info could be another column of the benchmark table.

**Comment by yueguoguo** [comment]
> Agreed. Maybe let's add an Algorithms section which includes a table that gives a 1 sentence description of each algorithm and which env it supports? Alternatively this info could be another column of the benchmark table.

We may also want to make the table look more qualitative instead of quantitative since we want the repo to be non-opinionated. In addition to a one-sentence description, pros and cons can also be good things to have.

**Comment by miguelgfierro** [comment]
good suggestion, I remember an ask for Gianluca and other was to give a guidance on what recommendation algorithm to use. A recommendation about recommendation :-)

**Comment by anargyri** [comment]
> > Agreed. Maybe let's add an Algorithms section which includes a table that gives a 1 sentence description of each algorithm and which env it supports? Alternatively this info could be another column of the benchmark table.
> 
> We may also want to make the table look more qualitative instead of quantitative since we want the repo to be non-opinionated. In addition to a one-sentence description, pros and cons, use case scenarios, etc. can also be good things to have.

This is a good point. When updating the Readme, I wrote something like "xDeepFM, good for CTR prediction, works on python + GPU + TF". We could structure this info a bit better e.g. by using a few columns for use case, platform etc.
