### ISSUE TITLE
Proper way to reference Azure ML Service

### ISSUE THREAD

**Issue by bethz** [Microsoft/Recommenders#483]
Confirm the proper way to reference Azure ML Service, is it:
- Azure ML
- AML

This will affect docs, scripts, notebooks, etc.

**Comment by bethz** [comment]
Update: there have been a number of emails on this topic. AML is definitely not recommended for use.  Currently finalizing what we can use.

**Comment by miguelgfierro** [comment]
hey @bethz any news on this?

**Comment by bethz** [comment]
A few things:
- AzureML should NOT be called AML. Please do NOT use AML in anything public facing documentation.
- It is suggested to introduce AzureML as an abbreviation in any document where you use it, e.g.
                      “This notebook shows how to use Azure Machine Learning services (AzureML) to …..”

Then you can use AzureML to refer to “Azure Machine Learning services” whenever you want.  This explicitly differentiates it from Azure Machine Learning Studio, for instance, which also has experiments, etc.
