### ISSUE TITLE
Impression_id not used in DeepRec

### ISSUE THREAD

**Issue by anargyri** [microsoft/recommenders#484]
https://github.com/Microsoft/Recommenders/blob/395ef543433ddbcc68a3ff554af25bf0e38a5f89/reco_utils/recommender/deeprec/IO/iterator.py#L76

I don't see the impression ids being passed when loading from file. Are they obsolete and should they be removed?

**Comment by danyang-liu** [comment]
We use impression id to compute group metrics like: NDCG, group-auc in DKN.
