### ISSUE TITLE
Add support for Windows in getting started 

### ISSUE THREAD

**Issue by heatherbshapiro** [Microsoft/Recommenders#491]
The current steps in the README.md will not work for Windows users unless they use git bash or something similar. Specifically, the line, `./scripts/generate_conda_file.sh` will not work.

There are [docs](https://www.howtogeek.com/249966/how-to-install-and-use-the-linux-bash-shell-on-windows-10/) on how to install the Linux bash shell on Windows that might be helpful or we can just point them to the git bash/ cygwin

**Comment by nikhilrj** [comment]
+1 to Windows support in general. 

@miguelgfierro do we have any dependencies in the repo that don't work on Windows? We'd need to add testing in a Windows environment as well.

**Comment by miguelgfierro** [comment]
There will probably be dependencies that won't work and installation problems when porting everything to Windows. In general, it is more difficult than linux. 

We plan to change the generate_conda_file script to a python file, so the installation can be done on different operating systems https://github.com/Microsoft/Recommenders/issues/492. 

We have in the backlog to add a pipeline for Databricks https://github.com/Microsoft/Recommenders/issues/432, I would prioritize this before doing the windows work, since we have a lot of customers on this platform.

**Comment by heatherbshapiro** [comment]
In the short term, maybe we could just call out in the readme that a user can use Git Bash on windows?

**Comment by nikhilrj** [comment]
Unforuntately using some flavor of Git Bash on Windows won't fully solve the problem: there's a few notebooks that just won't work due to dependencies that we've only tested on Linux. 

Agreed that we should prioritize testing on Databricks first based on customers we've engaged on the platform.

**Comment by jingyanwangms** [comment]
Without knowing this repo is not yet tested on Windows, I tried to run it on my local box. So far I've just tried 00_quick_start folder, 01_prepare_data folder and 02_model/als_deep_dive.ipynb. Maybe there're more things to fix for other notebooks as I go.

If we plan to add support for Windows, I will find some time to try setting up a fresh Windows VM and verify various things I tried.

----

Here's an incomplete list of the errors I encountered. Some fixes are probably unnecessary, just part of trying. 

- Added C:\ProgramData\Miniconda3\Scripts\, C:\ProgramData\Miniconda3\Library\bin to user variable
- When running conda env create -n reco_pyspark -f conda_pyspark.yaml, I received below

> CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.anaconda.com/pkgs/main/win-64/repodata.json.bz2>

I tried adding proxy setting in .condarc and ssl verify setting as discussed [here](https://github.com/ContinuumIO/anaconda-issues/issues/2760).

- For one of the configuration steps (probably conda env create -n reco_pyspark -f conda_pyspark.yaml), running powershell as Administrator gave below permission errors, but running as user works fine

> Access is denied: 'c:\\programdata\\miniconda3\\envs\\reco_bare\\-cripts\\jupyter-nbconvert.exe'

-  Installed pyspark
- When running als_pyspark_movielens.ipynb, I received below

> Java gateway process exited before sending its port number java_gateway.py

I tried unset and export PYSPARK_SUBMIT_ARGS in bash, then installed Java 8 and set JAVA_HOME as [this stackoverflow post](https://stackoverflow.com/questions/31841509/pyspark-exception-java-gateway-process-exited-before-sending-the-driver-its-po).
- From als_pyspark_movielens.ipynb, 3.1 movielens.load_spark_df() method threw below error:

> 'java.net.URISyntaxException: Relative path in absolute URI: file:C:/Users/jingywa/Source/Repos2/Recommenders/notebooks/00_quick_start/u.data'

I changed 2 lines in source code based on top answers from [this stackoverflow post](https://stackoverflow.com/questions/38940312/why-does-spark-report-java-net-urisyntaxexception-relative-path-in-absolute-ur).
In spark_utils.py:
Added .config("spark.sql.warehouse.dir", "file:///c:/tmp/spark-warehouse") to line 22
In movielens.py:
Line 169, from datapath = "file:" + _load_datafile(size, local_cache_path)
to datapath = "file:///" + _load_datafile(size, local_cache_path)

**Comment by miguelgfierro** [comment]
yeah, set up conda with spark is not easy, we will have to spend some time on optimizing this path

**Comment by wutaomsft** [comment]
+1 for this request.

**Comment by gramhagen** [comment]
@jingyanwangms did you install winutils.exe ? curious what process we should recommend there

**Comment by gramhagen** [comment]
I had to download https://github.com/steveloughran/winutils/blob/master/hadoop-2.6.0/bin/winutils.exe to C:\hadoop-2.6.0\bin\winutils.exe then create the following files:
~\AppData\Local\Continuum\anaconda3\envs\reco_pyspark\etc\conda\activate.d\env_vars.ps1
```
$env:HADOOP_HOME="C:\hadoop-2.6.0"
```
and
~\AppData\Local\Continuum\anaconda3\envs\reco_pyspark\etc\conda\deactivate.d\env_vars.ps1
```
$env:HADOOP_HOME=""
```

**Comment by miguelgfierro** [comment]
added by Jun Ki
