### ISSUE TITLE
Change generate_conda script to a python file

### ISSUE THREAD

**Issue by miguelgfierro** [Microsoft/Recommenders#492]
### *What* is affected by this bug?
Proposed by @gramhagen: it would be really great to refactor `generate_conda_file.sh` to a python script that leverages the [conda api](https://docs.conda.io/projects/conda/en/latest/api/python_api.html)
we could have a base set of dependencies in a list, and separate dependencies for each environment in different lists, then just run a single command to create the desired environment on any OS.

### In *which* platform does it happen?
* *Azure Data Science Virtual Machine.*

### Related issues
https://github.com/Microsoft/Recommenders/pull/447
https://github.com/Microsoft/Recommenders/issues/491

**Comment by gramhagen** [comment]
fixed in #512
