### ISSUE TITLE
User affinity formula description is incorrect in sar_single_node_deep_dive

### ISSUE THREAD

**Issue by jreynolds01** [Microsoft/Recommenders#495]
### *What* is affected by this bug?
*markdown text in sar_single_node_deep_dive does not match implementation

### In *which* platform does it happen?
*For example:*
* ALL

### *How* do we replicate the issue?

NA

### Other Comments

main issue is the log factor should be $-log(2) X$ **NOT** $-log_2(X)$

**Comment by gramhagen** [comment]
good catch
