### ISSUE TITLE
TOC Numbering does not match individual section name and links do not work

### ISSUE THREAD

**Issue by bethz** [Microsoft/Recommenders#498]
### *What* is affected by this bug?
Notebook Documentation in notebook [4 Operationalization](https://github.com/Microsoft/Recommenders/blob/master/notebooks/04_operationalize/als_movie_o16n.ipynb)

### In *which* platform does it happen?
All, not platform specific

### *How* do we replicate the issue?
The Table of Contents has 2 issues:
1. [Read the Table of Contents](https://github.com/Microsoft/Recommenders/blob/cb916f4f47edff629804667446172705f2cb1e48/notebooks/04_operationalize/als_movie_o16n.ipynb#L27) 
It is numbered 1,2,3,4 BUT the entries were numbered starting with 0,1,2...

2. Links in TOC do not work
Select and it does not go to the expected entry

### Expected behavior (i.e. solution)
Something is odd with the TOC implementation in the Markdown.  Do we have a norm for this?
Also, I'm used to the top level being something like ## and then each sublevel adds a #.

I'm happy to create a PR unless someone has an existing approach for a preferred way to make a TOC? 

### Other Comments
@nikhilrj thanks!

**Comment by bethz** [comment]
It seems the issue is how md rendering occurs in GitHub vs Jupyter environment.  Thoughts on how to address? Hardcoding is ugly. Do we need numbers? Thoughts?

**Comment by miguelgfierro** [comment]
oh I see. Yeah, the numberation was a mistake. 

Le wrote a notebook about how to organize the sections in a notebook https://github.com/Microsoft/Recommenders/blob/staging/notebooks/template.ipynb

**Comment by bethz** [comment]
The TOC is no longer in the notebooks so I'm closing the issue.
