### ISSUE TITLE
VW wrapper needed

### ISSUE THREAD

**Issue by gramhagen** [microsoft/recommenders#513]
### Description
Current vw testing doesn't match other algorithms execution pattern so can't easily be run for benchmarking

### In which platform does it happen?
Notebooks for vw testing / benchmarking

### Expected behavior (i.e. solution)
should be able to load model with parameters then fit, then predict:
```
vw = VW(**params)
vw.fit(train_dataframe)
prediction_dataframe = vw.predict(test_dataframe)
```

**Comment by loomlike** [comment]
#514 Check this issue about Recommender interface class and let's have discussion.
