### ISSUE TITLE
In Azure reference arch doc, our github link is broken

### ISSUE THREAD

**Issue by loomlike** [Microsoft/Recommenders#515]
I guess it happened after our file name changes.

**Comment by loomlike** [comment]
https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/ai/real-time-recommendation

**Comment by yueguoguo** [comment]
Great catch - sent PR to fix the link.

**Comment by nikhilrj** [comment]
Looks like it's fixed, thanks @yueguoguo @loomlike !
