### ISSUE TITLE
Better model-categorization in README table

### ISSUE THREAD

**Issue by loomlike** [Microsoft/Recommenders#519]
### Description
Current main README includes a algo table, but the categorization is a bit vague,
e.g. xDeepFM and DKN are both deep learning recommenders too but categorized under MS's recommenders.

### Expected behavior (i.e. solution)
Need discussion

**Comment by nikhilrj** [comment]
@miguelgfierro and I went back and forth on this - let's discuss tomorrow.

**Comment by yueguoguo** [comment]
Related to #516

**Comment by anargyri** [comment]
I like the Type column where you can enter multiple attributes describing the algorithm. We could also add details like news data for DKN.

**Comment by miguelgfierro** [comment]
Solved https://github.com/Microsoft/Recommenders
