### ISSUE TITLE
LightGBM Scenario: Databricks + MMLSpark + LightGBM distributed pattern, o16n on AKS + CRITEO

### ISSUE THREAD

**Issue by nikhilrj** [Microsoft/Recommenders#524]
LightGBM Based Recommender for Ecommerce
Model: LightGBM
Pipeline: Databricks + MMLSpark + LightGBM distributed pattern, operationalization on AKS
Dataset: Ecommerce or News (includes user or item features) for example CRITEO

**Comment by miguelgfierro** [comment]
TODO:

- [ ]  Create data loader for CRITEO in pyspark
- [ ] Installer for MMLSpark 
- [ ] Train LightGBM with CRITEO on Databricks
- [ ] o16n with AKS
- [ ] Write reference architecture

**Comment by jreynolds01** [comment]
draft of scenario doc: https://github.com/jreynolds01/architecture-center/blob/0b21c73289e88111486ddb8b6d6b6b4eed6aa1bc/docs/example-scenario/ai/criteo-personalization.md

**Comment by gramhagen** [comment]
initial cut at notebook here: https://github.com/Microsoft/Recommenders/blob/gramhagen/lgbm_scenario/notebooks/02_model/mmlspark_lightgbm_criteo.ipynb

need to split out training from serving and add tests
