### ISSUE TITLE
Deep Learning for News Recs

### ISSUE THREAD

**Issue by nikhilrj** [microsoft/recommenders#525]
Deep Learning Based Recommender for News
Model: DKN
Pipeline: Training on DLVM+GPU via AML, O16N on AKS+GPU
Dataset: News (includes user or item features)

**Comment by miguelgfierro** [comment]
TODO:
- Find a knowledge graph
- After the knowledge graph, try to find a dataset that has text (maybe not news) and matches knowledge graph

**Comment by anargyri** [comment]
I'd like to start a discussion about what are feasible scenarios with data in the public domain, that can be implemented. The objective is to have a scenario using DKN, maybe we could be flexible whether the data are about news or other types of text.

@Leavingseason do you think we could repeat the setup from this paper?
https://www.kdd.org/kdd2016/papers/files/adf0066-zhangA.pdf
The first data used is Movielens + Satori; is the Satori data publicly available? if not could we replace Satori with a public knowledge graph?
Is the second data set (IntentBooks) publicly available? 

It looks like the first approach (Movielens + DBpedia) has been used already in this paper
http://giusepperizzo.github.io/publications/Palumbo_Rizzo-RecSys2017.pdf

**Comment by anargyri** [comment]
Jester is another text recommendations data set
http://eigentaste.berkeley.edu/dataset/
Amazon reviews
http://jmcauley.ucsd.edu/data/amazon/

**Comment by gramhagen** [comment]
https://github.com/zygmuntz/goodbooks-10k is an interesting dataset, it would be nice to scrape text / images from each book to be able to leverage content features

**Comment by anargyri** [comment]
> https://github.com/zygmuntz/goodbooks-10k is an interesting dataset, it would be nice to scrape text / images from each book to be able to leverage content features

There may be IP issues with text / images from the book that may be difficult to sort out.

**Comment by almudenasanz** [comment]
Possible Knowledge Graphs:
- YAGO (wordNet + wikipedia): https://www.mpi-inf.mpg.de/departments/databases-and-information-systems/research/yago-naga/yago/
- Unigraph: https://github.com/unigraph/docs/wiki/Datadump
- DBPedia: https://wiki.dbpedia.org
- Wikidata: https://www.wikidata.org/wiki/Wikidata:Main_Page

News datasets:
- Webhose: https://webhose.io/free-datasets/ (link from @miguelgfierro)
- Yahoo News: https://webscope.sandbox.yahoo.com/catalog.php?datatype=r
- This is an interesting approach, building their own dataset from twitter info: https://github.com/huangy22/NewsRecommender
- To obtain just a list of news and titles, we could use MediaCloud's API: https://mediacloud.org

**Comment by almudenasanz** [comment]
I think this other dataset could be used for news recommendation: https://www.kaggle.com/gspmoreira/articles-sharing-reading-from-cit-deskdrop

**Comment by anargyri** [comment]
> I think this other dataset could be used for news recommendation: https://www.kaggle.com/gspmoreira/articles-sharing-reading-from-cit-deskdrop

Do they have a link to the data outside Kaggle?

**Comment by anargyri** [comment]
A github I saw related to knowledge graphs
https://github.com/SANSA-Stack

**Comment by miguelgfierro** [comment]
today, after a meeting with Jianxun, we discussed that we can create something similar to a news dataset, by merging Movielens with the text summary of the movie.

cc @almudenasanz @leavingseason

**Comment by miguelgfierro** [comment]
MSRA added 4 methods

**Comment by zzz123xyz** [comment]
> I'd like to start a discussion about what are feasible scenarios with data in the public domain, that can be implemented. The objective is to have a scenario using DKN, maybe we could be flexible whether the data are about news or other types of text.
> 
> @Leavingseason do you think we could repeat the setup from this paper?
> https://www.kdd.org/kdd2016/papers/files/adf0066-zhangA.pdf
> The first data used is Movielens + Satori; is the Satori data publicly available? if not could we replace Satori with a public knowledge graph?
> Is the second data set (IntentBooks) publicly available?
> 
> It looks like the first approach (Movielens + DBpedia) has been followed already in this paper
> http://giusepperizzo.github.io/publications/Palumbo_Rizzo-RecSys2017.pdf
> 
> Instead of news, we could use other text associated to the movies.

I also want to ask if the intentbook is available or not. Thanks
