### ISSUE TITLE
About AKS Cluster ?

### ISSUE THREAD

**Issue by harbourlga** [microsoft/recommenders#530]
In 3.3.2 Create an AKS Cluster to run your container (this may take 20-25 minutes),Use the default configuration dosen't work.

# Use the default configuration (can also provide parameters to customize)
prov_config = AksCompute.provisioning_configuration()
# Create the cluster
aks_target = ComputeTarget.create(workspace = ws, 
                                  name = aks_name, 
                                  provisioning_configuration = prov_config)

aks_target.wait_for_completion(show_output = True)

print(aks_target.provisioning_state)
print(aks_target.provisioning_errors)

above code Failed:
Creating.......................................
FailedProvisioning operation finished, operation "Failed"
Async operation failed with
StatusCode: 409
Message: Conflict
Compute object has provisioning state "Failed"
and provisioning errors: [{'error': {'details': [{'code': 'Conflict', 'message': 'SubDeployment: OperationId=A886E1117E76AA33, ProvisioningState=Failed, StatusCode=Conflict, StatusMessage={\n  "status": "Failed",\n  "error": {\n    "code": "ResourceDeploymentFailure",\n    "message": "The resource operation completed with terminal provisioning state \'Failed\'.",\n    "details": [\n      {\n        "code": "NotFound",\n        "message": "resources.DeploymentsClient#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code=\\"DeploymentNotFound\\" Message=\\"Deployment \'5eb9bc18-864a-4624-bc6e-1a43fd637c8d\' could not be found.\\""\n      }\n    ]\n  }\n}\n'}, {'code': 'Conflict', 'message': 'SubDeployment: OperationId=08586512111143685647, ProvisioningState=Failed, StatusCode=Conflict, StatusMessage=Template output evaluation skipped: at least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.\n'}], 'message': 'Conflict', 'code': 'Conflict', 'statusCode': 409}, 'code': 'Conflict', 'message': 'Conflict'}]
Failed
[{'error': {'details': [{'code': 'Conflict', 'message': 'SubDeployment: OperationId=A886E1117E76AA33, ProvisioningState=Failed, StatusCode=Conflict, StatusMessage={\n  "status": "Failed",\n  "error": {\n    "code": "ResourceDeploymentFailure",\n    "message": "The resource operation completed with terminal provisioning state \'Failed\'.",\n    "details": [\n      {\n        "code": "NotFound",\n        "message": "resources.DeploymentsClient#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code=\\"DeploymentNotFound\\" Message=\\"Deployment \'5eb9bc18-864a-4624-bc6e-1a43fd637c8d\' could not be found.\\""\n      }\n    ]\n  }\n}\n'}, {'code': 'Conflict', 'message': 'SubDeployment: OperationId=08586512111143685647, ProvisioningState=Failed, StatusCode=Conflict, StatusMessage=Template output evaluation skipped: at least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.\n'}], 'message': 'Conflict', 'code': 'Conflict', 'statusCode': 409}, 'code': 'Conflict', 'message': 'Conflict'}]

**Comment by yueguoguo** [comment]
@nikhilrj @danielsc @heatherbshapiro FYI probably you can provide help on this.

**Comment by nikhilrj** [comment]
@dciborow have you seen this before?

"Conflict" means the following:
> You're requesting an operation that isn't allowed in the resource's current state. For example, disk resizing is allowed only when creating a VM or when the VM is deallocated.

Do you already have your AKS resource provisioned when you run into this?

**Comment by harbourlga** [comment]
YES, AKS resource had been Created in Azure Portal when run als_movie_o16n on Databricks.However, in Azure Portal it show Status Failed. I don't understand , AKS resource provisioned?

**Comment by miguelgfierro** [comment]
closing because stale issue, feel free to reopen if needed
