### ISSUE TITLE
DRY in stratified and chrono splitters

### ISSUE THREAD

**Issue by miguelgfierro** [Microsoft/Recommenders#537]
### Description

Perform Don't Repeat Yourself (DRY) on stratified and chrono splitters.

@loomlike:
Our stratified and chrono splitters share many similar codes. Does it make sense to define a private function, e.g. `_prepare_stratification()` and share them from both splitters? Maybe a bit tricky in the main splitting algorithm part but at least the column validity check and data preparation part look the same.

@anargyri:
Good point, they look very similar. The main difference between the two methods is `sort_values(col_timestamp)`
Probably the chrono split could be reduced to sorting the timestamps and then calling the stratified splitter. We could open a new issue for this.

### In which platform does it happen?

 Azure Data Science Virtual Machine.

**Comment by yueguoguo** [comment]
I can also take a look at this one.

**Comment by yueguoguo** [comment]
Fixed in #607
