### ISSUE TITLE
Test spark hypertune notebook

### ISSUE THREAD

**Issue by anargyri** [Microsoft/Recommenders#542]
### Description

There are no tests for the notebook for Spark tuning  https://github.com/Microsoft/Recommenders/blob/master/notebooks/04_model_select_and_optimize/hypertune_spark_deep_dive.ipynb 

### Expected behavior with the suggested feature

Should we add unit, smoke and integration tests, or just unit tests? What are the scalability limitations?

**Comment by yueguoguo** [comment]
Great suggestion. Is it reasonable to have these after #432 and #450 are resolved, or the tests can be run on the existing one-node DevOps machine?

**Comment by loomlike** [comment]
This will applicable to aml_* notebooks too (currently, one in #448 also doesn't have tests). The thing is, it is very tricky to test. Should start a run and wait until the run finishes and check its status with [get_status()](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.run.run?view=azure-ml-py#get-status--) to see if it is "Completed" or "Failed".

**Comment by anargyri** [comment]
I opened this issue only for this notebook. This notebook is more straightforward to test because it does not use AML. For the other notebooks I opened a separate discussion here #547

**Comment by yueguoguo** [comment]
Fixed in #583
