### ISSUE TITLE
[FEATURE] Support on Windows.

### ISSUE THREAD

**Issue by jreynolds01** [Microsoft/Recommenders#544]
### Description

The conda script to generate a conda file works on windows appropriately. Further, conda states it creates an appropriate environment, but the resulting environment cannot be activated. 

```
activate reco_base
```

results in a crash of the anaconda prompt with final message:

```
Did not find VS in registry or in VS140COMNTOOLS env var - exiting
```

### In which platform does it happen?

Windows

### How do we replicate the issue?

on windows:

```
python scripts\generate_conda_file.py
activate reco_base
```

results in a crash

### Expected behavior (i.e. solution)

expected behavior is that the conda environment is activated.

### Other Comments

Fix incoming - the issue is due to a bad build for windows in the `conda-forge` channel

**Comment by loomlike** [comment]
Related to #491

**Comment by jreynolds01** [comment]
Grrr - sorry for the sort-of dupe; I did a quick search and didn't see 491. This is pretty narrowly constrained to just the reco_base conda env.
