### ISSUE TITLE
[BUG] conda update conda error - PackageNotInstalledError: Package is not installed in prefix

### ISSUE THREAD

**Issue by roalexan** [Microsoft/Recommenders#550]
### Description
I'm getting an error when running the first setup instruction on my Linux (Ubuntu) DSVM.

### In which platform does it happen?
Azure Data Science Virtual Machine (Ubuntu)

### How do we replicate the issue?
I created a Linux (Ubuntu) DSVM, set up port forwarding, and opened a browser to log into to Jupyter using my VM username/password. I then ran the first step from the command line to setup the dependencies, from the instructions here: https://github.com/Microsoft/Recommenders/blob/master/SETUP.md#dependencies-setup:

conda update conda

This produced the following console output error:

PackageNotInstalledError: Package is not installed in prefix.
  prefix: /data/anaconda/envs/py35
  package name: conda

### Expected behavior (i.e. solution)
Should be no error

### Other Comments
I could run the next line, 'conda update anaconda', so it looks like conda is indeed there.

**Comment by miguelgfierro** [comment]
Maybe this could help https://groups.google.com/a/continuum.io/forum/m/#!topic/anaconda/OZ77eyoFwiw it says to add the name of the base env.

@paulshealy1 any guidance on this?

**Comment by paulshealy1** [comment]
The _conda_ package is only available in the Anaconda root environment, not all environments. The Ubuntu DSVM has the py35 environment as the default one, and the root environment is py27. This update step should be _conda update conda -n root_ for the Ubuntu DSVM.

**Comment by roalexan** [comment]
I suggest that this issue is resolved by changing the initial README.md and associated SETUP.md to show the setup steps for each environment - 1) local, 2) Ubuntu DSVM, 3) etc...

**Comment by yueguoguo** [comment]
Resolved in #563

**Comment by yts61** [comment]
how was it solved?

**Comment by gramhagen** [comment]
@yts61 the setup instructions were changed to
`conda update conda -n root`
I believe you could also use
`conda update -n base conda`
