### ISSUE TITLE
[ASK] Model save in xDeepFM

### ISSUE THREAD

**Issue by AWalkInClouds** [Microsoft/Recommenders#551]
### Description

How to save model in XDeepFm

**Comment by yueguoguo** [comment]
The xDeepFM is implemented in TensorFLow so that you can follow the same convention to persist the model. 

@Leavingseason would it better to provide the info in the notebook as I see it is mentioned to reload saved model to avoid training from scratch?

**Comment by AWalkInClouds** [comment]
/Users/dukeyu/anaconda3/envs/reco/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py:112: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "

**Comment by AWalkInClouds** [comment]
Run  notebook-Xdeepfm

**Comment by AWalkInClouds** [comment]
How to upload  my notebook to you foe help?

**Comment by AWalkInClouds** [comment]
for help

**Comment by AWalkInClouds** [comment]
<img width="2322" alt="2019-02-22 10 21 53" src="https://user-images.githubusercontent.com/35360577/53215489-d8f80e00-368b-11e9-949e-f4d9f0268c9f.png">

**Comment by AWalkInClouds** [comment]
<img width="2256" alt="2019-02-22 10 22 13" src="https://user-images.githubusercontent.com/35360577/53215500-e57c6680-368b-11e9-9759-ec9fe60f232b.png">

**Comment by AWalkInClouds** [comment]
<img width="2445" alt="2019-02-22 10 22 26" src="https://user-images.githubusercontent.com/35360577/53215517-f5944600-368b-11e9-96d5-f527e91c6ad7.png">
