### ISSUE TITLE
Create data loader for CRITEO in pyspark

### ISSUE THREAD

**Issue by miguelgfierro** [Microsoft/Recommenders#555]
### Description

Create data loader for CRITEO in pyspark

### In which platform does it happen?

* Azure Databricks.
* Azure Data Science Virtual Machine

**Comment by jreynolds01** [comment]
Dataset to be used is the link available after filling this form: http://labs.criteo.com/2014/02/kaggle-display-advertising-challenge-dataset/

**Comment by jreynolds01** [comment]
first pass at load for databricks is available [here](https://github.com/Microsoft/Recommenders/blob/jeremr-criteo-dataloader/reco_utils/dataset/criteo_dac.py). Working on tests.

**Comment by miguelgfierro** [comment]
Several comments/questions:
1) what is dac in criteo_dac?
2) I think we are also using _clean_up(filepath) in the downloader of movielens, I think it would make sense to add it as a common function

**Comment by jreynolds01** [comment]
dac = 'digital advertising challenge'. They have shared multiple [datasets](https://ailab.criteo.com/outreach/), so it is to discriminate in case we ever work with something like the terabyte click logs or another.

Yes, thought the same about `_clean_up()`
