### ISSUE TITLE
 Train LightGBM with CRITEO on Databricks

### ISSUE THREAD

**Issue by miguelgfierro** [Microsoft/Recommenders#556]
### Description

 Train LightGBM with CRITEO on Databricks

### Other Comments
Mockup code:
```
import pyspark.sql.functions as F
import pyspark.sql.types as T
 
from pyspark.ml.feature import (
  Imputer,
  OneHotEncoderEstimator,
  StringIndexer,
  VectorAssembler,
)
from pyspark.ml.pipeline import Pipeline
 
...
 
pipeline = Pipeline(stages=[
  Imputer(strategy='median',
          inputCols=features,
          outputCols=[f + '_imp' for f in features]),
  # LightGBM can handle categoricals directly if StringIndexer is used through meta-data
  *[StringIndexer(inputCol=f+'_na', outputCol=f+'_vec') for f in sparse_features + features],
  VectorAssembler(inputCols=[f + '_imp' for f in features] +
                            [f + '_vec' for f in sparse_features + features] +
                            app_features,
                  outputCol='features')
])
...
pipeline.fit(all).transform(all).saveAsTable('train')
 
model = LightGBMClassifier(featuresCol='features', 
                           labelCol='label', 
                           numIterations=classifier_lightgbm_iterations, 
                           numLeaves=64,
                           isUnbalance=True)
 
grid = (ParamGridBuilder()
  # .addGrid(model.numLeaves, [31]) # for now it's good enough
  .build())
 
evaluator = BinaryClassificationEvaluator(labelCol='label')
 
cv = CrossValidator(estimator=model, estimatorParamMaps=grid, evaluator=evaluator, numFolds=n_folds)
model = cv.fit(train)
```

**Comment by jreynolds01** [comment]
First pass at this based on the code above is available [here](https://github.com/Microsoft/Recommenders/blob/jeremr-criteo-dataloader/notebooks/02_model/lightgbm_estimate_criteo_dac.ipynb). The fit() calls for both the model and cv seem unstable - some times they succeed and sometimes they don't. Hopefully this helps - I need to work on a couple of other things tomorrow and will come back to this later this week.

**Comment by imatiach-msft** [comment]
@jreynolds01 what is your cluster configuration?  did you make sure to disable dynamic allocation?

**Comment by miguelgfierro** [comment]
done in https://github.com/Microsoft/Recommenders/pull/680

**Comment by emnajaoua** [comment]
Hi everyone, I am trying to run the lightGBMClassifier with my own dataset but I am always facing this error: java.net.ConnectException: Connection refused (Connection refused). I have described very well my issue here : [https://github.com/Azure/mmlspark/issues/609](url)
I would be very grateful if someone could have a look on it !
Thank you in advance

**Comment by gramhagen** [comment]
Hi @emnajaoua, let's track this issue in a single place. I think mmlspark is the right place for the discussion. I will add comments there.
