### ISSUE TITLE
[BUG] SVD notebook presentation improvements

### ISSUE THREAD

**Issue by wutaomsft** [Microsoft/Recommenders#561]
### Description

Misc presentation suggestions/issues on SVD deep dive notebooks.
1. "The SVD model algorithm is very similar to the ALS algorithm presented in the ALS deep dive notebook": add ALS notebook link.
2. "also called baselines in the litterature": typo, also need to add references.
3, "The model is SVD is then as follows": revise.
4. "𝑏𝑢←𝑏𝑢+𝛾(𝑒𝑢𝑖−𝜆𝑏𝑢)": does not render in browser mode.
5. Move introduction of SVD and references up front.

**Comment by yueguoguo** [comment]
This is fixed in #596 right? I am closing the issue now - if needed for any discussion we can open it again @wutaomsft
