### ISSUE TITLE
[FEATURE] SETUP for Azure Databricks uses 'zip' command not available on Windows

### ISSUE THREAD

**Issue by roalexan** [Microsoft/Recommenders#564]
### Description
The setup instructions here, https://github.com/Microsoft/Recommenders/blob/master/SETUP.md#repository-installation, say to run 'zip' on your local computer. If you're running Windows, this won't work.

### Expected behavior with the suggested feature
For those users running Windows, describe the steps they should use to create the archived file. My workaround will probably be to use a Linux DSVM that I have already created (and downloaded the recommendations repo) and run the 'zip' command there.

**Comment by yueguoguo** [comment]
Still working to support other OS, but yea this is something important. 

At least we need to make it clear somewhere that all the system commands used/mentioned in the repo are for Linux.

**Comment by roalexan** [comment]
I agree that it might be sufficient to state somewhere that the commands are intended to be run on a Linux environment. Since these commands are designed to be run on the user's local computer, I do wonder how many people have a local Linux computer.

**Comment by bethz** [comment]
I think we need both Windows and Linux support. In a couple of the prior companies I worked for, Linux was the most prevalent work environment with Windows used only for email/meeting setup/office. But, Windows dev is a huge environment that we have a unique advantage with and should not ignore. So, that means both.

**Comment by loomlike** [comment]
You can use Windows with some extra tools, e.g. [GOW](https://github.com/bmatzelle/gow/wiki) (Gnu on Windows). I'm using Windows and all the scripts and setups in our repo are working on my env.

**Comment by roalexan** [comment]
Maybe. I like the way some other Microsoft documentation handles setup instructions, example:

# Bash
zip -r myAppFiles.zip .

# PowerShell
Compress-Archive -Path * -DestinationPath myAppFiles.zip

from: https://docs.microsoft.com/en-us/azure/app-service/app-service-web-get-started-nodejs#create-a-project-zip-file
