### ISSUE TITLE
[FEATURE] Create a version of operationalize notebook for ALS for Jupyter notebook

### ISSUE THREAD

**Issue by roalexan** [microsoft/recommenders#565]
### Description
There is already an operationalize notebook for ALS, Recommenders\notebooks\05_operationalize\als_movie_o16n.ipynb, that works on Databricks. Make a version that works on Jupyter Notebook, for example on a Ubuntu DSVM 

### Expected behavior with the suggested feature
A new notebook showing operationalizing an ALS model on Jupyter notebook.

**Comment by yueguoguo** [comment]
@roalexan trying to understand more about the rationality of having another notebook for DSVM as it might be simple to switch the computing instance from ADB to DSVM...

**Comment by roalexan** [comment]
I think it's more that just switching the compute. The setup steps in particular, such as what libraries are available, is what tripped me up. als_movie_o16n.ipynb involves a fair amount of setup steps specific to Databricks to get all the libraries in place. I think this would also be useful to support those customers that have not adopted Databricks.

**Comment by nikhilrj** [comment]
Thanks - +1 to this ask. I'll take a stab at this.
