### ISSUE TITLE
[FEATURE] Create a version of operationalize notebook for SAR

### ISSUE THREAD

**Issue by roalexan** [microsoft/recommenders#566]
### Description
There is already a SAR operationalize notebook, Recommenders\notebooks\05_operationalize\als_movie_o16n.ipynb. Make a version for SAR.

### Expected behavior with the suggested feature
A sample SAR operationalize notebook.

**Comment by jreynolds01** [comment]
This work for AML Pipeline recipes is relevant: https://github.com/Microsoft/Recommenders/blob/jeremr-parallel-top10/notebooks/02_model/parallel_scoring_2_prepare_and_run_amlpipeline.ipynb

It's not in the write place, but it is an operationalization / scoring notebook that just needs to add the cosmosdb piece to make it comparable to the ALS one.
