### ISSUE TITLE
[FEATURE] Support for Windows

### ISSUE THREAD

**Issue by miguelgfierro** [Microsoft/Recommenders#567]
### Description

Test pipeline for a Windows machine, which will include unit, smoke and integration tests for CPU, GPU and PySpark envs.

### Expected behavior with the suggested feature

Similar to what we have in Linux, but with Windows

**Comment by gramhagen** [comment]
after reinstalling visual studio and cuda toolkit on windows the gpu environment works for me, pyspark and base too, so this should be doable without too much hassle

**Comment by loomlike** [comment]
Is visual studio necessary?

**Comment by gramhagen** [comment]
pytorch needed the vs14 runtime libraries

**Comment by gramhagen** [comment]
hmm, after looking more closely I don't think it's actually using the gpu device, tf.test.is_gpu_available() still indicates False =(
