### ISSUE TITLE
[FEATURE] Dataloader to have a progress bar

### ISSUE THREAD

**Issue by loomlike** [Microsoft/Recommenders#574]
### Description
Dataloader to show a progress bar will be useful for larger dataset.

### Expected behavior with the suggested feature
Whenever call `data_set_name.load_pandas/spark_df`, shows the progress bar

**Comment by yueguoguo** [comment]
Ha this is a great idea 💯

**Comment by jreynolds01** [comment]
I have an example of this in the context of the lightgbm work easily enough if we are ok with adding another dependency such as tqdm. https://pypi.org/project/tqdm/ (see the urlretrieve example on that page).

**Comment by jreynolds01** [comment]
eh - that leaves a lot to be desired in a notebook. Really need a widget instead.

**Comment by loomlike** [comment]
hmmm... databricks is a really cool tool, but at the same time it is not very seamless experience when moving from jupyter notebooks even they both look the same...

**Comment by miguelgfierro** [comment]
Fixed in https://github.com/Microsoft/Recommenders/pull/642
