### ISSUE TITLE
[FEATURE] Data preprocessing and scoring for top-N recommendation on movielens for xdeepFM

### ISSUE THREAD

**Issue by yexing99** [Microsoft/Recommenders#585]
The followings need to be finished:

1. For scoring the topN recommendation, the data needs to be pre-proccessed to have the ranking pool.
2. Add scoring components for topN recommendation using reco repo

**Comment by yexing99** [comment]
Finished

**Comment by yueguoguo** [comment]
> Finished

@yexing99 does it mean it is resolved?

**Comment by loomlike** [comment]
Regarding generating a ranking pool (all user-item pairs or except the pairs in the training set if we want to remove 'seen' items), it is already there under `reco_utils/dataset/pandas_df_utils.py`

**Comment by yexing99** [comment]
The work is already done.. Your script does not apply here.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by yexing99** [comment]
All the work has been finished. It is under my branch. I opened this ticket just for purpose of reporting progress as I should do it previously.

**Comment by yueguoguo** [comment]
@yexing99 I am closing this issue now unless there is anything needed to invoke team's attention. Do you want to merge the code that resolves this issue into the staging branch? Or you will wait till later when everything is finished?
