### ISSUE TITLE
Docstring to NCF

### ISSUE THREAD

**Issue by loomlike** [microsoft/recommenders#597]
### Description
NCF example implementation doesn't have docstring. It does have enough comments. We can move those comments to docstring format.

### Expected behavior (i.e. solution)
NCF class with good docstrings

### Other Comments
Also would be good to have gpu check codes at its example notebook. FYI, gpu check codes are in wide-deep quickstart notebook.

**Comment by yueguoguo** [comment]
Not sure if @AaronHeee has the bandwidth on this - I can take it if not.

**Comment by AaronHeee** [comment]
Sure, I will take it @yueguoguo
