### ISSUE TITLE
[ASK] Notes on SAR, question please

### ISSUE THREAD

**Issue by seancaodo** [Microsoft/Recommenders#602]
### Description

Hi,

Sorry, it's me again. Below note in document https://github.com/Microsoft/Recommenders/blob/master/notebooks/00_quick_start/sar_movielens.ipynb:

"Notes to use SAR properly:
    Since it does not use item or user features, it can be at a disadvantage against algorithms that do."

suggests that SAR does not use item or user features. In previous version however:

https://github.com/Microsoft/Product-Recommendations/blob/master/doc/sar.md

author stated that a linear learner using item features will be used for cold and cold/warm items situations. Does this mean this feature of using item features in the current SAR has been taken off? Or is it only just SARSingleNode?

Many thanks again,

**Comment by gramhagen** [comment]
The implementation of SAR in this repository does not include cold start using item features. However it should be straightforward to port. PRs welcome! =)

**Comment by seancaodo** [comment]
Thanks @gramhagen, I'm new to git and GitHub so not sure how to do Pull Requests yet. 

I'm not sure if I should create a feature request either.. I think it may be quite beneficial for others as well though. I'll formulate my current problem further to see if we would need this feature and update accordingly.

Thanks again.
