### ISSUE TITLE
[BUG] SAR indexing issue

### ISSUE THREAD

**Issue by yueguoguo** [Microsoft/Recommenders#606]
### Description
Not 100% this is discussed before but it would be great that SAR Single Node can handle the index better for an enhanced usability.

Painpoints:
* When one tries to build a SAR model he has to do the indexing manually - it would be great that this can be wrapped properly in the implementation itself for enhanced usability.
* The returned top k recommendations used the same column names, e.g., user ID, item ID, etc., which are the same to the original dataset. However, after re-indexing, columns with the same in the top k recommendation dataset and the original training dataset are different. This causes issues for correctly using the recommendation results. E.g., if movielens dataset is used and one wants to use the recommended movie IDs to get movie titles, it does not work. 

### In which platform does it happen?
CPU platform where SAR single node implementation is used.

### How do we replicate the issue?
1. Use the the movielens dataset with `title` parameter set properly in the function of `load_pandas_df`.
2. Follow the SAR notebook to generate the recommendation results.
3. The movie IDs in the recommendation results do not correspond to the movie titles correctly.

### Expected behavior (i.e. solution)
* It should be indicated clearly the columns in the recommendation data are different from the original one.
* It would be great that the indexing operations are wrapped in SAR implementation itself.

**Comment by miguelgfierro** [comment]
Can you elaborate:
> When one tries to build a SAR model he has to do the indexing manually

I don't understand the second point either, the input columns are: `'UserId','MovieId','Rating','Timestamp'` and the output are `UserId, MovieId, prediction`, are you referring to these columns?

**Comment by yueguoguo** [comment]
> 'UserId','MovieId','Rating','Timestamp' and the output are UserId, MovieId, prediction, are you referring to these columns?

In SAR's case, if the indexing is applied, the returned top k recommendations with column `MovieId' contain different IDs from that in the input data (this is because it is re-indexed). Or am I missing anything here...

**Comment by gramhagen** [comment]
@yueguoguo the current version of SAR singlenode in the repo doesn't require external indexing and does convert the recommended item indices back to the original ids. It could be how you are initializing the model. This seems to work for me:
```
train, test = python_random_split(movielens.load_pandas_df(size='100k', title_col='title'))
model = SARSingleNode(
    remove_seen=True, 
    similarity_type="jaccard", 
    time_decay_coefficient=30, 
    time_now=None, 
    timedecay_formula=True,
    col_item='title')
model.fit(train)
top_k = model.recommend_k_items(test)
display(top_k.head(5))
```

| idx | userID | title | prediction |
|-|-|-|-|
|0|498|Forrest Gump (1994)|3.163114|
|1|498|Dead Poets Society (1989)|3.172998|
|2|498|Wizard of Oz, The (1939)|3.178975|
|3|498|Jaws (1975)|3.186345|
|4|498|Terminator 2: Judgment Day (1991)|3.194543|

**Comment by yueguoguo** [comment]
Thanks @gramhagen for the proof - talked with @gjwgit and it seems the old version of SAR is used. I'll close this issue unless there is any other bug found.
