### ISSUE TITLE
[BUG] Papermill Record is deprecated in Papermill 1.0 and has been replaced by scrapbook

### ISSUE THREAD

**Issue by bethz** [microsoft/recommenders#641]
### Description
This applies to any notebook using pm.record to capture logs.

### In which platform does it happen?
this applies to all platforms and any notebook using papermill.record

### How do we replicate the issue?
Run the SARS notebook.
The last cell uses pm.record and generates a warning:
/data/anaconda/envs/reco_full/lib/python3.6/site-packages/ipykernel_launcher.py:3: DeprecationWarning: Function record is deprecated and will be removed in verison 1.0.0 (current version 0.19.0). Please see `scrapbook.glue` (nteract-scrapbook) as a replacement for this functionality.
  This is separate from the ipykernel package so we can avoid doing imports until

### Other Comments
Scrapbook does not appear to be a drop in replacement for pm.record .

**Comment by heatherbshapiro** [comment]
Should we pin the release version until we can get a fix for this?

**Comment by gramhagen** [comment]
yeah, sounds good

**Comment by wutaomsft** [comment]
+1 to fix this as this is breaking notebooks now that papermill 1.0 is out @gramhagen @yueguoguo

**Comment by gramhagen** [comment]
We have locked down the version to 0.18.2, so this shouldn't cause is trouble. But yeah we should prioritize switching off to minimize changes as new notebooks are added.

**Comment by wutaomsft** [comment]
Hmm when I created the Env papermill was not installed...

________________________________

**Comment by gramhagen** [comment]
We've seen this on Windows for certain versions of conda. Try conda update conda, then retry the env installation.
________________________________

**Comment by wutaomsft** [comment]
Yes this is on windows.

________________________________
