### ISSUE TITLE
[FEATURE] Optimize column checking codes in each function with decorator

### ISSUE THREAD

**Issue by yueguoguo** [microsoft/recommenders#648]
### Description
Decorator pattern is used to check columns in Python evalutor (https://github.com/Microsoft/Recommenders/blob/master/reco_utils/evaluation/python_evaluation.py). It would be good to have it used across the repo where column checking is a common task for properly using a function.

### Expected behavior with the suggested feature
The code for functions that may need to check columns can be optimized from
```
def func_old(df, col_user, col_item, col_rating):
    columns = df.columns
    if col_user not in columns:
        raise ValueError("Column {} is not in the input data".format(col_user))
    ...
```
to
```
@check_column
def function_new(df, col_user, col_item, col_rating):
    ...
```

**Comment by gramhagen** [comment]
what can we do if the required columns are missing? catching it and raising an error seems the same as not checking at all and raising the error where it occurs in the function

**Comment by yueguoguo** [comment]
@gramhagen Yea it should check the existence of columns as well. If it occurs in the function, the error might be different. See #543 for example. The input datasets to the evaluator may be different, and the difference in dtypes may result in some unexpected behaviors.

**Comment by gramhagen** [comment]
yeah, you're right. I am working on some changes to the python evaluation code, and will push a PR for review of that approach. Changes to address type checking can be put there.
