### ISSUE TITLE
[ASK] SAR random split/prediction

### ISSUE THREAD

**Issue by ajhepburn** [Microsoft/Recommenders#649]
I'm trying to run through the SAR example with my own dataset and have formatted the dataset to look almost identical to the MovieLens input:

```
   user_id  item_id    weight  item_timestamp
0      170       71  0.000325      1484669739
1      170      325  0.000325      1485980875
2      170      387  0.000325      1485373566
3      170      474  0.000325      1483971321
4      170      526  0.000650      1490022081
```

However, I come across an issue when trying to run `recommend_k_items` with a `remove_seen=True` flag, I get the following error:

```
Traceback (most recent call last):
  File "model_sar.py", line 127, in <module>
    sar.run()
  File "model_sar.py", line 120, in run
    top_k = self.predict_items(model, test)
  File "model_sar.py", line 107, in predict_items
    top_k = model.recommend_k_items(test, remove_seen=True)
  File "/media/ntfs/Workspace/Project/rec-sys/reco_utils/recommender/sar/sar_singlenode.py", line 297, in recommend_k_items
    test_scores = self.score(test, remove_seen=remove_seen)
  File "/media/ntfs/Workspace/Project/rec-sys/reco_utils/recommender/sar/sar_singlenode.py", line 261, in score
    raise ValueError("SAR cannot score users that are not in the training set")
ValueError: SAR cannot score users that are not in the training set
```

Is there a way to configure fitting/splitting of the data so that this issue doesn't occur? I've attempted to use the flag during the fitting stage as well to no avail. Apologies if this is technically a bug but I didn't want to report something that was likely down to a misunderstanding of usage.

**Comment by ajhepburn** [comment]
Just realised my problem was not reading documentation enough, used stratified split instead of random.

**Comment by gramhagen** [comment]
Hey there, thanks for the question, I think there's room to extend the notebook documentation to make some of these things clearer.
1. It's not necessary to reformat the titles of your data to match movielens for SAR, you just need to pass arguments to SAR telling it where to look for users, items, ratings, otherwise it uses defaults
```
model = SARSingleNode(
  col_user='MyUserCol',
  col_item='MyItemCol',
  col_rating='MyRatingCol'
)
```
2. yes, you beat me to it!

```
train, test = python_stratified_split(
  data,
  ratio=0.8,
  min_rating=1,
  filter_by='user',
  col_user='MyUserCol',
  col_item='MyItemCol'
  seed=123
)
```
