### ISSUE TITLE
[FEATURE] Reorganize the reco_utils folder

### ISSUE THREAD

**Issue by yueguoguo** [microsoft/recommenders#651]
### Description
I found I did not reuse some good utitilies in the repo that could have saved much work in #637 . Not sure if a new user will get lost or not, given that many relevant utility functions are scattered here and there in the `reco_utils` 

### Expected behavior with the suggested feature
* Reorganization of the `reco_utils`. For instance, the utilities for Pandas splitter and Pandas DataFrame can be put together into one script?
* Maybe good documentation of the utilities are needed as a reference for the users. 

### Other Comments

**Comment by miguelgfierro** [comment]
We discussed the documentation in some meeting. It would be quite easy to compile a documentation using sphinx and readthedocs.

**Comment by yueguoguo** [comment]
@miguelgfierro readthedocs is all we need 😄

**Comment by gramhagen** [comment]
I generated a branch at one point which used sphinx apidoc to generate documentation (at least for the reco_utils sub-folders). There were some concerns around how best to maintain / host the documentation though so it was not pushed forward.  Maybe we should revisit it, with building / publishing docs built into the process for pushing to master?

**Comment by yueguoguo** [comment]
Agree with @gramhagen
