### ISSUE TITLE
[BUG] broken links in Hyperdrive wide and deep notebook

### ISSUE THREAD

**Issue by anargyri** [Microsoft/Recommenders#655]
### Description

https://github.com/Microsoft/Recommenders/blob/master/notebooks/04_model_select_and_optimize/azureml_hyperdrive_wide_and_deep.ipynb
The "entry script" links do not work (give 404).

**Comment by loomlike** [comment]
oh yeah. seems our folder name has changed from 'aml' to 'azureml'. There might be another broken links in both wide-deep and azureml- notebooks because of the name changes. I will check them. Thanks @anargyri !

**Comment by yueguoguo** [comment]
Fixed in #678
