### ISSUE TITLE
[FEATURE] Alphabetical order of algorithms in README table

### ISSUE THREAD

**Issue by loomlike** [Microsoft/Recommenders#663]
### Description
Now it is getting difficult to find a specific algorithm from the table ;-)

### Expected behavior with the suggested feature
Alphabetically ordered Algorithms table.

**Comment by yueguoguo** [comment]
Would it be better to order by `type`?

**Comment by loomlike** [comment]
@yueguoguo type sounds good to me too. So 1. order by type -> then 2. order by 'abc..' within the same type

**Comment by yueguoguo** [comment]
Fixed in #675
