### ISSUE TITLE
[BUG] Criteo loader on databricks issues

### ISSUE THREAD

**Issue by gramhagen** [Microsoft/Recommenders#672]
### Description
the criteo loader on azure databricks doesn't seem to support local_cache_path set to FileStore or I'm doing it wrong
tmp_data = load_spark_df(size='sample', spark=spark, dbutils=dbutils, local_cache_path='/FileStore')
FileNotFoundError: [Errno 2] No such file or directory: '/FileStore/dac_sample.tar.gz'

using local_cache_path='.' or 'tmp' works though

also the tqdm progress prints to a newline, maybe able to change the end option in write() as described here: https://stackoverflow.com/questions/41707229/tqdm-printing-to-newline

example
```
0.00B [00:00, ?B/s]
  0%|          | 0.00/4.58G [00:00<?, ?B/s]
  0%|          | 8.19k/4.58G [00:00<19:57:01, 63.7kB/s]
  0%|          | 41.0k/4.58G [00:00<15:28:20, 82.2kB/s]
```

### In which platform does it happen?
Azure Databricks

**Comment by miguelgfierro** [comment]
I'll try to find time to take a look at this today

**Comment by loomlike** [comment]
@miguelgfierro check [movielens.py](https://github.com/Microsoft/Recommenders/blob/bbef6e254128a59529549b2bbf8c60d7f4478336/reco_utils/dataset/movielens.py#L375)

try add "file://" instead of "file:"

**Comment by jreynolds01** [comment]
Also did you create a /FileStore in the local filesystem? By default it's just a dbfs path and not available on local (except through /dbfs/FileStore)
