### ISSUE TITLE
[FEATURE] Sample site utilizing operationalized recommender service

### ISSUE THREAD

**Issue by nikhilrj** [microsoft/recommenders#673]
### Description
Have a sample website using movie recommendations that can be used for workshops, ebcs, etc. Website would call model hosted with operationalization notebook to get and display movie recommendations.

### Expected behavior with the suggested feature
Visual UI that shows live recommendations.

### Other Comments
@heatherbshapiro fyi

**Comment by miguelgfierro** [comment]
+1 to this, we can even do a web for the project like the cool kids: https://www.tensorflow.org/, https://pytorch.org/

**Comment by miguelgfierro** [comment]
developed in https://github.com/microsoft/recommenders_engine_example_layout
