### ISSUE TITLE
[BUG] Error running test notebook als_deep_dive on Windows DSVM

### ISSUE THREAD

**Issue by roalexan** [Microsoft/Recommenders#677]
### Description
Get this error running unit test:

`E           papermill.exceptions.PapermillExecutionError:
E           ---------------------------------------------------------------------------
E           Exception encountered at "In [15]":
E           ---------------------------------------------------------------------------
E           TypeError                                 Traceback (most recent call last)
E           <ipython-input-15-9eddaaa7187e> in <module>
E                 4               relevancy_method='top_k', k=TOP_K)
E                 5
E           ----> 6 rank_metrics = {'MAP': map_at_k(*args, **kwargs),
E                 7                 'NDCG': ndcg_at_k(*args, **kwargs),
E                 8                 'Precision': precision_at_k(*args, **kwargs),
E
E           ~\notebooks\Recommenders\reco_utils\evaluation\python_evaluation.py in check_column_dtypes_wrapper(rating_true, rating_pred, col_user, col_item, col_rating, col_prediction, *args, **kwargs)
E                57             raise TypeError(
E                58                 "data types of column {} are different in true and prediction".format(
E           ---> 59                     col_user
E                60                 )
E                61             )`

### In which platform does it happen?
Windows DSVM

### How do we replicate the issue?
The steps are exactly the same as issue https://github.com/Microsoft/Recommenders/issues/616, except the test to run is:
pytest tests/unit -m "not notebooks and not spark and not gpu"
or more specifically:
pytest tests/unit -m "notebooks and not spark and not gpu" -k vw

### Expected behavior (i.e. solution)
should run successfully without any errors

### Other Comments
Had a discussion with Jun and Scott about this. One possible workaround is to make this change to: Recommenders\reco_utils\evaluation\python_evaluation.py:

```
from: if rating_true[col_user].dtypes != rating_pred[col_user].dtypes:
to: if rating_true[col_user].dtype.type.__base__ != rating_pred[col_user].dtype.type.__base__:
```
and
```
from: if rating_true[col_item].dtypes != rating_pred[col_item].dtypes:
to: if rating_true[col_item].dtype.type.__base__ != rating_pred[col_item].dtype.type.__base__:
```
Scott made the following suggestion, which makes a lot of sense:

I think the right solution is to create a couple utility functions to check that columns exists, and another to check that two dataframes have the same base types for columns of interest, or alternatively to remove unnecessary type checks

Another open question is how pervasive this type of check happens - it would be nice to fix this across the repo.

**Comment by gramhagen** [comment]
somewhat related issue: #648

**Comment by gramhagen** [comment]
the easiest solution is to abandon all type checking and column checking and let the exceptions get raised at the lower level. in this instance, doing the join with one dataframe using np.int32 and another using np.int64 works fine, so even caring about this distinction is dubious

**Comment by miguelgfierro** [comment]
Which OS sets the data to int32 and which one to int64?
Another question, apart from the integers, are there problems with other types?

**Comment by roalexan** [comment]
So far I've been running all my test on a Windows DSVM, which is 64 bit. I have not hit any other type errors yet.

**Comment by gramhagen** [comment]
I'm working on a change to putting evaluation. It will handle this error. The code works now. But changes to all notebooks using python evaluation will be needed. PR upcoming...

**Comment by gramhagen** [comment]
ok, this should be fixed in staging, @roalexan can you confirm this fixes the issue you're seeing?
