### ISSUE TITLE
[FEATURE] TensorFlow 1.13 update

### ISSUE THREAD

**Issue by loomlike** [microsoft/recommenders#683]
### Description
Update TensorFlow package version

### Other Comments
Require to refactor deprecated functions and changed APIs

**Comment by miguelgfierro** [comment]
We should also discuss about TF 2.0, it is still in alpha https://github.com/tensorflow/tensorflow/releases but it will have some interesting new features (and probably breaking changes)

**Comment by loomlike** [comment]
@miguelgfierro Do we want to skip 1.13 and directly move to 2.0?

We don't suffer any bugs from 1.12 and thus not sure moving from 1.12 to 1.13 would give any benefit to us. TF2.0, on the other hand, seems has attractive features as you said, e.g. NCF reference model, distributed training API and cleaner APIs.

**Comment by miguelgfierro** [comment]
yeah that makes sense. I wouldn't rush unless we see a big benefit, TF 2.0 could be buggy

**Comment by gramhagen** [comment]
yeah, it would be nice to have a branch where tf 2.0 example was built out so we could compare, ncf might be a good starting point.

**Comment by loomlike** [comment]
Btw, tested 1.13 with `unit/test_tf_utils.py` and `smoke/test_notebooks_gpu.py` and all tests got passed.

**Comment by miguelgfierro** [comment]
Cool, we can upgrade them

**Comment by loomlike** [comment]
@miguelgfierro TF already released 1.14 lol... and I discussed with @gramhagen about the version. We think it makes sense to just stick with the current version we have for now (1.12) since nothing has been broken nor are buggy. Also not very exciting features in .13 and .14 for us.

So we will wait until 2.0 officially released. Is that make sense?

**Comment by miguelgfierro** [comment]
> So we will wait until 2.0 officially released. Is that make sense?

yeah that makes sense

**Comment by miguelgfierro** [comment]
Closing this, feel free to reopen if needed
