### ISSUE TITLE
[FEATURE] add a new folder to put all the code related to tuning: reco_utils/tuning

### ISSUE THREAD

**Issue by miguelgfierro** [microsoft/recommenders#689]
### Description

from a conversation with @anargyri:

>  It would be more appropriate to have a folder called tuning and, under that folder, azureml and nni and the spark tuning code. This would require testing again all the tuning notebooks, so I would leave it for a separate PR. Hyperdrive and NNI rely on several path names, so they will break as soon as you change the folder structure.

### Related
https://github.com/Microsoft/Recommenders/pull/687

**Comment by loomlike** [comment]
azureml may include o16n or remote-compute training related helper scripts in the future, not necessarily limited to tuning. What else do we expect to have other than NNI under the tuning folder?

**Comment by yueguoguo** [comment]
My two cents, if in the `tuning` directory, there are just training scripts instead of "utility" function scripts, would it be better we place them together with the notebooks? Most likely the training scripts are not used by other scripts/notebooks.

**Comment by miguelgfierro** [comment]
interesting idea, @anargyri @loomlike are there any utility functions in the hyperparameter tuning code?

**Comment by anargyri** [comment]
> interesting idea, @anargyri @loomlike are there any utility functions in the hyperparameter tuning code?

I think putting the .py training scripts in the same directory as the notebooks does not look nice and may confuse the reader. I would prefer it as it is now, or maybe have a directory for SVD_hyperdrive, one for wide_and_deep_hyperdrive etc.

There are not any common tuning utils currently.

**Comment by loomlike** [comment]
@anargyri what about put under a child folder (e.g. `scripts`) of the notebooks then? like
`../notebooks/04_model_select_and_optimize/scripts/` ?

**Comment by anargyri** [comment]
TBH most of these suggestions sound good to me. Just in the interest of housekeeping, having .py and .ipynb files together is a bit messy and you need to take care that it is clear which .py corresponds to each .ipynb.

**Comment by anargyri** [comment]
We should probably revisit this issue when / if the hyperparameter tuning repo is open-sourced, since there are some utilities + Kubeflow notebooks there.
