### ISSUE TITLE
[BUG] Error running spark notebooks unit tests on Windows DSVM

### ISSUE THREAD

**Issue by roalexan** [Microsoft/Recommenders#690]
### Description
Running pspark unit tests as described [here ](https://github.com/Microsoft/Recommenders/tree/staging/tests)as follows: pytest tests/unit -m "notebooks and spark and not gpu". Getting error: 3 failed, 2 passed, 129 deselected, 4 warnings. Please see attached file of full stacktrace [here](https://github.com/Microsoft/Recommenders/files/3019448/stacktrace-pyspark-unittests-windowsdsvm.txt) for details.

### In which platform does it happen?
Windows DSVM

### How do we replicate the issue?
Create Windows DSVM, create and activate reco_spark (or reco_full) Python environment, run unit test: pytest tests/unit -m "notebooks and spark and not gpu"

### Expected behavior (i.e. solution)
should not have any errors

**Comment by loomlike** [comment]
changing spark driver's local file path as `file:///` which is a shorten form of `file://localhost/` I will create PR soon once I tested all on Databricks too
