### ISSUE TITLE
[BUG] Spark uses python 2.x

### ISSUE THREAD

**Issue by loomlike** [Microsoft/Recommenders#691]
### Description
I'm getting this error: Python in worker has different version 2.7 than that in driver 3.6.
Run pyspark on my DSVM and found the python version is 2.7

I recently created this DSVM and just followed the SETUP.md  

### In which platform does it happen?
* Azure Data Science Virtual Machine.

### How do we replicate the issue?
Install reco_pyspark

**Comment by loomlike** [comment]
`export PYSPARK_PYTHON=python3.6` this solves the issue.

**Comment by miguelgfierro** [comment]
yeah, this is defined in the setup: https://github.com/Microsoft/Recommenders/blob/master/SETUP.md#dependencies-setup, below spark

**Comment by loomlike** [comment]
@miguelgfierro oh! how did I miss that :-o
