### ISSUE TITLE
[BUG] Remove contrib from azureml

### ISSUE THREAD

**Issue by miguelgfierro** [Microsoft/Recommenders#695]
### Description

The product team mentioned that contrib package is not recomended for production, we need to remove contrib from here `azureml-sdk[notebooks,tensorboard,contrib]==1.0.18` and check that all the tests pass

### In which platform does it happen?

DSVM, DB

### Expected behavior (i.e. solution)

everything runs

### Other Comments
question to @anargyri @loomlike @jreynolds01 @gramhagen @bethz @heatherbshapiro @jingyanwangms are we using contrib anywhere (or planning to use)?

**Comment by loomlike** [comment]
azureml_hyperdrive_wide_and_deep notebook does**n't** use any azureml contrib modules.

**Comment by jingyanwangms** [comment]
papermill PR in progress is using azureml.contrib.notebook. If it's not desired in the yaml file, I can install this package only inside the notebook. Will this work?

**Comment by miguelgfierro** [comment]
mmm, yeah that would be a workaround

**Comment by anargyri** [comment]
Not in the Hyperdrive notebooks.

**Comment by miguelgfierro** [comment]
since @jingyanwangms is the only one using it, can you take care of this issue in your PR?

**Comment by heatherbshapiro** [comment]
Do we want to require people to install things at the beginning of notebooks, though?

**Comment by jingyanwangms** [comment]
azureml.contrib.notebook is required for submitting notebook through aml. But if we don't want azureml.contrib to install as default in base yaml files, @heatherbshapiro what would you recommend doing here?

**Comment by jingyanwangms** [comment]
@miguelgfierro Sure. I can do it in my PR.

**Comment by Raman1121** [comment]
Hey guys
I am getting an error while trying to run this line "from azureml.contrib.notebook import NotebookRunConfig, AzureMLNotebookHandler".
**The error is ModuleNotFoundError: No module named 'azureml.contrib'** although I have installed azureml-contrib-notebook from pip. What should I do?

**Comment by anargyri** [comment]
HI @Raman1121 , which file in the code is this line in?

**Comment by Raman1121** [comment]
I am trying to experiment with jupyter notebook on Azure through API calls by following the code snippet given here - 
https://docs.microsoft.com/en-us/python/api/azureml-contrib-notebook/azureml.contrib.notebook.azuremlnotebookhandler?view=azure-ml-py

**Comment by anargyri** [comment]
Well, this code is not related to the Recommenders GitHub repo. Most likely you have not configured your conda or python settings appropriately.
