### ISSUE TITLE
[BUG] Error running GPU smoke tests on Windows DSVM

### ISSUE THREAD

**Issue by roalexan** [Microsoft/Recommenders#698]
### Description
Running GPU unit tests as described here as follows: pytest tests/smoke -m "smoke and not spark and gpu". Getting error: 4 failed, 4 passed, 15 deselected, 139 warnings. Please see attached file of full stacktrace here for details.
[stacktrace-gpu-smoketests-windowsdsvm.txt](https://github.com/Microsoft/Recommenders/files/3024569/stacktrace-gpu-smoketests-windowsdsvm.txt)

### In which platform does it happen?
Windows DSVM

### How do we replicate the issue?
Create Windows DSVM, create and activate reco_spark (or reco_full) Python environment, run unit test: pytest tests/unit -m "notebooks and spark and not gpu"

### Expected behavior (i.e. solution)
Should not have any errors

**Comment by loomlike** [comment]
@roalexan Can you check this thread and see if this helps? https://github.com/tensorflow/tensorflow/issues/11812

> Try 'Shutdown' the running notebooks which uses your GPU. Restart the kernel.
Run the code again.. This time it should work.

> To be clear, tensorflow will try (by default) to consume all available GPUs. It cannot be run with other programs also active. Closing. Feel free to reopen if this is actually another problem.

**Comment by roalexan** [comment]
I actually started up the VM this morning - but problem persists. Let's take a closer look.

**Comment by roalexan** [comment]
BTW, I switched to use a repo_gpu environment, then the tests passed. Just for kicks, I switched back to the repo_full environment, and it failed again, but with a different error. So, a little hard to understand the delta between these test runs and environments.

**Comment by loomlike** [comment]
So the failure is happening only from `reco_full` right?

**Comment by roalexan** [comment]
you have a point there, Jun. I'm not sure if this is conclusive, but I seem to only to be able to reproduce this occasionally on reco_full. not reco_gpu.

**Comment by loomlike** [comment]
will look into it more in the next couple of days.

**Comment by roalexan** [comment]
can't reproduce at this point - closing.
