### ISSUE TITLE
[Feature] pytest temp directory

### ISSUE THREAD

**Issue by loomlike** [Microsoft/Recommenders#701]
#### Description
Benefit of using pytest fixture `tmp_path` is that pytest handles temp directory creation and cleanup for us. E.g., `tempfile.TemporaryDirectory` may fail to cleanup the directory if the files are being used. On the other hand, pytest's tmpdir module will revisit the existing temp directories next time we run tests and cleanup.

One drawback of using pytest's tmpdir is, it keeps the **last three directories**.  But we want to clean up the directory right after we use it. 

I can think about two options to solve our issue:
##### 1. Use `TemporaryDirectory` with pytest's `tmp_path`:
```
def test_A(tmp_path):
    with TemporaryDirectory(dir=tmp_path) as td:
        ....
```
Pros - TemporaryDirectory will take care of cleanup. If it fails, the worst case is the dir will last for next three tests (and then tmp_path will be cleaned up by the pytest module)
Cons - Every test scripts that uses tmp dir should import TemporaryDirectory 

##### 2. Use `tmp_path_factory` and cleanup by ourselves
```
def test_A(tmp_path_factory):
    td = tmp_path_factory.mktemp("test_1")
    ....
    shutils.rmtree(os.path.abspath(str(td)))
```
Pros - No need to import TemporaryDirectory
Cons - Have to use `rmtree` if we want to clean up right after we use the dir; `pathlib.Path.resolve()` doesn't seem reliable across different platforms so that we need to use `os.path.abspath`

I will probably want to use 1st option....but feel free to share thoughts!

**Comment by yueguoguo** [comment]
+1 on option1. Is it heavy to import Temporary Directory? Given we don't have every testing script importing TemporaryDirectory, maybe the overhead is negligible...

**Comment by miguelgfierro** [comment]
@loomlike, with TemporaryDirectory, when is the directory erased?

**Comment by loomlike** [comment]
@miguelgfierro you're right! Thought we wanted to use *context manager*(which I was obsessed about!) from our test functions which doesn't work with the fixtures, but we don't need to use context manager.

I will use 1st approach with our own fixture (what Miguel showed) for extra safety. Also will use function scope instead of module.

**Comment by miguelgfierro** [comment]
@loomlike, about the context manager thing, there is an alternative in pytests: https://pytest.readthedocs.io/en/2.8.7/yieldfixture.html

maybe yield fixture will allow you to do this:
```
with tmp_dir:
   # do something with tmp_dir
#after leaving the context, the folder is automatically erased
```
is this what you want?
