### ISSUE TITLE
[BUG] Error in mmlspark-lightgbm on Windows

### ISSUE THREAD

**Issue by roalexan** [microsoft/recommenders#709]
### Description
I'm getting an error when running:

pytest tests/unit -m "notebooks and spark and not gpu"
	1 failed, 5 passed, 130 deselected, 4 warnings in 6478.96 seconds

pytest tests/smoke -m "smoke and spark and not gpu"
	1 failed, 3 passed, 20 deselected, 5 warnings in 1011.78 seconds

More specifically, the errors occur in these tests:

	pytest tests/unit/test_notebooks_pyspark.py -k test_mmlspark_lightgbm_criteo_runs
	pytest tests/smoke/test_notebooks_pyspark.py -k test_mmlspark_lightgbm_criteo_smoke

The full stack traces, which are essentially the same for both, are attached:

[error6.txt](https://github.com/Microsoft/Recommenders/files/3043949/error6.txt)
[error7.txt](https://github.com/Microsoft/Recommenders/files/3043950/error7.txt)

### In which platform does it happen?
Windows DSVM

### How do we replicate the issue?
Create Windows DSVM, clone repo, create reco_pyspark Python environment, and run the tests in the description.

### Expected behavior (i.e. solution)
Should run without any errors.

**Comment by miguelgfierro** [comment]
it looks it is not resolving correctly the mmlspark version: `com.microsoft.ml.spark#mmlspark_2.11;0.16.dev8+2.g6a5318b: not found` it is weird that this is happening on windows. @mhamilton723 any idea where the problem could be?

**Comment by roalexan** [comment]
Another possibility is that it's related to a Java pathing issue - e.g. "The installation directory for Java must not have blanks in the path such as in C:\Program Files" as mentioned [here](https://stackoverflow.com/questions/31841509/pyspark-exception-java-gateway-process-exited-before-sending-the-driver-its-po#36367669). Agree that the "unsolved dependency" might be the real problem.

**Comment by roalexan** [comment]
tested with JAVA_HOME=C:\java\Zulu\zulu-8\ on one of my Windows DSVMs - no space in path - still didn't work.

**Comment by roalexan** [comment]
BTW, I created a new Windows DSVM and this time did 'conda update conda' then 'conda install anaconda'. This brings the conda version to 4.6.9, and apparently fixes the problem where the pip installs weren't working. Unfortunately, this issue persists.

**Comment by gramhagen** [comment]
I think there's a bug in the noteboook in how the maven repo info is retrieved, honestly I'm surprised it's working in linux, testing fix now

**Comment by gramhagen** [comment]
@roalexan can you checkout this branch and try it on your environment?
gramhagen/mmlspark_lgbm_win_bug

**Comment by roalexan** [comment]
Hitting an issue. Talked with Scott a bit. Tried set SPARK_HOME="" but problem persists. Scott could reproduce the same issue on a Linux DSVM, and unsetting SPARK_HOME fixed the issue. The main error is: E           Py4JJavaError: An error occurred while calling o96.getParam.
E           : java.util.NoSuchElementException: Param boostFromAverage does not exist.
The full trace is attached here:
[error8.txt](https://github.com/Microsoft/Recommenders/files/3048970/error8.txt)

**Comment by roalexan** [comment]
Tried setting set SPARK_HOME="C:\Anaconda\envs\reco_pyspark\Lib\site-packages\pyspark\jars" - didn't work - file not found exception.

**Comment by loomlike** [comment]
@roalexan @gramhagen Found how to fix the error, here is a go-around way to fix it:
1. unset PYTHONPATH: `set PYTHONPATH=`  (note, this is temporal method. we should find better way to handle this)
2. change lightgbm notebook's mmlspark package path to **stable** version:
```
spark = start_or_get_spark(packages="Azure:mmlspark:0.16") 
```
'1' lets your spark drivers use correct python (our env's) and '2' I guess we've been using a dev version... please confirm, the reason we are using a dev version is because of Markus' optimization work? I can post the exact error message so that Markus or Scott can fix that bug.

**Comment by gramhagen** [comment]
yes, we're using the dev version for Markus's optimization. That is temporary. But it's strange that the dev version does not work and the stable version does. I don't know if they build the final jar differently than dev artifacts?

imo the best way to handle this is to create a script to set (environment variables)[https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#saving-environment-variables]. I wish conda had a post install hook which we could use to automatically create those scripts, although I suppose we could create our own conda package which does this...

**Comment by miguelgfierro** [comment]
hey guys, if there is only one tests that is blocking the development, it might be a good idea to skip it for now, push all the windows part and then come back to this

**Comment by loomlike** [comment]
Proper env variable setup fixes part of this issue. Also mmlspark has a known issue on Windows. Will keep track the thread. Setup instructions has been merged into staging.

**Comment by loomlike** [comment]
Related issue in mmlspark repo:
https://github.com/Azure/mmlspark/issues/483

**Comment by miguelgfierro** [comment]
closing because stale issue, feel free to reopen if needed
