### ISSUE TITLE
[BUG] Sporadic AssertionError running non-notebook/spark/gpu unit tests on Windows DSVM

### ISSUE THREAD

**Issue by roalexan** [Microsoft/Recommenders#731]
### Description
I'm hitting a sporadic assertion error when running:

		conda activate reco_base 
		pytest tests/unit -m "not notebooks and not spark and not gpu"

on a Windows DSVM. See attached file for exact test and associated error.
[sporadic-assertion-error.txt](https://github.com/Microsoft/Recommenders/files/3068962/sporadic-assertion-error.txt)

### In which platform does it happen?
Windows DSVM. I'm not aware of this issue on Linux DSVM.

### How do we replicate the issue?
Spin up Windows DSVM, login, download reco repo, update conda, install anaconda, create and activate reco_base python environment, and run pytest tests/unit -m "not notebooks and not spark and not gpu".

### Expected behavior (i.e. solution)
Should not produce an error. Perhaps there's a way to make things more deterministic.

**Comment by loomlike** [comment]
Created an issue (#736). This bug will be fixed by resolving the issue.
