### ISSUE TITLE
[FEATURE] Refactor utilities that are in the notebook and in the benchmark utils to a common place in reco_utils

### ISSUE THREAD

**Issue by miguelgfierro** [microsoft/recommenders#733]
### Description

ask from @gramhagen and @yueguoguo 

> also it would be awesome to extract thisout as a function that can be used by all algorithms: get_all_user_items(data, user_col, item_col, remove_seen=True)

from [here](https://github.com/Microsoft/Recommenders/pull/715#discussion_r274054120)

> Many of the utilities are used only in the context of benchmarking (they wrap our existing utilities), and some of them have very similar functionalities. Do we want to combine in a way to enhance the readability?

from [here](https://github.com/Microsoft/Recommenders/pull/715#discussion_r273031871)

**Comment by loomlike** [comment]
check `user_item_pairs` in `reco_utils/dataset/pandas_df_utils.py`
is that what "get_all_user_items" is doing?
