### ISSUE TITLE
[FEATURE] Default random-seed to None

### ISSUE THREAD

**Issue by loomlike** [microsoft/recommenders#753]
### Description
* Set modules' default random-seed to be `None` to follow communities' convention.
If None, the random value will most likely generate unpredictable random value, e.g. see [numpy doc](https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.RandomState.html#numpy.random.RandomState).

* Set the seed at notebooks and tests explicitly whenever we want to have deterministic results.

### Expected behavior with the suggested feature
Use seed for reproducibility / Do not use seed for pure random.

**Comment by miguelgfierro** [comment]
I discover the other day that fastai gives back the exact same results, so the seed is working, however, NCF doesn't

**Comment by loomlike** [comment]
I'm working on NCF seed too. Currently blocked by #759

**Comment by miguelgfierro** [comment]
@loomlike, I think this issue is finished right? Should we close it?

**Comment by loomlike** [comment]
@miguelgfierro Our data splitter utils are still using a default seed argument `42`. I think we should use `None` for default instead. What do you think?

**Comment by miguelgfierro** [comment]
yeah definitely we should
