### ISSUE TITLE
[BUG] manual setup instructions to install azureml-sdk[databricks]==1.0.8 don't work

### ISSUE THREAD

**Issue by roalexan** [microsoft/recommenders#765]
### Description
Following the instructions here: https://github.com/Microsoft/Recommenders/blob/1b682fc63b6e154709856c20a9ce355802c054c2/SETUP.md#setup-guide-for-azure-Databricks. 

 I get this error: No matching distribution found for azureml-sdk[databricks]==1.0.8
### In which platform does it happen?
Manually setting up Databricks environment

### How do we replicate the issue?
Follow manual setup instructions

### Expected behavior (i.e. solution)
No error - probably needs to be updated to use correct version

**Comment by gramhagen** [comment]
Looks like the manual description is missing adding pypi dependencies. 

@roalexan  I'm assuming you didn't add any pip package dependencies for the cluster?
@jreynolds01 do you have time to add the manual steps that match the databricks install script?

**Comment by roalexan** [comment]
I just followed the documented steps: uploaded a zipped reco repo egg, then installed azure-cli==2.0.56, then went to install azureml-sdk[databricks]==1.0.8. What pip package dependencies are needed? I thought about upgrading pip (as per the console output), but held off and filed this bug for now.

**Comment by gramhagen** [comment]
I guess I'm confused, are you seeing this error on your local machine or from a databricks notebook?

when you say you went to install azureml-sdk[databricks]==1.0.8 where / how are you doing that?

**Comment by gramhagen** [comment]
I don't think I scrolled all the way down to the operationalization section of the manual instructions, that's the piece that's causing trouble?

**Comment by roalexan** [comment]
yeah, scroll down - see section "AND you must also install some additional dependencies. ". That's where I hit this. This is all from the portal - configuring the cluster.

**Comment by roalexan** [comment]
@gramhagen I've got an environment up and running now where I can reproduce this error.
