### ISSUE TITLE
[BUG] Windows reco_base - tests\unit\test_timer.py:40: AssertionError

### ISSUE THREAD

**Issue by roalexan** [Microsoft/Recommenders#769]
### Description
Windows test on reco_cpu causing an assertion error. The error is here: tests\unit\test_timer.py:40: AssertionError. Here are the error lines:

assert t.interval == pytest.approx(1, abs=TOL)
E       assert 0.9884977 == 1 � 1.0e-02
E        +  where 0.9884977 = <reco_utils.common.timer.Timer object at 0x0000028302638048>.interval
E        +  and   1 � 1.0e-02 = <function approx at 0x0000028373A071E0>(1, abs=0.01)
E        +    where <function approx at 0x0000028373A071E0> = pytest.approx

### In which platform does it happen?
Windows DSVM test machine, running tests using the reco_base python environment.

### How do we replicate the issue?
Create a Windows DSVM, install reco repo, create reco_base python environment, and run tests\unit\test_timer

### Expected behavior (i.e. solution)
Should work without error. I've seen this before, but it only happens sporadically. It happened again, so I logged it. Maybe we need to adjust the acceptable threshold?

**Comment by gramhagen** [comment]
i think the easiest thing to do here is just increase the tolerance, i suggest either 0.03 or 0.05
@miguelgfierro thoughts?

**Comment by miguelgfierro** [comment]
yeah, we an increase the tolerance, but it is weird, time(1) in Windows is not 1 second? lol

**Comment by gramhagen** [comment]
yeah, surprising, on my laptop

```
>>> from time import sleep
>>> import timeit
>>> (timeit.timeit('sleep(1)', number=30, globals=globals()) - 30) / 30
0.0005368666666678716
```
which on avg. is well within tolerance, but it's not a rtos, so i guess it's all variable /shrug

**Comment by roalexan** [comment]
issue now fixed with slightly "relaxed" assertion.
