### ISSUE TITLE
iterator doesn't support the input format of "FM"?

### ISSUE THREAD

**Issue by fly12357** [microsoft/recommenders#777]
Tensorflow version: 1.13.1
python 3.6.8

./xDeepFM/Recommenders/reco_utils/recommender/deeprec/IO/iterator.py

![image](https://user-images.githubusercontent.com/40494145/57456142-61f01000-729f-11e9-9108-fcbd0871502a.png)

./xDeepFM/Recommenders/reco_utils/recommender/deeprec/deeprec_utils.py

![image](https://user-images.githubusercontent.com/40494145/57456202-8a780a00-729f-11e9-8106-e942a7d5179f.png)

It seems that there isn't an useful data iterator script for "FM" format input.

**Comment by gramhagen** [comment]
Hi @fly12357 can you provide a bit more detail where this issue is occurring, what platform, what part of the code? And what the expected behavior is? This will help us debug and address what's happening.

**Comment by fly12357** [comment]
> Hi @fly12357 can you provide a bit more detail where this issue is occurring, what platform, what part of the code? And what the expected behavior is? This will help us debug and address what's happening.

It seems that there isn't an useful data iterator script for "FM" format input.

I modify the "deeprec_utils.py" as below. and change the "FM" format input file to "FFM" format (each feature with a unique field) to solve this problem. 

![image](https://user-images.githubusercontent.com/40494145/57456566-5bae6380-72a0-11e9-88ec-e05f693340f4.png)

**Comment by gramhagen** [comment]
Revisiting this, from looking at the script it seems like the final else clause should be catching the case where model_type == "FM", not the first case. Perhaps there's a discrepancy in your configuration where model_type and data_format are not both "FM"?

I will close it for now, but if this is still an issue let us know how to reproduce it.
