### ISSUE TITLE
[ASK] why ncf has no rating result?

### ISSUE THREAD

**Issue by mit10000** [microsoft/recommenders#796]
### Description
in https://github.com/microsoft/recommenders/blob/master/benchmarks/movielens.ipynb 
the metric setting 
metrics = {
    "als": ["rating", "ranking"],
    "sar": ["ranking"],
    "svd": ["rating", "ranking"],
    "fastai": ["rating", "ranking"],
    "ncf": ["ranking"],
}
means ncf will not evaluate rating, could you please explain why?
Thanks!!

**Comment by gramhagen** [comment]
The output of the model goes through a sigmoid layer, so the results are also between 0-1. In cases where the input ratings are in the same range [0,1], then you could apply rating evaluation metrics. But for this case we're using Movielens data with input ratings in the range [1, 5], so the rating metrics aren't applicable without scaling the inputs or outputs to the same range.

SAR is a similar case, with the standard implementation the output values are not necessarily in the same range as the input ratings so cannot be compared directly, but the ranking can be evaluated.
