### ISSUE TITLE
[FEATURE] Publish the documentation in readthedocs

### ISSUE THREAD

**Issue by miguelgfierro** [microsoft/recommenders#818]

**Comment by yueguoguo** [comment]
May consider prioritizing this.

**Comment by miguelgfierro** [comment]
https://docs.readthedocs.io/en/stable/webhooks.html

**Comment by miguelgfierro** [comment]
MMLSpark folks just have an automated process where they push the document to a blob: https://github.com/Azure/mmlspark/blob/671b68892ace5967e60c7a064effd42dd5a21ec7/build.sbt#L89

This is the final result: https://mmlspark.blob.core.windows.net/docs/0.18.1/pyspark/modules.html

**Comment by gramhagen** [comment]
That sounds great and looks the same as rtd, let's do it.
