### ISSUE TITLE
[BUG] Broken README link: benchmark notebook

### ISSUE THREAD

**Issue by alex-zwingli** [microsoft/recommenders#819]
### Description
The "benchmark notebook" link on the Recommenders README is broken (aka. goes to GitHub 404 Star Wars page).

### In which platform does it happen?
* Online

### How do we replicate the issue?
Click on "benchmark notebook" link under Algorithms > Preliminary Comparison.

### Expected behavior (i.e. solution)
Think link should go to the appropriate notebook.

**Comment by gramhagen** [comment]
Thanks @alex-zwingli! Put in a patch now, we'll roll it through staging and then to master.

**Comment by miguelgfierro** [comment]
fixed in #820
