### ISSUE TITLE
Using recommenders in my own codebase

### ISSUE THREAD

**Issue by atimesastudios** [microsoft/recommenders#824]
### Description
Looking for best practices on how to use recommenders and especially reco_utils with my own codebase. Do I simply clone the repo in a parallel directory and then reference reco_utils that way? I see #774 but until it is available via pip or conda, I'm not sure how best to do this.

**Comment by yueguoguo** [comment]
Hey @atimesastudios so far the recommended way to use `reco_utils` is to clone the repo and reference the utilities in `reco_utils` as modules in your Python own scripts/codes.

**Comment by atimesastudios** [comment]
Thank you @yueguoguo
