### ISSUE TITLE
[BUG] Update readme of o16n

### ISSUE THREAD

**Issue by miguelgfierro** [microsoft/recommenders#829]
### Description

In the o16n readme https://github.com/microsoft/recommenders/tree/staging/notebooks/05_operationalize, we only have the als notebook. Two new notebooks that we did are missing. 

Also, we added some content in the readme, which is not common to all the notebooks. Should we put this content in the als notebook?

Was it @yueguoguo who did this workflow https://github.com/microsoft/recommenders/tree/staging/notebooks/05_operationalize#workflow right? not sure if we should move it to the readme of notebooks.

**Comment by yueguoguo** [comment]
Agree on moving the diagram to the upper level of the directory - it seems more suitable there as it is something general. Also, the plot may need to be updated somehow to reflect the updates of the repo.
