### ISSUE TITLE
[FEATURE] LibffmConverter input type

### ISSUE THREAD

**Issue by yexing99** [microsoft/recommenders#831]
### Description
When I use libffmconverter to do the conversion on movielens dataframe, userID and itemID are not converted correctly after using movielens.load_pandas_df . These two columns are loaded as int. I changed these two columns into string to make the converter work properly. We may need to mention that types of columns need to be "string" if they are categorical variables, in the readme file or description of libffmconverter part.

**Comment by yueguoguo** [comment]
@yexing99 it is mentioned in the docstring of the utility function [here](https://github.com/microsoft/recommenders/blob/89e922b2c8c90d25cc247bbc70ae44a7119b9afe/reco_utils/dataset/pandas_df_utils.py#L90) - the input columns should be either string or numerical indicating the variable are categorical or numerical, respectively.

**Comment by yexing99** [comment]
![image](https://user-images.githubusercontent.com/25463584/59576700-a8027580-908e-11e9-90fa-f3fa4ac17b5f.png)

Another thing I've noticed is that with converting movielens data to libffm, the genres is mapped to a large number (e.g. 2626) , which supposedly less than 20.

**Comment by yueguoguo** [comment]
@yexing99 talked and explained offline - please reopen the issue if there is anything.
