### ISSUE TITLE
[ASK] How to get top 10 recommendations based on a userID and itemID

### ISSUE THREAD

**Issue by karthikraja95** [microsoft/recommenders#849]
Hey all!
@gramhagen 

I know the trained model has predict function that will give a score for that user-item pair.

What I want to know is, If i give a userID say 1001 and a itemID ( say 1234 it might be a new purchase made by the usedID ). How do I incorporate the new itemID (1234) with userID (1001) and give top 10 recommendations i.e the top 10 items for that particular UserID - 1001  considering the new itemID (1234) and also based on the previous interactions?

Thanks!

**Comment by yueguoguo** [comment]
It looks like you are developing a collaborative filtering model for a user-to-item recommendation scenario? If so, in the first place a CF model cannot handle cold items, that is to say, your model can only generate top 10 items (ranked by the predicted scores) for the user (1001), which are existing in the previous interactions. Then if you want to incorporate the new item (1234) you need to put the interactions (if there are) between item-1234 and user-1001 to retrain the CF model. 

Alternative to the above is to use a content-based model where features of users and items are used for predicting scores.

**Comment by karthikraja95** [comment]
Thanks @yueguoguo . I am using NCF notebook and I wanted to implement/try the above mentioned feature. So there is no way I can do this without retraining the CF model?

Also thanks for suggesting content-based model, I will try DKN or VW model which was available in this repo

**Comment by karthikraja95** [comment]
Another quick question? is there a way to recommend top 10 items for a particular user(1001) based on the users history? is there any inbuilt function available in this repo for this feature .

P.S.    I am using NCF deep dive notebook

**Comment by gramhagen** [comment]
@karthikraja95 this implementation of NCF doesn't have a method which will automatically return the top 10 items for a particular user, you will need to score all items for a user and sort them.

It would be possible to generate such a method, please feel free create a pull request if you end up developing some code that you think would be useful.
