### ISSUE TITLE
[BUG] unable to find papermill when running notebook on local Windows laptop

### ISSUE THREAD

**Issue by roalexan** [microsoft/recommenders#852]
### Description
When running the 00_quick_start/sar_movielens.ipynb notebook locally on a Windows PC, it fails, complaining that it can't find 'papermill'. 

### In which platform does it happen?
Local Windows laptop.

### How do we replicate the issue?
Ran through the setup instructions on the home page (installed miniconda, added it to path, cloned repo, activated environment, started jupityr, and ran 00_quick_start/sar_movielens.ipynb).

### Expected behavior (i.e. solution)
There should be no error.

### Other Comments
Please see this Teams channel snippet with Lu Zhang, who originally reported this issue. I replicated the issue on my laptop, and worked around it as follows:

Hello. I have seen in the past that in some environments if a package cannot be found while creating the conda environment, it will abort and consequently skip the remaining package installs. For example, we used to see this before we removed nni testing on Windows - see: https://github.com/microsoft/recommenders/issues/747. Anyway, one way to track down potential missing packages is to compare the 'pip' packages listed in your generated reco_base.yaml file with what you see when you activate your environment and type 'pip list'. FWIW, I ran through the steps just now on my laptop and could reproduce your first error. I shutdown my notebook and pip installed several packages, namely: azure-storage>=0.36.0, fastai==1.0.46, hyperopt==0.1.1, locustio==0.11.0, memory-profiler>=0.54.0, nvidia-ml-py3>=7.352.0, papermill==0.18.2, pydocumentdb>=2.3.3, and pymanopt==0.2.3. After doing this, the notebook worked. Maybe you could try this? As for what caused these packages not to be installed initially, we'll have to look some more.

**Comment by gramhagen** [comment]
This could also be related to #852. Is this error occurring with the latest version of staging or master?

**Comment by roalexan** [comment]
yes, looks related. It was as of last week - haven't tried since then. Has something changed to warrant trying it again?

**Comment by gramhagen** [comment]
well, something is different in staging vs master, but that didn't change in the last week. I was just curious which branch you had replicated the error in.

**Comment by miguelgfierro** [comment]
this is working now
