### ISSUE TITLE
[BUG] NNI issue in conda env creation

### ISSUE THREAD

**Issue by zoewang1989** [microsoft/recommenders#872]
### Description
There is one problem when the process of conda env create, pip install nni error, the detail error snapshot as follow:
Pip subprocess error:
  ERROR: Could not find a version that satisfies the requirement nni==0.5.2.1.1 (from -r /Users/zoewangcn/Projects/recommenders/condaenv.pdwnjard.requirements.txt (line 17)) (from versions: 0.7.1, 0.8.1, 0.9.1, 0.9.1.1)
ERROR: No matching distribution found for nni==0.5.2.1.1 (from -r /Users/zoewangcn/Projects/recommenders/condaenv.pdwnjard.requirements.txt (line 17))

### In which platform does it happen?
MacOS Anaconda3-2019.03

**Comment by yueguoguo** [comment]
Add @scarlett @anargyri @miguelgfierro for visibility.

**Comment by miguelgfierro** [comment]
Not sure if this is a problem with nni on Mac. Can you install any version of nni?

If that works, can you try to install from source?
```
    git clone -b v0.5.2.1.1 https://github.com/Microsoft/nni.git
    cd nni	
    source install.sh	
```

If any of this work, I would consider talking with nni folks directly

**Comment by scarlett2018** [comment]
@zoewang1989 - this probably related to a recent pipeline issue, we are working on it, will update the thread with status later. cc @chicm-ms

**Comment by gramhagen** [comment]
It looks like Windows support has been added in later releases. @scarlett2018 should we move to a more recent version? Are there breaking changes from the version we have now we should be aware of?

**Comment by anargyri** [comment]
> It looks like Windows support has been added in later releases. @scarlett2018 should we move to a more recent version? Are there breaking changes from the version we have now we should be aware of?

Keep in mind that a couple of minor changes are required for one of the tuners if we move to a newer version.

**Comment by scarlett2018** [comment]
@gramhagen @anargyri - we had a new Mac build ready for this issue. @chicm-ms might add more details.

@gramhagen - For the other question about breaking changes, since the v0.5.2.1.1 is a fairly old version, there are some changes might impact you (multiphase feature, annotation features). So, does it make sense that you try the latest version in a branch, and we can standby to help?

**Comment by chicm-ms** [comment]
@zoewang1989  nni v0.5.2.1.1 has been built for MAC, you can retry now.

**Comment by miguelgfierro** [comment]
> @gramhagen - For the other question about breaking changes, since the v0.5.2.1.1 is a fairly old version, there are some changes might impact you (multiphase feature, annotation features). So, does it make sense that you try the latest version in a branch, and we can standby to help?

Do you think if we have a 30min meeting with you guys we could finish the upgrade to the new version and the needed changes in recommenders?

**Comment by scarlett2018** [comment]
> > @gramhagen - For the other question about breaking changes, since the v0.5.2.1.1 is a fairly old version, there are some changes might impact you (multiphase feature, annotation features). So, does it make sense that you try the latest version in a branch, and we can standby to help?
> 
> Do you think if we have a 30min meeting with you guys we could finish the upgrade to the new version and the needed changes in recommenders?

@miguelgfierro - sure thing, go ahead book our time =).

**Comment by miguelgfierro** [comment]
we have a newer version, closing this
