### ISSUE TITLE
[ASK] SAR: use order history instead of user history

### ISSUE THREAD

**Issue by tandav** [microsoft/recommenders#875]
### Description
I want to make recomendations for shopping-cart/product-basket/ [complementary-item-recommendations](https://www.ebayinc.com/stories/blogs/tech/complementary-item-recommendations-at-ebay-scale)

User adds some items to cart and I need to recommend more items to buy with that set of items.

I have list of orders, each containing some items that were bought together.

I want to use SAR model but I want to change `user_id` to `order_id` in the following table:
```
userID  itemID  rating  timestamp
   196     242     3.0  881250949
   186     302     3.0  891717742
    22     377     1.0  878887116
   244      51     2.0  880606923
   166     346     1.0  886397596
```
for rating column I'm gonna choose one of this:
 - just 1
- quantity of each item in order (order can contain some item more than 1 
- item price (maybe with some normalization / scaling)

So I want to fit SAR with order history.  Then I want to make recommendations by passing set of items in the shopping cart to [`get_item_based_topk`](https://github.com/microsoft/recommenders/blob/master/reco_utils/recommender/sar/sar_singlenode.py#L348) method.

What do you think, are there any drawbacks in that logic?

**Comment by yueguoguo** [comment]
> User adds some items to cart and I need to recommend more items to buy with that set of items.

Sounds like an "item-to-item" recommendation scenario. Do you want to use the item similarity matrix to do that?

> I want to use SAR model but I want to change user_id to order_id in the following table

Does this mean that you don't want to "recommend items to users"?

The current implementation of SAR accounts for the co-occurrence of user-item pair to generate the affinity score. See [deep dive notebook](https://github.com/microsoft/recommenders/blob/master/notebooks/02_model/sar_deep_dive.ipynb) for notebook. The recommendation scores from SAR can be normalized by adding the flag `normalize` to be `True`.

**Comment by tandav** [comment]
> Do you want to use the item similarity matrix to do that?
yes, I want to use item similarity matrix (using  [`get_item_based_topk`](https://github.com/microsoft/recommenders/blob/master/reco_utils/recommender/sar/sar_singlenode.py#L348))

> Does this mean that you don't want to "recommend items to users"?
yes, I just need to find similar items to items in shopping cart

The reason why I want to train SAR on order history instead of user history is because

> SAR defines similarity based on item-to-item co-occurrence data. Co-occurrence is defined as the number of times two items appear together for a given user. (from [deep dive notebook](https://github.com/microsoft/recommenders/blob/master/notebooks/02_model/sar_deep_dive.ipynb))

but in my case co-occurrence should be defined as "number of times two items appear together **for a given order** (not for user)". Items should not be similar if some user bought them in two separate orders.

**Comment by gramhagen** [comment]
creating 'users' which are actually unique orders sounds reasonable. i don't see any drawback to using this approach other than the existing memory limitations with using SAR on very large sets of items.

one basic aspect of SAR is to calculate a user preference which can weight the final recommendation, but if you're just get item-based recommendations that won't be used, so the results might be less personalized, but maybe that's not a concern?

It's possible you could generate a simple user preference (either time-weighted or not) and use that after the fact to weight the ratings if you really wanted to.

**Comment by yueguoguo** [comment]
@tandav checking if the problem has been resolved?

**Comment by tandav** [comment]
Yes, thanks for help, closing the issue.
