### ISSUE TITLE
Incorporate VW python bindings from anaconda] 

### ISSUE THREAD

**Issue by gramhagen** [microsoft/recommenders#885]
### Description
VW is now installable via anaconda (for linux), installing from this should provide a more portable solution and will have a path towards windows support as that is added.

### Expected behavior with the suggested feature
leverage python vw wrapper directly in vw example notebook

**Comment by miguelgfierro** [comment]
<img src="https://media.giphy.com/media/AuwBPJztsEWkw/giphy.gif" >
