### ISSUE TITLE
[ASK][HELP] python stratified split 

### ISSUE THREAD

**Issue by karthikraja95** [microsoft/recommenders#892]
Is there a way to split using both item and user in python_statified_split function instead of either using 'user' or 'item'

train_auto, test_auto = python_stratified_split(data_1m,filter_by="item",min_rating=5,ratio=0.80)

I want to split the test and train set, with the same user and items with min_rating of 5 

Any help would be appreciated.

Thanks

**Comment by yueguoguo** [comment]
@karthikraja95 does it help if we do stratification on either user (or item) to generate the data splits, and then get the intersection of items (or users) in the two splits, which is then used to subset the train and test with only those interacted items appearing in them. This can make the user-item matrix identical to both training and testing sets, that is, stratification on both user and item.

**Comment by loomlike** [comment]
I'm closing this issue as it has been inactive for over a month. If needed, please feel free to reopen it.

FYI, see related discussion at [StackOverflow](https://stackoverflow.com/questions/45516424/sklearn-train-test-split-on-pandas-stratify-by-multiple-columns).
