### ISSUE TITLE
[ASK] WideAndDeep - ValueError: Cannot create a tensor proto whose content is larger than 2GB.

### ISSUE THREAD

**Issue by atimesastudios** [microsoft/recommenders#898]
### Description
My work is based on Wide-and-Deep Model Hyperparameter Tuning with AzureML.
I am running hyperparameter tuning on the Wide and Deep algorithm on a problem with about 11000 users and 36000 items, 164000 ratings on an Standard NC12 dedicated Azure. I am running in CPU mode with 118GB of RAM (I run out of memory on the 2 GPU 11GB/per GPU compute instance). In this particular tuning example the algo is set to Deep. My feature vector is len 10. I have 93K training examples and 31K validation examples. The output file shows all of the settings, I've obfuscated project details using '....' in the path names.

This is the structure of my dataframe
<class 'pandas.core.frame.DataFrame'>
Index: 164608 entries, 23 to 222357
Data columns (total 4 columns):
userID          164608 non-null int64
itemID          164608 non-null int64
item_feature    164608 non-null object
rating          164608 non-null int32
dtypes: int32(1), int64(2), object(1)
memory usage: 5.7+ MB

userID | itemID | item_feature | rating
12464 | 156047 | [0, 0, 0, 0, 0, 0, 1, 0, 0, 0] | 3

So it should be very similar to MovieLens used in the recommenders example notebooks.

I've included the stack track that ends in tensor_util.py with the error message ValueError: Cannot create a tensor proto whose content is larger than 2GB.

The first level of the stack trace seems to be when we are trying to get the predictions.

ValueError                                Traceback (most recent call last)
<ipython-input-16-2a1bd132a6a1> in <module>
      1 if len(RANKING_METRICS) > 0:
----> 2     predictions = list(model.predict(input_fn=tf_utils.pandas_input_fn(df=ranking_pool)))
      3     prediction_df = ranking_pool.copy()
      4     prediction_df[PREDICT_COL] = [p['predictions'][0] for p in predictions]
      5 

I'm looking to understand if further code modifications may be needed to the notebooks and scripts to handle my dataset and problem.

### Other Comments
[70_driver_log_tf_error.txt](https://github.com/microsoft/recommenders/files/3482422/70_driver_log_tf_error.txt)

**Comment by atimesastudios** [comment]
notebooks/04_model_select_and_optimize/azureml_hyperdrive_wide_and_deep.ipynb
In this file it looks like the implementation chunks the ranking_pool, the author comments:

> If we put all ranking_pool into a tensor, we get error (since the content limit is 2GB). We divide ranking_pool into 5 chunks, make prediction, and concat the results. 

However, in **notebooks/00_quick_start/wide_deep_movielens.ipynb**, it looks like the implementation
attempts to predict the ranking_pool one-shot, **this is where I get the 2GB limit error.**


The implemention needs to be changed to chunk through the ranking_pool the same way as it is done in notebooks/04_model_select_and_optimize/azureml_hyperdrive_wide_and_deep.ipynb

**Comment by loomlike** [comment]
Thanks for the feedback! I will take a look at this issue and see the best way to handle this, including looking into newer tf version.

**Comment by atimesastudios** [comment]
@loomlike - Thank you for looking into this, much appreciated. Please let me know if I can be on any assistance.

**Comment by atimesastudios** [comment]
Hi @loomlike  - any thoughts on this?

**Comment by loomlike** [comment]
@atimesastudios Sorry, I was busy for doing other stuffs. Regarding this, I will take a look over the weekend!

**Comment by loomlike** [comment]
@atimesastudios chunking dataframe into smaller dataframes is a temporal workaround as the tf exported model accepts Examples object and input_fn_for_exported_model puts all the samples into the object which is prone to cause tensor size > 2GB.

I think you should be able to control the error by decreasing your batch-size.

At the same time, I'm working on moving tf model save-load behavior in our repository from "exporting SavedModel" to "saving the checkpoints". With that, you'll easily load model and re-train / re-evaluate.

**Comment by atimesastudios** [comment]
Thank you @loomlike, I will run smaller batch sizes and give it a try.

**Comment by yueguoguo** [comment]
Reopen if needed
