### ISSUE TITLE
[FEATURE] Improve performance of score() in SAR

### ISSUE THREAD

**Issue by zegerius** [microsoft/recommenders#907]
### Description
Every time the SARSingleNode.score(**) is called for a list of users, it actually calculates the scores for all users. In our training-set of nearly .5M rows the dot product of the 'User Affinity'-matrix and 'Item Similarity'-matrix takes roughly 5+ seconds. The sizes of these matrices are respectively (23009, 17262) and (17262, 17262). This is too slow when calculating recommendations for one user.

### Expected behavior with the suggested feature
Optimize calculations by only calculating the scores for the specified users.

### Other Comments
This is already a TODO: https://github.com/microsoft/recommenders/blob/71a38d422c00329f8f8226ea24ad6260b1b7b4e9/reco_utils/recommender/sar/sar_singlenode.py#L304

**Comment by yueguoguo** [comment]
This is indeed something useful to have. Thanks @zegerius

Add @maxkazmsft who is the original author for visibility and awareness.

**Comment by zegerius** [comment]
Thanks @yueguoguo.

@Overv and I started working on a fix. Our first version still fails some tests for removing seen items, but the performance without removing seen items went to 33ms (99.4% improvement).

**Comment by yueguoguo** [comment]
@zegerius great to know. What is the detailed failure for tests in removing seen items?

**Comment by Overv** [comment]
@yueguoguo We've changed the code to select just the slice of the user affinities matrix that corresponds with the users that we actually want to predict. However, this new "incomplete" matrix makes it harder to use the existing logic/maths for removing seen items from it.

**Comment by gramhagen** [comment]
that's great, yeah this is why it's remained a todo for so long =)

the approach that was in my head was to construct a sparse matrix (of -np.infs) for the seen items of the same size as user_affinity, then you could slice it the same way you are slicing user_affinity for relevant users and that to the score matrix.
