### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by rogerrojur** [microsoft/recommenders#911]
### Description
Py4JJavaError                             Traceback (most recent call last)
<ipython-input-11-d62d244977dc> in <module>
      9 )
     10 
---> 11 data = movielens.load_spark_df(spark, size=MOVIELENS_DATA_SIZE, schema=schema)
     12 data.show()

D:\tuijian\Recommenders\reco_utils\dataset\movielens.py in load_spark_df(spark, size, header, schema, local_cache_path, dbutils, title_col, genres_col, year_col)
    451         # Cache and force trigger action since data-file might be removed.
    452         df.cache()
--> 453         df.count()
    454 
    455     return df
### In which platform does it happen?
windows 10

### How do we replicate the issue?
I follow the setup.md to create the environment reco_pyspark. When I start the test for "als_movielens.ipynb", this error occur, and there is no detail description for this bug, so confusing.

**Comment by gramhagen** [comment]
Is this the entire error message generated? Usually there's a section indication the type of error. Running a single node spark instance on Windows can be a little tricky so there could be a few things going on. Any additional output will help Barrow it down.

**Comment by yueguoguo** [comment]
Reopen if needed.
