### ISSUE TITLE
[FEATURE] Consider adding BPR model with a tutorial

### ISSUE THREAD

**Issue by tqtg** [microsoft/recommenders#931]
### Description

`Bayesian Personalized Ranking (BPR)` is a well-established model for implicit feedback. I would like to contribute a tutorial using `BPR` model with the usage of Cornac library @ https://github.com/PreferredAI/cornac

**Comment by gramhagen** [comment]
Definitely agree. Would love to see your contribution. Putting it as a notebook in the  notebooks/02_model section. You can add that as a dependency to the conda environment to support this.

**Comment by miguelgfierro** [comment]
hi @tqtg, it would be nice to have your contribution. Ideally, what we are doing with other algos is to use our [dataloaders](https://github.com/microsoft/recommenders/blob/master/reco_utils/dataset/movielens.py#L143) and [splitters](https://github.com/microsoft/recommenders/blob/master/reco_utils/dataset/python_splitters.py#L19). 

Then with that data we will put it into your model. Normally we will use `model.fit` but it can be any other method your library has. Then we will have either `model.predict` for rating or `model.recommend_k_items` for ranking. In this part, if the library is already developed, we normally try to add the minimum possible addition. Maybe a good example is [the surprise utilities](https://github.com/microsoft/recommenders/blob/master/reco_utils/recommender/surprise/surprise_utils.py). Here the functions that we have are a small refactoring of the original content of surprise library, but we don't reinvent the wheel here.

And then finally, we will input the results on our ranking or rating [metrics](https://github.com/microsoft/recommenders/blob/master/reco_utils/evaluation/python_evaluation.py). 

We have two kinds of algorithm content, one are the [quick starts](https://github.com/microsoft/recommenders/blob/master/notebooks/00_quick_start/sar_movielens.ipynb), where we just show quickly how to run an algo. The others are the [deep dives](https://github.com/microsoft/recommenders/blob/master/reco_utils/evaluation/python_evaluation.py), where we explain the math and show an algo implementation.

I think for your case it would be good to do a deep dive.

Please let us know if you need any help in designing the content. We would be happy to help

**Comment by tqtg** [comment]
Thank you for your instructions @miguelgfierro !
I'm working on my PR and will seek your suggestions when I have the first draft.

**Comment by tqtg** [comment]
Since we already have `BPR` model, I would like to add it to the benchmark notebook. Is it something we are interested in?

**Comment by gramhagen** [comment]
yes, definitely. I'll add a separate issue so we can close this out.
