### ISSUE TITLE
[BUG] Readthedoc build was successful but in the build there were some issues

### ISSUE THREAD

**Issue by yueguoguo** [microsoft/recommenders#942]
### Description
Some of the content in the readthedoc documentation is not rendered. For example, many of the dataset utilities are not presented. See below

![image](https://user-images.githubusercontent.com/1726448/65586641-107ac000-dfb7-11e9-8cbd-f33d27479c1e.png)

I rerun the build on the readthedoc project, and the build can be successfully run. However, if we take a look at the details in the process there are some issues because of missing packages required for loading the utility functions. Note running the build of the html files in a local recommender conda environment does not have the issue. 

### In which platform does it happen?
N/A

### How do we replicate the issue?
If we run the build on readthedoc, and take a look at the internal steps for the build, the following errors can be found. 
![image](https://user-images.githubusercontent.com/1726448/65586368-a5c98480-dfb6-11e9-8443-30f8f103313a.png)

Having read the documentation about readthedoc, it seems like we need to use a configuration file to specify the environment used by readthedoc to mitigate the problem. Reference can be found here https://docs.readthedocs.io/en/stable/config-file/v2.html

### Expected behavior (i.e. solution)
The build on readthedoc should pass successfully and the html should be rendered properly on the website

**Comment by miguelgfierro** [comment]
I'll take this one

**Comment by miguelgfierro** [comment]
it looks that for being able to generate the conda file we need to add a process like this one: http://www.sphinx-doc.org/en/master/extdev/appapi.html#sphinx-core-events

**Comment by laserprec** [comment]
Closing this since the related issue is closed as well.
