### ISSUE TITLE
[ASK] In wide and deep, how to add more than one item/user feature?

### ISSUE THREAD

**Issue by atimesastudios** [microsoft/recommenders#947]
### Description
Request for how to use build_feature_columns() in wide_deep_utils.py when using item and or user features.

### Other Comments
The example notebooks use the genre column from the MovieLens database. Please provide an example of how to use item_feat_col and item_feat_shape if we want to use more than one feature column from item and/or user information.

**Comment by loomlike** [comment]
Easier path is to make a feature vector `np.array(np.float32)` that includes all the features just like how we make a feature vector for classification or regression problems. In your case, both user-features and item-features into the same np.array. Then put that array to a column and pass the column as `item_feat_col`.

If you want to keep those two features in separate columns for some reason, you can make a feature like
```
tf.feature_column.numeric_column(
    YOUR_FEAT_COL, shape=YOUR_FEAT_SHAPE, dtype=tf.float32
)
```
and add that to the deep columns list. Both will be the same to the model as those features are simply the input nodes and they are all fully connected by the next hidden layer.

**Comment by atimesastudios** [comment]
Thank you @looklike, that is a very helpful explanation and I will try it immediately.
