### ISSUE TITLE
[FEATURE] BPR quick start notebook

### ISSUE THREAD

**Issue by tqtg** [microsoft/recommenders#951]
### Description

Should we have a simplified version of the BPR deep dive notebook in `00_quick_start`?
If yes, I can create a PR on this.

**Comment by gramhagen** [comment]
It's not necessary to cover all algorithms in both model and quickstart. We probably have more than is needed in quickstart anyway =).

Are there other algorithms that we can easily include from cornac? One common baseline in particular is SLIM. That would be nice to include.

**Comment by tqtg** [comment]
I see. Unfortunately, we haven't covered SLIM in Cornac yet :)
Another simple baseline we could have is `Non-Negative Matrix Factorization (NMF)`, or even the simplest `Most Popular Items` (not personalized) for testing/benchmarking purposes.

In addition, Cornac covers quite a few content-based models. I will consider contributing one of them at some point ^^
