### ISSUE TITLE
[DISCUSSION] Deep-learning model and GPU environment

### ISSUE THREAD

**Issue by loomlike** [microsoft/recommenders#952]
### Description
We had a good discussion about deep-learning models on GPU tests (#436),
and as a result, we are testing such models only on GPU.

However, we still have the deep-learning packages (e.g. tensorflow) at the base environment where the codes that uses those packages are not being tested. Should we remove deep-learning packages from the base environment too?

**Comment by loomlike** [comment]
found some people use those models on cpu (#898)... then the question is, do we want to test deep learnings on cpu? ....

**Comment by yueguoguo** [comment]
I think there is a possible scenario where people use TF or other packages for DL algorithms for prototyping and experimenting in an environment without a GPU device. In that case, the base conda env does not block users from doing such before they move to a machine with GPU for acceleration.

**Comment by gramhagen** [comment]
Maybe adding a flag and documentation on how to opt out of the DL packages when building the conda end would be useful? I don't think we need extra testing for the CPU environment unless there are explicit issues we are seeing.

**Comment by miguelgfierro** [comment]
> I think there is a possible scenario where people use TF or other packages for DL algorithms for prototyping and experimenting in an environment without a GPU device. In that case, the base conda env does not block users from doing such before they move to a machine with GPU for acceleration.

Agree

I think testing only in GPU environment is reasonable, the perfect thing would  be to have a 100% coverage, but I think we can assume that if something works on GPU, it will work on CPU. Under this assumption we are trusting the tests of TF or Pytorch on cpu

**Comment by loomlike** [comment]
Got it. Thanks for the discussion!
