### ISSUE TITLE
[FEATURE] TensorFlow 2.0

### ISSUE THREAD

**Issue by loomlike** [microsoft/recommenders#953]
### Description
tf2.0 has released. It has some breaking changes from v1.xx. I'm testing the new API and updating tf_utils and models.

### Expected behavior with the suggested feature
To use v2.0, `import tensorflow as tf`. For v1.xx codes, use `tf.compat.v1` module or simply `import tensorflow.compat.v1 as tf`.

To disable v2.0 behavior (e.g. the new eager execution), run `tf.compat.v1.disable_v2_behavior()`.

**Comment by miguelgfierro** [comment]
as of today, there are still some problems with TF2 https://github.com/tensorflow/tensorflow/issues/38839, I think we should pause the migration. Propose to upgrade TF to 1.15.2
