### ISSUE TITLE
[FEATURE] Migrate AzureML service 'ContainerImage' usage to 'Environments'

### ISSUE THREAD

**Issue by Chris113113** [microsoft/recommenders#962]
### Description
Creating and deploying a ContainerImage is soon-to-be deprecated functionality inside of AzureML service.

The new recommended flow is instead to prepare an Environment object that contains your Pip/Conda requirements and simply include this in your InferenceConfiguration to be supplied in a Model.deploy() call.

This speeds up image build and service deployment time, and allows subsequent service deployments to leverage existing prepared Environment images.

Documentation on Environments can be found here: https://docs.microsoft.com/en-us/azure/machine-learning/service/how-to-use-environments

### In which platform does it happen?
Azure Machine Learning service

### How do we replicate the issue?
* Train your model
* Register a model with AzureML service
* Create a ContainerImage
* Deploy that ContainerImage as an AKS Webservice

### Expected behavior (i.e. solution)
* Create a shared Environment for training and deploying models
* Train your model locally or on a remote compute in the given environment
* Register a model with AzureML service
* Deploy that model as an AKS Webservice

**Comment by yueguoguo** [comment]
@Chris113113 Do we have an estimation about timeline for such deprecation?
