### ISSUE TITLE
[ASK] xDeepFM - Help on saving model checkpoint to Azure ML output directory

### ISSUE THREAD

**Issue by elogicsal** [microsoft/recommenders#970]
### Description

I've taken the xDeepFM deep dive notebook and adapted it so that it can run in Azure Machine Learning Service. I would like Azure to capture the model checkpoints and associated files so that I can download the best run and visualize training in Tensorboard, as well as restore the model at a later point in time. Currently, I do not see any of the model files captured (AML Service needs these to be in the outputs directory).

![image](https://user-images.githubusercontent.com/46599524/68155166-27e28c80-ff17-11e9-8fb3-ffffacfd74a0.png)

It appears that MODEL_DIR is used in a concatenation above. Should MODEL_DIR be passed in the form of a string such as './outputs' or as an os.path.join type construct?

![image](https://user-images.githubusercontent.com/46599524/68155560-f0c0ab00-ff17-11e9-9116-70d83f0be196.png)

When I tried the above on my local machine, I get the summaries nicely placed in the summaries directory under the outputs directory as I would expect. However the model files are placed in the outputs directory and are prepended with "model"

![image](https://user-images.githubusercontent.com/46599524/68155724-3da48180-ff18-11e9-8f37-2b0b84fb9934.png)

When I run this in Azure ML Service, summary files and model files are not available for download. My hunch is that the relative directory must be off.

Any tips on how to set up MODEL_DIR correctly in order to get the files placed in the outputs directory and how to set this up for running in Azure ML Service would be welcome.

**Comment by miguelgfierro** [comment]
maybe @eedeleon can help here?

**Comment by elogicaadith** [comment]
@miguelgfierro: I have a solution to this problem. It involves adding a "/" to the save_path string as shown below:

![image](https://user-images.githubusercontent.com/58820992/70727058-05d5ea00-1ccd-11ea-9479-7c38a1c46407.png)

This code is located in base_model.py. I have validated that this works on the Azure Machine Learning service.

![image](https://user-images.githubusercontent.com/58820992/70727158-328a0180-1ccd-11ea-8767-913b45753884.png)

I'm in the process of validating that the change works on local notebooks as well. Will you accept a pull request for this?

**Comment by elogicaadith** [comment]
@miguelgfierro: Just finished testing this change on the local xdeeepfm notebook in 00_quick_start:

![image](https://user-images.githubusercontent.com/58820992/70730609-4f293800-1cd3-11ea-94b8-462eb2958763.png)

contents of the local folder in my C: drive -

![image](https://user-images.githubusercontent.com/58820992/70730702-77189b80-1cd3-11ea-9ce5-e4c90d631817.png)

**Comment by miguelgfierro** [comment]
Thanks @elogicaadith I added a comment, can you please take a look?
