### ISSUE TITLE
[BUG]  SARSingleNode deprecated

### ISSUE THREAD

**Issue by konabuta** [microsoft/recommenders#989]
### Description

[sar_movielens_with_azureml.ipynb](https://github.com/microsoft/recommenders/blob/master/notebooks/00_quick_start/sar_movielens_with_azureml.ipynb) failed with error. It is because of  **SARSingleNode** doesn't accept `remove_seen`.

### In which platform does it happen?

Azure Machine Learning Notebook VM

### How do we replicate the issue?

I followed this link _**[Getting Started](https://github.com/microsoft/recommenders#getting-started)**_ to install Python(reco) kernel. I just run the [sar_movielens_with_azureml.ipynb](https://github.com/microsoft/recommenders/blob/master/notebooks/00_quick_start/sar_movielens_with_azureml.ipynb). 

You will get the error message like `Error occurred: User program failed with TypeError: __init__() got an unexpected keyword argument 'remove_seen'`

### Expected behavior (i.e. solution)

Training script should pass successfully

### Other Comments
I attached my notebook that works. I changed the following code.
- SARSingleNode -> SAR
- add `remove_seen` to `model.recommend_k_items` method

If there's no problem in my proposed chanage, I want to contribute to this project. Please provide label.
[sar_movielens_with_azureml.ipynb.zip](https://github.com/microsoft/recommenders/files/3902522/sar_movielens_with_azureml.ipynb.zip)

**Comment by yueguoguo** [comment]
Hi @konabuta, the constructor of `SARSingleNode` does not take `remove_seen` as an input argument (see line [here](https://github.com/microsoft/recommenders/blob/7c0a6a3e23dee047b9afbf8564bd236a8300454e/reco_utils/recommender/sar/sar_singlenode.py#L26)). It is instead used in the method of `recommend_k_items` (see line [here](https://github.com/microsoft/recommenders/blob/7c0a6a3e23dee047b9afbf8564bd236a8300454e/reco_utils/recommender/sar/sar_singlenode.py#L417)). 

In the notebook, it looks there is no `remove_seen` in the inputs of the constructor of the SARSingleNode (see [here](https://github.com/microsoft/recommenders/blob/master/notebooks/00_quick_start/sar_movielens_with_azureml.ipynb)). Did you add that by yourself? Do note that the remove seen items operation only apply to the recommendation steps, and this is why it is not an input of the constructor itself.

Hope this clarifies.

**Comment by konabuta** [comment]
I found the following code in this [notebook](https://github.com/microsoft/recommenders/blob/master/notebooks/00_quick_start/sar_movielens_with_azureml.ipynb). I don't add by myself.

```python
model = SARSingleNode(
    remove_seen=True, similarity_type="jaccard", 
    time_decay_coefficient=30, time_now=None, timedecay_formula=True, **header
)
```

Could you check again ?

Thanks,
Keita

**Comment by miguelgfierro** [comment]
good catch @kanobuta, you are right, we need to change that. The correct code would be:
```
model = SAR(
    col_user="userID",
    col_item="itemID",
    col_rating="rating",
    col_timestamp="timestamp",
    similarity_type="jaccard", 
    time_decay_coefficient=30, 
    timedecay_formula=True
)
```
We would do a PR fixing this soon

**Comment by konabuta** [comment]
@miguelgfierro Thank you for your confirmation !

**Comment by miguelgfierro** [comment]
@konabuta that would be fantastic, feel free to take any issue or bug in the list https://github.com/microsoft/recommenders/issues. And thanks again for finding the bug
