### ISSUE TITLE
how can I use this notebook functions with implicit feedback

### ISSUE THREAD

**Issue by m-idasa** [microsoft/recommenders#992]
#### I have data with implicit feedback for some items, this feedbacks can be "join", "check" or "leave". 
How can I use this notebook functions to recommend users with this data?

**Comment by yueguoguo** [comment]
Hi @m-idasa quite some algorithms work with implicit data. For example, in SAR (see [here](https://github.com/microsoft/recommenders/blob/master/notebooks/02_model/sar_deep_dive.ipynb)) the event type of user-item interaction corresponds to the type of the feedback in your case, and SAR algorithms takes that type information as weights in calculating the affinity score.

**Comment by yueguoguo** [comment]
Close this issue but feel free to reopen is if necessary. @m-idasa
